# Bibliographie du cours.
# BIB_WEEK : références utilisées dans chaque semaine (œuvres, critique, ponts italiens).
# BIB : bibliographie générale par rubriques. (texte, lien ou None)

BIB_WEEK = {
1: ["Jean-Jacques Rousseau, Les Rêveries du promeneur solitaire, rédigées en 1776-1778, publication posthume en 1782.",
    "Bernardin de Saint-Pierre, Paul et Virginie, 1788.",
    "François-René de Chateaubriand, Génie du christianisme, 1802 (René y illustre le chapitre « Du vague des passions » ; édition séparée avec Atala en 1805).",
    "Germaine de Staël, De la littérature, 1800 ; De l'Allemagne, imprimé en 1810, pilonné, publié à Londres en 1813.",
    "Ugo Foscolo, Ultime lettere di Jacopo Ortis, édition de 1802.",
    "Paul Viallaneix (dir.), Le Préromantisme : hypothèque ou hypothèse ?, Paris, Klincksieck, 1975 (colloque de Clermont-Ferrand, 1972).",
    "Yves Stalloni, Écoles et courants littéraires, chapitre « Le dix-neuvième siècle », section « Prélude au Romantisme ».",
    "Daniel Grojnowski, Lire la nouvelle, Paris, Dunod, 1993.",
    "Jean-Marie Schaeffer, Qu'est-ce qu'un genre littéraire ?, Paris, Seuil, 1989.",
    "Claude Duchet, « Pour une socio-critique ou variations sur un incipit », Littérature, n° 1, 1971."],
2: ["Alphonse de Lamartine, Méditations poétiques, 1820 (Le Lac).",
    "Victor Hugo, Préface de Cromwell, 1827 ; Hernani, 1830 (préface : le romantisme comme libéralisme en littérature).",
    "Alfred de Musset, La Confession d'un enfant du siècle, 1836 ; Lettres de Dupuis et Cotonet, 1836.",
    "Prosper Mérimée, Mateo Falcone, Revue de Paris, mai 1829 ; repris dans Mosaïque, 1833.",
    "Stendhal, Racine et Shakespeare, 1823-1825.",
    "Théophile Gautier, Histoire du romantisme, 1874 (posthume) : le récit de la première d'Hernani par un témoin.",
    "Paul Bénichou, Le Sacre de l'écrivain, 1750-1830, Paris, José Corti, 1973.",
    "Anne Ubersfeld, Le Drame romantique, Paris, Belin, 1993.",
    "Alessandro Manzoni, Lettre à M. Chauvet sur l'unité de temps et de lieu dans la tragédie, écrite en 1820, publiée en 1823.",
    "Giovanni Berchet, Lettera semiseria di Grisostomo al suo figliuolo, 1816."],
3: ["Stendhal, Le Rouge et le Noir. Chronique de 1830, 1830.",
    "Honoré de Balzac, Le Père Goriot, 1835 ; Avant-propos de La Comédie humaine, 1842.",
    "Théophile Gautier, La Morte amoureuse, Chronique de Paris, juin 1836.",
    "Charles-Augustin Sainte-Beuve, « De la littérature industrielle », Revue des Deux Mondes, 1er septembre 1839.",
    "Marie-Ève Thérenty et Alain Vaillant, 1836. L'An I de l'ère médiatique, Paris, Nouveau Monde, 2001.",
    "Dominique Kalifa, Philippe Régnier, Marie-Ève Thérenty et Alain Vaillant (dir.), La Civilisation du journal, Paris, Nouveau Monde, 2011.",
    "Tzvetan Todorov, Introduction à la littérature fantastique, Paris, Seuil, 1970.",
    "Alessandro Manzoni, I promessi sposi, édition définitive 1840-1842."],
4: ["Charles Baudelaire, Les Fleurs du mal, 1857 ; Petits poèmes en prose (Le Spleen de Paris), posthume, 1869.",
    "Gustave Flaubert, Madame Bovary, 1857 (le réquisitoire d'Ernest Pinard et la plaidoirie de Jules Senard figurent en annexe de nombreuses éditions) ; Trois Contes, 1877.",
    "Théophile Gautier, préface de Mademoiselle de Maupin, 1835.",
    "Aloysius Bertrand, Gaspard de la nuit, 1842 (modèle revendiqué du poème en prose).",
    "Yves Stalloni, Écoles et courants littéraires, sections « Le Parnasse » et « Le Réalisme ».",
    "Pierre Bourdieu, Les Règles de l'art. Genèse et structure du champ littéraire, Paris, Seuil, 1992.",
    "Gisèle Sapiro, La Responsabilité de l'écrivain. Littérature, droit et morale en France (XIXe-XXIe siècle), Paris, Seuil, 2011."],
5: ["Émile Zola, Mes Haines, 1866 ; Le Roman expérimental, 1880 ; Germinal, 1885.",
    "Les Soirées de Médan (Zola, Maupassant, Huysmans, Céard, Hennique, Alexis), Paris, Charpentier, 1880.",
    "Jules Barbey d'Aurevilly, Les Diaboliques, 1874.",
    "Alphonse Daudet, La Dernière Classe, 1872, repris dans les Contes du lundi, 1873.",
    "Guy de Maupassant, Le Horla, 1887 (seconde version) ; « Le Roman », préface de Pierre et Jean, 1888.",
    "Edmond et Jules de Goncourt, préface de Germinie Lacerteux, 1865.",
    "Jules Huret, Enquête sur l'évolution littéraire, 1891.",
    "Colette Becker, Lire le réalisme et le naturalisme, Paris, Armand Colin.",
    "Pierre Cogny, Le Naturalisme, Paris, PUF, coll. Que sais-je ?, 1959.",
    "Jacques Bainville, Au seuil du siècle. Études critiques, 1927 : « L'école naturaliste » (4 octobre 1902), « Un père et un fils » (7 juin 1902).",
    "Christophe Charle, Naissance des « intellectuels », 1880-1900, Paris, Minuit, 1990.",
    "Anne-Marie Thiesse, La Création des identités nationales, Paris, Seuil, 1999 (pour Daudet, l'Alsace et le Félibrige).",
    "Giovanni Verga, Vita dei campi, 1880 ; I Malavoglia, 1881. Luigi Capuana, théoricien du verismo."],
6: ["Arthur Rimbaud, lettres à Georges Izambard (13 mai 1871) et à Paul Demeny (15 mai 1871), dites lettres du Voyant ; Le Bateau ivre, 1871.",
    "Paul Verlaine, Les Poètes maudits, 1884 ; Jadis et naguère, 1884 (Art poétique, Langueur).",
    "Jean Moréas, « Le Symbolisme », Le Figaro, supplément littéraire, 18 septembre 1886.",
    "Auguste de Villiers de l'Isle-Adam, Contes cruels, 1883 (Véra).",
    "Joris-Karl Huysmans, À rebours, 1884.",
    "Rémy de Gourmont, Le Livre des masques, Mercure de France, 1896.",
    "Pierre V. Zima, Manuel de sociocritique, Paris, Picard, 1985 ; rééd. L'Harmattan, 2000.",
    "Guy Michaud, Message poétique du symbolisme, Paris, Nizet.",
    "Yves Stalloni, Écoles et courants littéraires, section « Le Symbolisme ».",
    "Giovanni Pascoli, Il fanciullino, 1897 ; Gabriele D'Annunzio, Il piacere, 1889."],
7: ["Oscar Wilde, Salomé, drame en un acte, écrit en français, Paris, 1893.",
    "Alfred Jarry, Ubu Roi, Théâtre de l'Œuvre, 10 décembre 1896.",
    "André Gide, Les Nourritures terrestres, 1897.",
    "René Vivien, Études et préludes, Paris, Lemerre (la fiche indique 1902 ; l'édition originale est généralement datée de 1901).",
    "Stéphane Mallarmé, « Crise de vers », repris dans Divagations, 1897.",
    "Maurice Maeterlinck, Pelléas et Mélisande, 1892.",
    "Jacques Bainville, Au seuil du siècle, 1927 : « Le poète maudit » (13 avril 1904), « Un poète vraiment mystique » (30 juillet 1904), « Une confession des enfants du siècle » (21 juin 1901).",
    "Pascale Casanova, La République mondiale des lettres, Paris, Seuil, 1999 (pourquoi des étrangers écrivent en français à Paris).",
    "Michel Lioure, Le Drame, Paris, Armand Colin, coll. U, 1963."],
8: ["Filippo Tommaso Marinetti, « Manifeste du futurisme », Le Figaro, 20 février 1909.",
    "Blaise Cendrars et Sonia Delaunay, La Prose du Transsibérien et de la petite Jehanne de France, 1913.",
    "Alain-Fournier, Le Grand Meaulnes, 1913. André Gide, Les Caves du Vatican, 1914.",
    "Guillaume Apollinaire, Alcools, 1913 (Zone). Paul Valéry, « La Crise de l'esprit », 1919.",
    "André Breton, Manifeste du surréalisme, 1924. René Maran, Batouala, prix Goncourt 1921.",
    "Myriam Juan, Les Années folles, Paris, PUF, coll. Que sais-je ?.",
    "Jean-Yves Le Naour, 1922-1929. Les années folles ?, Paris, Perrin, 2022.",
    "Luigi Pirandello, Six personnages en quête d'auteur, mise en scène de Georges Pitoëff, Paris, 1923."],
}

BIB = [
("Histoires littéraires et manuels", [
  ("Pierre Brunel, Yvonne Bellenger, Daniel Couty, Philippe Sellier, Michel Truchet, Histoire de la littérature française, t. 2, Paris, Bordas (référence de la fiche du cours).", None),
  ("André Lagarde et Laurent Michard, XIXe siècle, Paris, Bordas (anthologie de référence de la fiche).", None),
  ("Yves Stalloni, Écoles et courants littéraires, Paris, Armand Colin, coll. « Cursus », 3e éd., 2015.", None),
  ("Alain Vaillant, Jean-Pierre Bertrand, Philippe Régnier, Histoire de la littérature française du XIXe siècle, Paris, Nathan, 1998.", None),
  ("Max Milner, Le Romantisme I, 1820-1843 ; Claude Pichois, Le Romantisme II, 1843-1869, Paris, Arthaud, coll. Littérature française, 1973 et 1979.", None),
  ("Philippe Van Tieghem, Le Romantisme français, Paris, PUF, coll. Que sais-je ?.", None),
  ("Henri Peyre, Qu'est-ce que le romantisme ?, Paris, PUF, 1979.", None),
  ("Daniel Bergez, L'Explication de texte littéraire (référence de la fiche pour le commentaire).", None)]),
("Sociocritique et sociologie de la littérature", [
  ("Claude Duchet, « Pour une socio-critique ou variations sur un incipit », Littérature, n° 1, 1971 ; Claude Duchet (dir.), Sociocritique, Paris, Nathan, 1979.", None),
  ("Edmond Cros, Théorie et pratique sociocritiques, Paris, Éditions sociales, 1983.", None),
  ("Pierre V. Zima, Manuel de sociocritique, Paris, Picard, 1985 ; rééd. L'Harmattan, 2000.", None),
  ("Pierre Bourdieu, « Le champ littéraire », Actes de la recherche en sciences sociales, n° 89, 1991 ; Les Règles de l'art, Paris, Seuil, 1992.", None),
  ("Gisèle Sapiro, La Sociologie de la littérature, Paris, La Découverte, coll. Repères, 2014.", None),
  ("Paul Bénichou, Le Sacre de l'écrivain, Paris, José Corti, 1973.", None),
  ("Christophe Charle, Naissance des « intellectuels », 1880-1900, Paris, Minuit, 1990.", None),
  ("Pascale Casanova, La République mondiale des lettres, Paris, Seuil, 1999.", None),
  ("Edward W. Said, L'Orientalisme. L'Orient créé par l'Occident, Paris, Seuil, 1980 (éd. originale 1978).", None),
  ("Gökhan Dinar, thèse de doctorat, Université Pamukkale, 2025 : lecture sociocritique (Duchet, Cros, Zima, Bourdieu) de la trilogie de Leïla Slimani ; modèle de lecture à quatre niveaux (contextuel, socio-idéologique, socio-historique, socio-identitaire) repris dans ce cours.", None)]),
("Genres : nouvelle, fantastique, drame, poème en prose", [
  ("Daniel Grojnowski, Lire la nouvelle, Paris, Dunod, 1993.", None),
  ("Jean-Marie Schaeffer, Qu'est-ce qu'un genre littéraire ?, Paris, Seuil, 1989.", None),
  ("Tzvetan Todorov, Introduction à la littérature fantastique, Paris, Seuil, 1970.", None),
  ("Anne Ubersfeld, Le Drame romantique, Paris, Belin, 1993 ; Michel Lioure, Le Drame, Paris, Armand Colin, 1963.", None)]),
("Presse, marché, tribunaux", [
  ("Marie-Ève Thérenty et Alain Vaillant, 1836. L'An I de l'ère médiatique, Paris, Nouveau Monde, 2001.", None),
  ("Dominique Kalifa, Philippe Régnier, Marie-Ève Thérenty, Alain Vaillant (dir.), La Civilisation du journal, Paris, Nouveau Monde, 2011.", None),
  ("Gisèle Sapiro, La Responsabilité de l'écrivain, Paris, Seuil, 2011.", None),
  ("Jules Huret, Enquête sur l'évolution littéraire, 1891.", None)]),
("Critique d'époque (sources primaires)", [
  ("Sainte-Beuve, « De la littérature industrielle », 1839 ; Goncourt, préface de Germinie Lacerteux, 1865 ; Zola, Le Roman expérimental, 1880 ; Maupassant, « Le Roman », 1888 ; Verlaine, Les Poètes maudits, 1884 ; Moréas, « Le Symbolisme », 1886 ; Gourmont, Le Livre des masques, 1896.", None),
  ("Jacques Bainville, Au seuil du siècle. Études critiques, Paris, Éditions du Capitole, 1927 : un critique de droite, antidreyfusard, juge la littérature de 1900 à 1913. Document à lire avec distance (préjugés de classe et racisme explicites dans l'article sur Zola).", None)]),
("Ponts italiens", [
  ("Germaine de Staël, « Sulla maniera e la utilità delle traduzioni », Biblioteca italiana, janvier 1816 ; Giovanni Berchet, Lettera semiseria, 1816 ; Alessandro Manzoni, Lettre à M. Chauvet, 1823.", None),
  ("Giovanni Verga, Vita dei campi (1880), I Malavoglia (1881) ; Luigi Capuana ; Nino Martoglio, poète et homme de théâtre en sicilien (Belpasso, près de Catania).", None),
  ("Filippo Tommaso Marinetti, Manifeste du futurisme, Le Figaro, 1909 ; Luigi Pirandello, Sei personaggi in cerca d'autore, 1921.", None)]),
("IA et éducation", [
  ("UNESCO, Orientations pour l'IA générative dans l'éducation et la recherche, 2023.", None),
  ("Charte IA du cours (page d'accueil) : déclarer, vérifier, écrire soi-même, rester critique.", "index.html")]),
("Ressources en ligne", [
  ("Gallica (BnF) : éditions originales, journaux du XIXe siècle.", "https://gallica.bnf.fr"),
  ("Wikisource : textes du domaine public, dont tous les textes du XIXe siècle du programme.", "https://fr.wikisource.org"),
  ("RetroNews (BnF) : la presse ancienne, utile pour les feuilletons et les procès.", "https://www.retronews.fr"),
  ("Cairn : articles et chapitres d'ouvrages critiques (accès par l'université).", "https://shs.cairn.info"),
  ("Persée : revues savantes en accès libre (Littérature, Romantisme).", "https://www.persee.fr"),
  ("Fabula : actualité de la recherche en littérature.", "https://www.fabula.org")]),
]
