W = []

# ---------------------------------------------------------------- S5
W.append(dict(
n=5, dates="9–13 nov.", dates_long="9–13 novembre 2026",
title="L'âge d'or de la nouvelle", period="1870–1887",
sub="Zola, Maupassant, Daudet, Barbey d'Aurevilly · atelier de commentaire",
recit="Médan, Diaboliques, Daudet, Le Horla",
hand="Pendant plusieurs jours de suite…",
objectifs=[
 "Je présente le naturalisme et le groupe de Médan.",
 "Je lis un recueil de nouvelles comme un ensemble : Médan, Les Diaboliques.",
 "Je compare deux nouvelles de la partie B : Maupassant, Daudet, Barbey.",
 "Je rédige une introduction de commentaire complète.",
],
prog=[("Partie B","Les Soirées de Médan (1880) : Boule de suif"),
      ("Partie B","Barbey d'Aurevilly, Les Diaboliques (1874) : Le Rideau cramoisi"),
      ("Partie B","Daudet, La Dernière Classe ; Maupassant, Le Horla"),
      ("A.2","Zola, Germinal, incipit")],
seances=[("Le groupe de Médan","Troisième République, presse de masse, Zola et ses disciples ; lire un recueil."),
         ("Atelier de commentaire","2 heures, sans note : rédiger une introduction, avec retour écrit."),
         ("Nouvelles et labo IA","Le Horla, Le Rideau cramoisi, La Dernière Classe ; l'IA relit votre introduction.")],
enigme=("Comment raconter la défaite de 1870 en quelques pages ?",
        "1880 : six écrivains, une maison à Médan, six nouvelles sur la guerre.",
        "Pendant plusieurs jours de suite…"),
frise=[("1870","Défaite face à la Prusse ; la Commune en 1871",1),
       ("1872","Daudet, La Dernière Classe",0),
       ("1874","Barbey d'Aurevilly, Les Diaboliques, aussitôt saisies",0),
       ("1880","Les Soirées de Médan, avec Boule de suif",0),
       ("1885","Zola, Germinal",0),
       ("1887","Maupassant, Le Horla",0)],
frise_titre="La nouvelle à son sommet",
auteurs=[("Zola","1840–1902","Le chef de file : science, enquête, puis engagement (J'accuse… !, 1898)."),
         ("Maupassant","1850–1893","Disciple de Flaubert : plus de 300 nouvelles, nées dans la presse."),
         ("Daudet","1840–1897","Le conteur du Midi et de la guerre : émotion et ironie."),
         ("Barbey d'Aurevilly","1808–1889","Le dandy catholique : passions et crimes racontés à voix basse.")],
outil=("Le recueil","Lire un ensemble, pas seulement une nouvelle",
       [("Cadre","Qui réunit les récits : un lieu, des soirées, un narrateur ?"),("Échos","Quels thèmes reviennent d'une nouvelle à l'autre ?"),("Position","Un recueil collectif est aussi un manifeste de groupe.")],
       "Les Soirées de Médan : six auteurs, un même sujet, la guerre, et une même école, le naturalisme."),
textes=[
 dict(title="Maupassant, Boule de suif", quotes=[(["Pendant plusieurs jours de suite des lambeaux d'armée en déroute avaient traversé la ville."],
      "Maupassant, Boule de suif, Les Soirées de Médan (1880), première phrase")],
      questions=[("Image","Lambeaux d'armée : quelle image de la défaite ?"),("Temps","Plus-que-parfait : pourquoi commencer après les faits ?"),("Recueil","Que partagent les six nouvelles de Médan ?")]),
 dict(title="Barbey d'Aurevilly, Le Rideau cramoisi", quotes=[(["Il y a terriblement d'années, je m'en allais chasser le gibier d'eau dans les marais de l'Ouest…"],
      "Barbey d'Aurevilly, Le Rideau cramoisi, Les Diaboliques (1874), première phrase")],
      questions=[("Voix","Qui raconte ? À qui ?"),("Adverbe","Terriblement d'années : quel effet ?"),("Cadre","Une histoire racontée de nuit, en voiture : pourquoi ?")]),
],
methode=(5,"Rédiger l'introduction",
  ["Amorce : situer l'auteur, l'œuvre, le mouvement.","Présenter le passage et poser la problématique.","Annoncer le plan en une phrase claire."],
  "Atelier de 2 h sur Boule de suif ou Le Horla : une introduction rédigée, sans note, avec retour écrit."),
nouvelle=dict(label="Fil rouge · la nouvelle", title="Maupassant, Le Horla (1887) · Daudet, La Dernière Classe (1872)",
  quote=(["8 mai. — Quelle journée admirable !"],"Le Horla, première entrée du journal"),
  points=[("Journal","Le Horla : un journal intime, un seul témoin, aucun contrôle."),
          ("Fantastique","Folie ou présence ? Le doute n'est jamais levé."),
          ("Daudet","La Dernière Classe : la langue française et la perte de l'Alsace.")],
  bas="Partie B de la fiche : Maupassant, Daudet, Barbey d'Aurevilly et le recueil de Médan."),
labo=dict(title="Votre introduction, deux relectures",
  steps=[("Demander","Déposer votre introduction dans l'Atelier commentaire."),
         ("Vérifier","Comparer le retour IA et le retour de l'enseignant : où sont-ils d'accord ?"),
         ("Améliorer","Réécrire l'introduction en gardant ce qui est juste.")],
  produit="Introduction réécrite (version 2), déposée sur Studium."),
italia=[("1880","Verga, né à Catania, publie Vita dei campi, l'année des Soirées de Médan."),
        ("1881","I Malavoglia : une famille d'Aci Trezza, racontée sans narrateur savant."),
        ("Capuana","Né à Mineo, théoricien du verismo et lecteur de Zola. Visite possible : Casa Verga.")],
avant=["Lire Rimbaud, Le Bateau ivre, strophes 1 à 5.","Lire Moréas, Le Symbolisme (extraits) et Villiers, Véra."],
production="Introduction de commentaire, version 2.",
anthologie=["Zola, Germinal, incipit","Zola, J'accuse… ! (extrait)","Goncourt, préface de Germinie Lacerteux"],
notes=[
 "Semaine centrale pour la partie B de la fiche : quatre auteurs de la liste et les deux recueils. Premier atelier de commentaire.",
 "L'objectif 2 est nouveau : lire un recueil. La fiche demande les deux recueils en intégralité, les étudiants doivent comprendre leur logique d'ensemble.",
 "Séance A : énigme, frise, outil (60 min), auteurs et Boule de suif (60 min). Séance B : atelier. Séance C : Barbey, Le Horla, Daudet, labo.",
 "Les six nouvelles de Médan parlent de la guerre de 1870 sans héroïsme. Demander : pourquoi une défaite intéresse-t-elle des écrivains ?",
 "Les Diaboliques sont saisies en 1874 pour outrage aux mœurs : lien avec la semaine 4.",
 "Zola dirige une école ; Maupassant est le disciple de Flaubert ; Daudet et Barbey sont hors de l'école : montrer la diversité de la nouvelle.",
 "L'outil recueil prépare la lecture intégrale demandée par la fiche. Faire remplir un tableau : cadre, échos, position.",
 "Séance A, 30 min. Le plus-que-parfait installe le lecteur après la défaite. Boule de suif est la nouvelle qui révèle Maupassant.",
 "Séance C, 30 min. Le cadre de Barbey est un récit dans le récit : le vicomte de Brassard raconte, de nuit, dans une diligence arrêtée devant une fenêtre au rideau cramoisi.",
 "Séance B, 2 h. Atelier non noté. Limiter à l'introduction et une partie si le groupe est nombreux. Corriger avec la grille à cinq critères pour habituer les étudiants.",
 "Séance C, 30 min. Le Horla existe en deux versions (1886 et 1887) : on lit la seconde, en journal intime. La Dernière Classe se lit en 10 minutes à voix haute.",
 "Séance C, 30 min. Comparer les deux retours : l'IA est souvent trop générale ou trop gentille. Valoriser les écarts repérés.",
 "Pont fort : Verga est catanais. Proposer une visite de la Casa Verga hors cours.",
 "Semaine lourde en correction : prévoir le retour écrit pour la semaine 6.",
],
carnet=dict(objectif="relier naturalisme, presse et recueil ; lire quatre auteurs de la partie B ; premier atelier de commentaire.",
  A="Énigme et frise (25 min) ; outil : le recueil (35 min) ; auteurs (30 min) ; Boule de suif, incipit (30 min).",
  B="Atelier de commentaire non noté (2 h) : méthode étape 5, rédaction de l'introduction sur Boule de suif ou Le Horla.",
  C="Le Rideau cramoisi (30 min) ; Le Horla et La Dernière Classe (40 min) ; labo IA retour sur l'introduction (30 min) ; pont italien (20 min).",
  anticiper="Semaine lourde en correction. Mettre les deux recueils sur Studium (textes du domaine public)."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine cinq : L'âge d'or de la nouvelle.",
 "Après la défaite de mille huit cent soixante-dix, la Troisième République développe l'école et la presse. Les journaux publient des nouvelles chaque jour.",
 "En mille huit cent quatre-vingts, six écrivains réunis autour de Zola publient Les Soirées de Médan : six nouvelles sur la guerre. La plus célèbre est Boule de suif, de Maupassant.",
 "Nous lisons aussi Les Diaboliques de Barbey d'Aurevilly, des histoires de passion racontées à voix basse, et La Dernière Classe de Daudet, sur la perte de l'Alsace et de la langue française.",
 "Notre outil est le recueil. Un recueil n'est pas une simple collection : il a un cadre, des échos entre les récits, et parfois un programme de groupe.",
 "Deux lectures critiques nous accompagnent. Yves Stalloni raconte l'école naturaliste en trois temps : la formation, l'âge d'or, puis l'éclatement. Et Jacques Bainville, un jeune critique de droite, juge Zola en mille neuf cent deux, au cœur de l'affaire Dreyfus. Nous lisons son texte comme une prise de position, avec distance.",
 "Le Horla, de Maupassant, est un journal intime. Le narrateur sent une présence invisible. Folie ou réalité ? Le doute reste.",
 "En séance B, nous faisons notre premier atelier de commentaire, sans note : vous rédigez une introduction. Amorce, présentation, problématique, annonce du plan.",
 "Au labo, l'IA relit votre introduction, l'enseignant aussi. Vous comparez les deux retours.",
 "Côté italien, Verga, né à Catania, publie Vita dei campi la même année que Médan.",
],
))

# ---------------------------------------------------------------- S6
W.append(dict(
n=6, dates="16–20 nov.", dates_long="16–20 novembre 2026",
title="La poésie en crise", period="1871–1886",
sub="Rimbaud, Verlaine, Mallarmé, Moréas · nouvelle : Villiers de l'Isle-Adam, Véra",
recit="Villiers, Véra",
hand="Je est un autre.",
objectifs=[
 "Je lis le début du Bateau ivre (liste A.1) et j'analyse qui dit je.",
 "J'explique ce qu'est un manifeste littéraire : Moréas (liste A.1).",
 "Je rédige un paragraphe d'analyse sans paraphraser.",
 "Je compare trois traductions italiennes d'une strophe.",
],
prog=[("A.1 · paire 2","Rimbaud, Le Bateau ivre (1871)"),
      ("A.1 · paire 4","Moréas, Le Symbolisme (1886)"),
      ("Partie B","Villiers de l'Isle-Adam, Véra (Contes cruels, 1883)"),
      ("A.2","Verlaine, Art poétique ; Rimbaud, Voyelles")],
seances=[("Voyants et symbolistes","Lettre du Voyant, poètes maudits, petites revues, Moréas ; Zima : le sociolecte."),
         ("Atelier du texte","Le Bateau ivre et Le Symbolisme : le paragraphe d'analyse."),
         ("Nouvelle et labo IA","Véra ; trois traductions du Bateau ivre ; manifeste express.")],
enigme=("Pourquoi des poètes choisissent-ils d'être difficiles ?",
        "1871–1886 : vers libérés, revues minuscules, lecteurs rares.",
        "De la musique avant toute chose"),
frise=[("1871","15 mai, lettre du Voyant ; Le Bateau ivre",0),
       ("1874","Verlaine écrit Art poétique (publié en 1882)",0),
       ("1883","Villiers, Contes cruels ; Verlaine, Les Poètes maudits",0),
       ("1884","Huysmans, À rebours",0),
       ("1886","18 septembre : Moréas, Le Symbolisme, dans Le Figaro",1),
       ("1886","Rimbaud, Illuminations",0)],
frise_titre="Quinze ans pour changer la poésie",
auteurs=[("Rimbaud","1854–1891","Poète à seize ans, voyant, puis silence et départ pour l'Afrique."),
         ("Verlaine","1844–1896","La musique du vers ; il nomme les poètes maudits."),
         ("Mallarmé","1842–1898","L'obscurité comme exigence ; ses mardis rue de Rome."),
         ("Moréas","1856–1910","Né à Athènes, il donne son nom au symbolisme.")],
outil=("Le sociolecte","Pierre Zima",
       [("Sociolecte","La langue d'un groupe : ses mots, ses tours, ses valeurs."),("Refus","Les symbolistes refusent la langue commune et la langue des journaux."),("Position","Être difficile devient une manière de se distinguer.")],
       "Le Bateau ivre invente sa propre langue : c'est déjà une prise de position."),
textes=[
 dict(title="Rimbaud, Le Bateau ivre", quotes=[(["Comme je descendais des Fleuves impassibles,","Je ne me sentis plus guidé par les haleurs :"],
      "Rimbaud, Le Bateau ivre (1871), vers 1 et 2")],
      questions=[("Je","Qui dit je : un homme, un bateau ?"),("Majuscule","Pourquoi Fleuves avec une majuscule ?"),("Liberté","Que perd le bateau ? Que gagne-t-il ?")]),
 dict(title="Moréas, le manifeste", quotes=[(["Ennemie de l'enseignement, la déclamation, la fausse sensibilité, la description objective, la poésie symbolique cherche à vêtir l'Idée d'une forme sensible…"],
      "Moréas, Le Symbolisme, Le Figaro, 18 septembre 1886")],
      questions=[("Ennemis","Contre quoi le manifeste se dresse-t-il ?"),("Programme","Que veut dire vêtir l'Idée ?"),("Genre","Quelles sont les marques d'un manifeste ?")]),
],
methode=(6,"Le paragraphe d'analyse",
  ["Une idée en tête de paragraphe.","Une citation courte, intégrée à la phrase.","Analyser l'effet : procédé et sens, sans raconter."],
  "Réécrire un paragraphe qui paraphrase en paragraphe qui analyse."),
nouvelle=dict(label="Fil rouge · la nouvelle", title="Villiers de l'Isle-Adam, Véra (Contes cruels, 1883)",
  quote=(["L'amour est plus fort que la Mort, a dit Salomon : oui, son mystérieux pouvoir est illimité."],"première phrase"),
  points=[("Deuil","Un comte refuse la mort de sa femme et vit comme si elle était là."),
          ("Fantastique","La volonté peut-elle ressusciter ?"),
          ("Conte cruel","Un récit court, une fin qui frappe.")],
  bas="Partie B de la fiche : Villiers ferme notre liste de nouvelles."),
labo=dict(title="Le Bateau ivre en trois langues de bord",
  steps=[("Demander","Faire traduire une strophe par l'IA."),
         ("Vérifier","Comparer avec une traduction publiée et la vôtre : sens, rythme, images."),
         ("Améliorer","Composer la meilleure version du groupe et la justifier.")],
  produit="Une strophe traduite et commentée."),
italia=[("Pascoli","Il fanciullino (1897) : le poète enfant, une autre poétique du symbole."),
        ("D'Annunzio","Il piacere (1889) : la décadence à l'italienne."),
        ("Jeu","Manifeste express d'un isme inventé, en cinq phrases.")],
avant=["Lire Jarry, Ubu Roi, acte I, scène 1, et Wilde, Salomé, la première page.","Lire Gide, Les Nourritures terrestres, Livre I (extraits)."],
production="Un paragraphe d'analyse sur Le Bateau ivre.",
anthologie=["Verlaine, Art poétique","Rimbaud, Voyelles","Mallarmé, Brise marine"],
notes=[
 "Deux textes A.1 cette semaine : Le Bateau ivre (paire 2, face à Cendrars en semaine 8) et Le Symbolisme de Moréas (paire 4, face à Marinetti en semaine 8).",
 "Mallarmé peut décourager : rester sur un vers ou deux, jamais un poème entier.",
 "Séance A : énigme, frise, auteurs (60 min), outil et Moréas (60 min). Séance B : Rimbaud et le paragraphe. Séance C : Véra, labo, jeu.",
 "Réponses attendues : refuser le public bourgeois, la presse, la langue de tous. Être difficile, c'est choisir ses lecteurs.",
 "Art poétique est écrit en 1874, publié en 1882 dans Paris-Moderne, puis dans Jadis et naguère (1884).",
 "Le symbolisme est largement fait par des étrangers et des francophones : Moréas d'Athènes, Maeterlinck de Gand.",
 "Une définition, un exemple. Le mot sociolecte suffit, sans entrer dans la théorie.",
 "Séance B, 40 min. Le je est le bateau : la métaphore est filée sur tout le poème. Faire relire les cinq premières strophes à voix haute.",
 "Séance A, 30 min. Faire relever les marques du manifeste : ennemis désignés, ton affirmatif, programme. On les retrouvera chez Marinetti en semaine 8.",
 "Méthode, étape 6 (40 min). Distribuer un paragraphe qui paraphrase et le faire réécrire en groupes.",
 "Séance C, 25 min. Véra se lit en une demi-heure. Lien avec La Morte amoureuse (semaine 3) : deux amours plus forts que la mort.",
 "Séance C, 35 min. Comparer trois versions d'une strophe. Faire vérifier aussi les dates biographiques de Rimbaud données par l'IA.",
 "Jeu (20 min) : manifeste express. Bon exercice d'écriture B1-B2, à relire avec les marques du manifeste.",
 "Annoncer la semaine 7 : théâtre. Distribuer les rôles d'Ubu et de Salomé pour une lecture jouée.",
],
carnet=dict(objectif="comprendre comment la poésie rompt avec la langue commune et lire deux textes A.1.",
  A="Énigme et frise (25 min) ; auteurs (35 min) ; outil : le sociolecte (30 min) ; Moréas, Le Symbolisme (30 min).",
  B="Le Bateau ivre, strophes 1 à 5 (40 min) ; Art poétique pour l'anthologie (30 min) ; méthode étape 6 (50 min).",
  C="Véra (25 min) ; labo IA traductions (35 min) ; jeu manifeste express (20 min) ; pont italien et devoirs (20 min) ; distribution des rôles pour la semaine 7 (20 min).",
  anticiper="Préparer trois traductions italiennes d'une strophe du Bateau ivre."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine six : La poésie en crise.",
 "Entre mille huit cent soixante et onze et mille huit cent quatre-vingt-six, la poésie change de langue. Rimbaud, à seize ans, écrit que le poète doit se faire voyant, et que je est un autre.",
 "Le texte du programme est Le Bateau ivre. Le je du poème est un bateau qui perd ses guides et part vers la liberté.",
 "Verlaine cherche la musique du vers. Mallarmé fait de la difficulté une exigence. Et en mille huit cent quatre-vingt-six, Jean Moréas publie dans Le Figaro le manifeste du symbolisme : la poésie doit vêtir l'Idée d'une forme sensible.",
 "Notre outil vient de Pierre Zima : le sociolecte, la langue d'un groupe. En refusant la langue commune, les poètes prennent position.",
 "Le manuel de Stalloni décrit le passage de la Décadence au symbolisme. Mallarmé y résume la nouvelle poésie : nommer un objet, c'est supprimer les trois quarts de la jouissance du poème. Attention : le manuel date le manifeste de mille huit cent soixante-six ; la bonne date est mille huit cent quatre-vingt-six.",
 "En méthode, nous écrivons un paragraphe d'analyse : une idée, une citation courte, l'analyse d'un effet, sans raconter.",
 "La nouvelle de la semaine est Véra, de Villiers de l'Isle-Adam. Un comte refuse la mort de sa femme. L'amour peut-il vaincre la mort ?",
 "Au labo, nous comparons trois traductions italiennes d'une strophe du Bateau ivre : publiée, par l'IA, et la vôtre.",
 "Pour la semaine prochaine, lisez le début d'Ubu Roi et de Salomé.",
],
))

# ---------------------------------------------------------------- S7
W.append(dict(
n=7, dates="23–27 nov.", dates_long="23–27 novembre 2026",
title="Fin de siècle : la scène et la ferveur", period="1891–1901",
sub="Wilde, Jarry, Gide, René Vivien · théâtre et prose poétique",
recit="Lecture jouée : Ubu Roi, Salomé",
hand="Merdre.",
objectifs=[
 "Je compare deux pièces de la liste A.1 jouées au même théâtre en 1896.",
 "Je reconnais la prose poétique de Gide (liste A.1).",
 "Je situe René Vivien, voix de femme dans la poésie de 1900 (liste A.1).",
 "Je rédige une conclusion qui ouvre vraiment.",
],
prog=[("A.1 · paire 5","Wilde, Salomé (1893) · Jarry, Ubu Roi (1896)"),
      ("A.1 · paire 3","Gide, Les Nourritures terrestres (1897)"),
      ("A.1 · paire 1","René Vivien, Études et préludes (1901)"),
      ("A.2","Mallarmé, Crise de vers ; Maeterlinck, Pelléas et Mélisande")],
seances=[("Le Théâtre de l'Œuvre","Symbolisme sur scène, scandale d'Ubu, Salomé interdite à Londres ; René Vivien."),
         ("Atelier du texte","Gide et Vivien : une prose et un vers de 1900 ; la conclusion."),
         ("Scène et labo IA","Lecture jouée d'Ubu et de Salomé ; l'IA installe Ubu à Catania.")],
enigme=("Comment un même théâtre peut-il jouer un drame sacré et une farce ?",
        "Paris, 1896, Théâtre de l'Œuvre : Salomé en février, Ubu Roi en décembre.",
        "Merdre."),
frise=[("1891","Wilde écrit Salomé en français",0),
       ("1892","Salomé interdite à Londres",1),
       ("1893","Salomé publiée à Paris",0),
       ("1896","Théâtre de l'Œuvre : Salomé en février, Ubu Roi le 10 décembre",1),
       ("1897","Gide, Les Nourritures terrestres ; Mallarmé, Un coup de dés",0),
       ("1901","René Vivien, Études et préludes",0)],
frise_titre="Dix ans de scandales et de ferveur",
auteurs=[("Oscar Wilde","1854–1900","Irlandais, il écrit Salomé en français : un drame symboliste."),
         ("Alfred Jarry","1873–1907","Ubu : un roi grotesque, une farce qui fait scandale."),
         ("André Gide","1869–1951","Les Nourritures : la ferveur, le désir, la liberté du regard."),
         ("René Vivien","1877–1909","Poétesse née à Londres, elle écrit en français ; Sappho est son modèle.")],
outil=("Scandale et consécration","Comment on entre dans l'histoire",
       [("Scandale","Le public siffle, la censure interdit : on parle de l'œuvre."),("Petite scène","Le Théâtre de l'Œuvre joue pour un public choisi."),("Consécration","Les deux pièces sifflées ou interdites sont aujourd'hui au programme.")],
       "Même question qu'en 1830 et 1857 : qui a le pouvoir de dire ce qu'est la bonne littérature ?"),
textes=[
 dict(title="Deux premières répliques", quotes=[
      (["Comme la princesse Salomé est belle ce soir !"],"Wilde, Salomé (1893), première réplique, le jeune Syrien"),
      (["PÈRE UBU. — Merdre.","MÈRE UBU. — Oh ! voilà du joli, Père Ubu, vous estes un fort grand voyou."],"Jarry, Ubu Roi (1896), acte I, scène 1")],
      questions=[("Ouverture","Une première réplique : que promet chaque pièce ?"),("Langue","Langue biblique, mot inventé, orthographe ancienne : quels effets ?"),("Scandale","Pourquoi l'une est-elle interdite, l'autre sifflée ?")]),
 dict(title="Gide, la ferveur", quotes=[(["Nathanaël, je t'enseignerai la ferveur.","Que l'importance soit dans ton regard, non dans la chose regardée."],
      "Gide, Les Nourritures terrestres (1897), Livre I")],
      questions=[("Destinataire","Qui est Nathanaël ? Pourquoi le tutoiement ?"),("Prose","Vers ou prose ? Où est le rythme ?"),("Vivien","Comparer avec un sonnet de René Vivien (Studium) : deux libertés de 1900.")]),
],
methode=(7,"Conclure et ouvrir",
  ["Répondre clairement à la problématique.","Rappeler le chemin, une phrase par partie.","Ouvrir sur une œuvre précise, pas sur une généralité."],
  "Trois ouvertures pour un même commentaire ; garder la meilleure."),
nouvelle=dict(label="Atelier de scène", title="Lire le théâtre à voix haute", quote=None,
  points=[("Ubu","Distribuer Père Ubu et Mère Ubu : lire fort, jouer l'excès."),
          ("Salomé","Lire le début à trois voix : répétitions, couleurs, lune."),
          ("Recueils","Retour sur la partie B : comment présenter Les Diaboliques ou Médan à l'oral ?")],
  bas="Paire 5 de la liste A.1 : choisir Salomé ou Ubu Roi pour sa lecture intégrale."),
labo=dict(title="Ubu à Catania",
  steps=[("Demander","Faire réécrire par l'IA la scène 1 d'Ubu à Catania aujourd'hui."),
         ("Vérifier","Qu'a gardé l'IA de Jarry : langue, excès, critique du pouvoir ? Qu'a-t-elle perdu ?"),
         ("Améliorer","Réécrire vous-mêmes trois répliques, plus justes.")],
  produit="Une scène courte et sa note de vérification."),
italia=[("D'Annunzio","Il écrit en français Le Martyre de saint Sébastien (1911), mis en musique par Debussy."),
        ("Salomé","La Salomé de Richard Strauss (1905), d'après Wilde, fait le tour des opéras d'Europe."),
        ("À faire","Traduire en italien trois mots d'Ubu : merdre, phynance, oneille.")],
avant=["Lire Marinetti, Manifeste du futurisme (extraits).","Choisir votre roman bref et lire le premier chapitre : Le Grand Meaulnes ou Les Caves du Vatican."],
production="Une conclusion avec ouverture.",
anthologie=["Mallarmé, Crise de vers (extrait)","Maeterlinck, Pelléas et Mélisande, une scène","Verhaeren, Les Villes tentaculaires (extrait)"],
notes=[
 "Semaine allégée en nouvelles, riche en liste A.1 : trois paires de la fiche sont abordées (théâtre, poèmes en prose, recueil de poèmes).",
 "Présenter René Vivien simplement : poétesse de la Belle Époque, modèle de Sappho, amours féminines. La fiche indique 1902 pour Études et préludes ; l'édition originale chez Lemerre est généralement datée de 1901 : vérifier dans l'édition.",
 "Séance A : énigme, frise, outil (60 min), auteurs et Vivien (60 min). Séance B : Gide et la conclusion. Séance C : scène et labo.",
 "Le même théâtre, la même année, la même mise en scène de Lugné-Poe : Salomé en février 1896, pendant que Wilde est en prison, puis Ubu Roi le 10 décembre.",
 "Salomé est interdite à Londres en 1892 pendant les répétitions avec Sarah Bernhardt : une pièce biblique ne pouvait pas être jouée.",
 "Wilde et Vivien sont deux étrangers qui choisissent le français. Gide et Jarry ont quatre ans d'écart et presque le même âge que leurs lecteurs.",
 "Fil rouge du semestre : la question de la semaine 1 revient. Faire comparer trois scandales : 1830, 1857, 1896.",
 "Séance A ou C, 30 min. Lire les deux répliques à voix haute, très différemment. Les étudiants choisiront une des deux pièces pour la lecture intégrale.",
 "Séance B, 40 min. Nathanaël est un disciple imaginaire. Faire repérer l'impératif et le futur : une prose qui enseigne. Lire ensuite un sonnet de Vivien (Studium).",
 "Méthode, étape 7 (40 min). Trois ouvertures possibles ; écarter les généralités du type de tout temps.",
 "Séance C, 40 min. Lecture jouée en petits groupes. Ne pas chercher la perfection : l'excès d'Ubu doit s'entendre.",
 "Séance C, 30 min. L'IA tend à rendre Ubu gentil ou moralisateur : excellent point de départ pour parler de la violence comique de Jarry.",
 "Pont italien : D'Annunzio est un autre étranger qui écrit en français, comme Wilde et Vivien.",
 "Annoncer la dernière semaine : choisir son roman bref (paire 6) et préparer l'atelier final de commentaire.",
],
carnet=dict(objectif="aborder trois paires de la liste A.1 (théâtre, poèmes en prose, recueil de poèmes) et apprendre à conclure.",
  A="Énigme et frise (25 min) ; outil : scandale et consécration (25 min) ; auteurs (30 min) ; René Vivien, lecture de deux sonnets (40 min).",
  B="Gide, Les Nourritures terrestres (40 min) ; comparaison avec Vivien (30 min) ; méthode étape 7 (50 min).",
  C="Lecture jouée d'Ubu et de Salomé (40 min) ; labo IA Ubu à Catania (30 min) ; pont italien (20 min) ; préparation de la semaine 8 (30 min).",
  anticiper="Choisir deux sonnets de Vivien et la première page de Salomé pour Studium. Répartir les rôles en semaine 6."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine sept : Fin de siècle, la scène et la ferveur.",
 "En mille huit cent quatre-vingt-seize, un petit théâtre parisien, le Théâtre de l'Œuvre, joue deux pièces très différentes. En février, Salomé, d'Oscar Wilde, un drame symboliste écrit en français et interdit à Londres. En décembre, Ubu Roi, d'Alfred Jarry, une farce qui commence par un mot inventé : merdre.",
 "Ces deux pièces forment une paire de la liste du programme. Vous en choisirez une pour la lecture intégrale.",
 "Nous lisons aussi Les Nourritures terrestres, d'André Gide, une prose poétique qui enseigne la ferveur : que l'importance soit dans ton regard, non dans la chose regardée.",
 "Et nous découvrons René Vivien, poétesse née à Londres, qui écrit en français et prend Sappho pour modèle.",
 "Notre outil est le couple scandale et consécration : les œuvres sifflées ou interdites hier sont aujourd'hui au programme.",
 "Le critique Jacques Bainville nous montre ce que deviennent les jeunes poètes de mille huit cent quatre-vingt-neuf : des livres tirés à cinquante exemplaires, puis la Bourse, la presse ou la politique.",
 "En méthode, nous apprenons à conclure et à ouvrir sur une œuvre précise.",
 "Au labo, l'IA installe Ubu à Catania aujourd'hui. Qu'a-t-elle gardé de Jarry ? Qu'a-t-elle perdu ?",
 "Pour la semaine prochaine, lisez le Manifeste du futurisme et choisissez votre roman bref.",
],
))

# ---------------------------------------------------------------- S8
W.append(dict(
n=8, dates="30 nov.–5 déc.", dates_long="30 novembre–5 décembre 2026",
title="Vitesse, guerre et Années folles", period="1909–1929",
sub="Marinetti, Cendrars, Alain-Fournier, Gide · bilan du semestre",
recit="Bilan : la nouvelle de René à Morand",
hand="la beauté de la vitesse",
objectifs=[
 "J'explique comment les avant-gardes cherchent à faire date : Marinetti, Cendrars.",
 "Je présente un roman bref de la liste A.1 : Le Grand Meaulnes ou Les Caves du Vatican.",
 "Je discute l'expression Années folles avec deux historiens.",
 "Je rédige un commentaire complet et je fais le bilan de mon usage de l'IA.",
],
prog=[("A.1 · paire 4","Marinetti, Manifeste du futurisme (1909)"),
      ("A.1 · paire 2","Cendrars, Prose du Transsibérien (1913)"),
      ("A.1 · paire 6","Alain-Fournier, Le Grand Meaulnes (1913) · Gide, Les Caves du Vatican (1914)"),
      ("A.2","Apollinaire, Zone ; Valéry, La Crise de l'esprit")],
seances=[("Avant-gardes et guerre","Futurisme, l'année 1913, la Grande Guerre ; les deux romans brefs de la liste."),
         ("Atelier final","Un commentaire complet, 2 heures, sans note, avec retour écrit."),
         ("Années folles et bilan","Dada, surréalisme, Maran ; l'envers de la fête ; bilan IA du semestre.")],
enigme=("Les Années folles ont-elles vraiment été folles ?",
        "Après 1,4 million de soldats français morts, Paris danse : fête, deuil, ou les deux ?",
        "la fête suit le deuil…"),
frise=[("1909","20 février : Marinetti, Manifeste du futurisme, dans Le Figaro",1),
       ("1913","Cendrars, Prose du Transsibérien ; Alain-Fournier, Le Grand Meaulnes ; Apollinaire, Alcools",0),
       ("1914","Gide, Les Caves du Vatican ; en août, la guerre",1),
       ("1919","Valéry, La Crise de l'esprit ; la revue Littérature",0),
       ("1921","René Maran, Batouala, prix Goncourt",0),
       ("1924","Breton, Manifeste du surréalisme",0)],
frise_titre="Vingt ans à toute vitesse",
auteurs=[("Marinetti","1876–1944","Né à Alexandrie, il lance le futurisme en français, à Paris."),
         ("Cendrars","1887–1961","Suisse et voyageur : un poème-voyage peint avec Sonia Delaunay."),
         ("Alain-Fournier","1886–1914","Un seul roman, Le Grand Meaulnes ; tué en septembre 1914."),
         ("Gide","1869–1951","Les Caves du Vatican : une sotie, Rome et l'acte gratuit de Lafcadio.")],
outil=("Faire date","Avant-gardes et chrononymes",
       [("Manifeste","Une avant-garde se proclame : elle date sa naissance."),("Chrononyme","Années folles : un nom d'époque donné après coup (Myriam Juan)."),("Envers","Deuil, reconstruction, refus du vote des femmes (Jean-Yves Le Naour).")],
       "Qui nomme une époque ? Même question que pour le préromantisme, en semaine 1."),
textes=[
 dict(title="Deux vitesses", quotes=[
      (["Nous déclarons que la splendeur du monde s'est enrichie d'une beauté nouvelle : la beauté de la vitesse."],"Marinetti, Manifeste du futurisme, Le Figaro, 20 février 1909"),
      (["En ce temps-là j'étais en mon adolescence"],"Cendrars, Prose du Transsibérien (1913), premier vers")],
      questions=[("Manifeste","Comparer avec Moréas (semaine 6) : mêmes marques ?"),("Vitesse","Train, auto, poème : comment la forme accélère-t-elle ?"),("Choix","Paire 2 et paire 4 : quel texte choisirez-vous ?")]),
 dict(title="Deux romans brefs", quotes=[(["Il arriva chez nous un dimanche de novembre 189…"],
      "Alain-Fournier, Le Grand Meaulnes (1913), première phrase")],
      questions=[("Date","189… : pourquoi une date incomplète ?"),("Narrateur","Qui raconte l'arrivée de Meaulnes ?"),("Gide","Lafcadio pousse un inconnu d'un train : un acte sans motif est-il possible ?")]),
],
methode=(8,"Le commentaire complet",
  ["Introduction, deux ou trois parties, conclusion.","Chaque partie : une idée, des citations, des analyses.","Relire : langue, citations, temps des verbes."],
  "Atelier final de 2 h, avec la grille du cours et un retour écrit."),
nouvelle=dict(label="Années folles", title="Un nom d'époque à discuter", quote=None,
  points=[("Juan","Un chrononyme : une image culturelle plus large que la réalité vécue."),
          ("Le Naour","Deuil, reconstruction, refus du vote des femmes en 1922 : la fête vient tard."),
          ("Maran","Batouala (1921) : premier Goncourt d'un écrivain noir, une préface anticoloniale.")],
  bas="Fil rouge : de René (1802) à Ouvert la nuit de Morand (1922), qu'est devenu le récit bref ?"),
labo=dict(title="Bilan IA du semestre",
  steps=[("Demander","Faire préparer par l'IA une fiche sur votre roman bref de la liste A.1."),
         ("Vérifier","Contrôler dates, noms et citations : combien d'erreurs ?"),
         ("Améliorer","Corriger la fiche et noter les erreurs dans le carnet IA.")],
  produit="Une fiche A.1 vérifiée et le bilan des erreurs repérées ce semestre."),
italia=[("1909","Marinetti écrit en français : le futurisme italien naît à Paris."),
        ("Ungaretti","Soldat au front, poète en italien et en français, ami d'Apollinaire."),
        ("1923","Pitoëff met en scène Six personnages en quête d'auteur de Pirandello à Paris.")],
avant=["Compléter votre liste A.2 avec les extraits proposés chaque semaine.","Relire les six classiques choisis dans la liste A.1 et leurs fiches."],
production="Un commentaire complet et une fiche A.1 vérifiée.",
anthologie=["Apollinaire, Zone (début)","Valéry, La Crise de l'esprit (1919)","Proust, Du côté de chez Swann, première page"],
notes=[
 "Dernière semaine : trois paires A.1 en une séance (manifeste, poème long, roman bref), puis l'atelier final et le bilan. Rester au niveau des extraits : la lecture intégrale reste personnelle.",
 "Objectif 4 : le bilan IA. Garder 20 minutes en fin de séance C pour la question : quelles hallucinations avons-nous repérées ce semestre ?",
 "Séance A : énigme, frise, auteurs, deux vitesses, romans brefs. Séance B : atelier final. Séance C : Années folles, envers de la fête, labo, bilan.",
 "Chiffre à donner : environ 1,4 million de soldats français morts. Laisser les étudiants proposer : fête pour oublier, fête de quelques-uns, deuil partout.",
 "Mettre en relief 1913, année extraordinaire, puis la rupture d'août 1914. Alain-Fournier meurt en septembre 1914.",
 "Paire 6 de la fiche : Le Grand Meaulnes ou Les Caves du Vatican. Laisser chacun annoncer son choix.",
 "Deux historiens : Myriam Juan (Les Années folles, Que sais-je ?) et Jean-Yves Le Naour (1922-1929. Les années folles ?, Perrin, 2022).",
 "Séance A, 30 min. Le manifeste de Marinetti paraît à la une du Figaro, comme celui de Moréas : faire comparer les marques du genre. Cendrars n'est pas dans le domaine public : citer seulement de courts passages.",
 "Séance A, 30 min. Le narrateur du Grand Meaulnes est François Seurel. Pour Gide, raconter simplement la scène du train entre Rome et Naples.",
 "Séance B, 2 h. Atelier final non noté, retour écrit. Proposer un extrait du domaine public (Alain-Fournier ou Marinetti).",
 "Séance C, 30 min. Le Manifeste de Breton et Batouala ne sont pas dans le domaine public : citations courtes seulement. Maran ouvre vers les littératures francophones (Mabanckou, Sarr, Slimani).",
 "Séance C, 30 min. Chaque étudiant repart avec une fiche A.1 corrigée : utile pour l'oral.",
 "Pont italien : le futurisme naît à Paris, en français. Pitoëff monte Pirandello en avril 1923 à la Comédie des Champs-Élysées.",
 "Clore sur l'énigme de la semaine 1 et la question du semestre. Laisser l'Atelier du siècle ouvert après le cours.",
],
carnet=dict(objectif="aborder les trois dernières paires de la liste A.1, interroger les Années folles et faire le bilan du semestre.",
  A="Énigme et frise (20 min) ; auteurs (25 min) ; Marinetti et Cendrars (30 min) ; les deux romans brefs (30 min) ; outil : faire date (15 min).",
  B="Atelier final de commentaire non noté (2 h) : méthode étape 8.",
  C="Années folles et l'envers de la fête (35 min) ; labo IA fiche A.1 (30 min) ; pont italien (15 min) ; bilan du semestre et retour sur l'énigme de la semaine 1 (40 min).",
  anticiper="Vérifier les dates de la dernière semaine (fin le 5 décembre). Breton, Maran et Cendrars : courtes citations seulement sur Studium."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine huit : Vitesse, guerre et Années folles.",
 "En mille neuf cent neuf, Marinetti publie à la une du Figaro le Manifeste du futurisme : la splendeur du monde s'est enrichie d'une beauté nouvelle, la beauté de la vitesse.",
 "En mille neuf cent treize, Cendrars publie la Prose du Transsibérien, un poème-voyage, et Alain-Fournier Le Grand Meaulnes. En mille neuf cent quatorze, Gide publie Les Caves du Vatican. Puis c'est la guerre.",
 "Ces œuvres forment trois paires du programme : le manifeste, le poème long et le roman bref. Vous choisissez un texte dans chaque paire.",
 "Après la guerre viennent les Années folles. Mais ont-elles été si folles ? L'historienne Myriam Juan parle d'un nom d'époque, plus large que la réalité. Pour Jean-Yves Le Naour, l'optimisme ne s'installe vraiment qu'en mille neuf cent vingt-quatre ou vingt-cinq : la fête suit le deuil.",
 "En mille neuf cent vingt et un, René Maran reçoit le prix Goncourt pour Batouala : c'est le premier écrivain noir couronné.",
 "En séance B, nous faisons l'atelier final : un commentaire complet.",
 "Au labo, l'IA prépare une fiche sur votre roman bref, et vous la vérifiez. Puis nous faisons le bilan : quelles erreurs de l'IA avons-nous repérées ce semestre ?",
 "Merci pour ce semestre, et bonne lecture.",
],
raw_after_outil=["envers"],
))
