W = []

# ---------------------------------------------------------------- S1
W.append(dict(
n=1, dates="12–16 oct.", dates_long="12–16 octobre 2026",
title="Seuils du siècle", period="1782–1820",
sub="Rousseau, Chateaubriand, Staël · la nouvelle : qu'est-ce que c'est ?",
recit="Introduction à la nouvelle · René",
hand="Levez-vous vite, orages désirés…",
objectifs=[
 "Je situe le préromantisme entre Révolution, exil et Empire.",
 "Je repère qui dit <i>je</i> dans un texte, à qui il parle et pourquoi.",
 "Je sais ce qu'est une nouvelle et en quoi elle diffère du conte et du roman.",
 "J'utilise l'IA avec la charte du cours : déclarer, vérifier, écrire moi-même.",
],
prog=[("Partie A","Le contexte socio-culturel au seuil du XIXe siècle"),
      ("Partie B","Le genre de la nouvelle : premières définitions (Grojnowski, Schaeffer)"),
      ("A.2","Rousseau, Chateaubriand : deux extraits pour mon anthologie")],
seances=[("Se rencontrer, situer","Présentations, l'énigme du mal du siècle, la frise 1782–1820, quatre voix."),
         ("Atelier du texte","Rousseau et René : lire à voix haute, observer, traduire."),
         ("Nouvelle et labo IA","Qu'est-ce qu'une nouvelle ? Prise en main de l'Atelier du siècle et de la charte IA.")],
enigme=("Pourquoi toute une jeunesse européenne souffre-t-elle du même mal vers 1800 ?",
        "Rousseau, Chateaubriand, Goethe, Foscolo : partout en Europe, de jeunes héros tristes.",
        "le mal du siècle, avant le siècle…"),
frise=[("1782","Rousseau, Rêveries du promeneur solitaire (posthume)",0),
       ("1788","Bernardin de Saint-Pierre, Paul et Virginie",0),
       ("1793","Suppression des académies",1),
       ("1802","Chateaubriand, René, dans le Génie du christianisme",0),
       ("1804","Napoléon empereur : la censure s'installe",1),
       ("1813","Staël, De l'Allemagne, publié à Londres",0)],
frise_titre="Trente ans pour changer de monde",
auteurs=[("Rousseau","1712–1778","Le moi seul face à la nature : la confidence devient littérature."),
         ("Bernardin de Saint-Pierre","1737–1814","Paul et Virginie : une idylle sur une île coloniale, l'esclavage à l'arrière-plan."),
         ("Chateaubriand","1768–1848","Noble ruiné, exilé à Londres : avec René, il invente le héros mélancolique."),
         ("Germaine de Staël","1766–1817","Exilée par Napoléon, elle ouvre la France aux littératures du Nord.")],
outil=("La sociocritique","Lire la société dans le texte",
       [("Dire","Que dit le texte de sa société ?"),("Former","Comment le dit-il : genre, langue, figures ?"),("Taire","Que tait-il ?")],
       "Exemple : Paul et Virginie dit le bonheur, sous forme d'idylle, et tait le travail des esclaves."),
textes=[
 dict(title="Rousseau, la solitude", quotes=[(["Me voici donc seul sur la terre, n'ayant plus de frère, de prochain, d'ami, de société que moi-même."],
      "Rousseau, Rêveries du promeneur solitaire (1782), Première promenade")],
      questions=[("Énonciation","Qui parle ? Comment le je est-il mis en valeur ?"),("Rythme","Repérez l'énumération : que produit-elle ?"),("Société","Que dit cette solitude de la société du temps ?")]),
 dict(title="René, l'appel de l'orage", quotes=[(["Levez-vous vite, orages désirés, qui devez emporter René dans les espaces d'une autre vie !"],
      "Chateaubriand, René (1802)")],
      questions=[("Énonciation","René parle de lui à la troisième personne : pourquoi ?"),("Figures","Apostrophe et impératif : à qui s'adresse-t-il ?"),("Traduction","Comment dire orages désirés en italien ?")]),
],
methode=(1,"Lire avant d'analyser",
  ["Lire le texte deux fois, dont une à voix haute.","Noter le genre, l'époque et qui parle.","Écrire une hypothèse de lecture en une phrase."],
  "Une phrase pour René : Ce texte montre…, grâce à…"),
nouvelle=dict(label="Fil rouge · la nouvelle", title="Qu'est-ce qu'une nouvelle ?", quote=None,
  points=[("Brève","Une seule histoire, peu de personnages, une fin forte : la chute."),
          ("Presse","Au XIXe siècle, elle naît dans les journaux avant d'entrer en recueil."),
          ("Genre","Nouvelle, conte, récit : des frontières discutées (Grojnowski, Schaeffer).")],
  bas="Notre parcours : Mérimée, Gautier, Flaubert, Maupassant, Daudet, Barbey d'Aurevilly, Villiers de l'Isle-Adam."),
labo=dict(title="Prise en main de l'Atelier du siècle",
  steps=[("Demander","Chaque binôme pose une question à René sur ses orages désirés."),
         ("Vérifier","Retrouver dans le texte une affirmation de l'IA : vraie, fausse ou inventée ?"),
         ("Améliorer","Réécrire la réponse en trois phrases personnelles.")],
  produit="Première ligne du carnet de vérification IA, déposée sur Studium."),
italia=[("1802","Foscolo, Ultime lettere di Jacopo Ortis : la même année que René, un autre jeune héros désespéré."),
        ("1816","Germaine de Staël invite les Italiens à traduire les littératures étrangères (Biblioteca italiana)."),
        ("À faire","Lire René et Ortis côte à côte : deux douleurs, deux patries.")],
avant=["Lire Lamartine, Le Lac (Studium).","Lire Mérimée, Mateo Falcone (une dizaine de pages)."],
production="Une fiche de lecture d'une page sur René (modèle sur Studium).",
anthologie=["Rousseau, Rêveries, Première promenade","Chateaubriand, René, la page des orages"],
notes=[
 "Première rencontre. Annoncer le principe : huit semaines, trois séances de 2 h, chaque semaine un contexte, un texte, une nouvelle et un labo IA. Dire clairement dès aujourd'hui : je ne fais pas passer l'examen, mais tout le cours prépare l'écrit de commentaire et l'oral prévus par la fiche du cours.",
 "Lire les objectifs avec la classe. Ils sont écrits en je : chaque étudiant peut cocher en fin de semaine. Montrer l'encadré Programme : chaque semaine indique quels textes de la fiche (A.1, B, A.2) sont travaillés.",
 "Séance A : présentations (25 min), énigme (15 min), frise et contexte (35 min), auteurs (30 min), contrat et Studium (15 min). Séance B : texte à la loupe. Séance C : la nouvelle et le labo IA.",
 "Laisser 3 minutes de réponses spontanées, l'italien est accepté pour démarrer. Noter les mots au tableau (ennui, révolution, religion, amour, exil) et les photographier : on y revient en fin de semaine.",
 "Idée clé : le préromantisme n'est pas une école, c'est une étiquette posée après coup. Beaucoup d'œuvres naissent hors de France : Chateaubriand à Londres, Staël à Coppet.",
 "Répartir les quatre auteurs entre quatre groupes pour la séance B. Pour Paul et Virginie, ouvrir discrètement la piste coloniale ; pour Staël, souligner son conflit direct avec Napoléon.",
 "Ces trois questions reviennent chaque semaine. Ne pas faire de théorie : l'exemple de Paul et Virginie suffit. Elles serviront aussi à construire l'introduction d'un commentaire.",
 "Séance B, 30 min. Lecture à voix haute par trois étudiants. Faire repérer l'énumération qui isole le je. Lien avec la société : Rousseau se dit exclu par ses contemporains.",
 "Séance B, 30 min. Trois lecteurs pour la phrase des orages. Clé : René parle de lui à la troisième personne, il se regarde souffrir. Comparer deux traductions italiennes.",
 "Méthode, étape 1 (20 min). Chaque étudiant écrit son hypothèse sur une feuille ; en lire cinq à voix haute. Les huit étapes du semestre mènent au commentaire complet de la semaine 8.",
 "Séance C, 30 min. Le fil rouge reprend la partie B de la fiche (la nouvelle au XIXe siècle). Distinguer simplement nouvelle, conte, récit ; René est un récit bref enchâssé dans un essai. Présenter le parcours des huit semaines.",
 "Séance C, 40 min. Vérifier que chacun ouvre le lien claude.ai ; sinon projeter depuis le poste. Saluer chaque erreur de l'IA détectée par la classe : on forme des lecteurs vigilants.",
 "Demander qui a lu Foscolo au lycée. Les étudiants connaissent mieux la littérature italienne : c'est un levier de motivation.",
 "Rappeler la fiche de lecture à déposer et les extraits A.2 : l'anthologie personnelle de 50 extraits se construit semaine après semaine avec le cours.",
],
carnet=dict(objectif="installer le contrat du cours et une première lecture sociocritique du je préromantique.",
  A="Présentations (25 min, quatre diapositives personnelles et tour de table) ; énigme (15 min) ; frise et contexte (35 min) ; quatre voix (30 min) ; contrat, site et Studium (15 min).",
  B="Rousseau (30 min) ; René, lecture expressive et traduction (30 min) ; méthode, étape 1 (20 min) ; relevé en groupes sur les quatre auteurs (40 min).",
  C="Qu'est-ce qu'une nouvelle (30 min) ; prise en main de l'Atelier du siècle (40 min) ; pont italien (20 min) ; devoirs et charte IA (20 min).",
  anticiper="Demander aux étudiants ce qui a été vu avec Carminella Sipala la première semaine pour éviter les doublons. Vérifier l'accès à claude.ai."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine un : Seuils du siècle.",
 "Cette semaine pose la question qui guide tout le cours : qui a le pouvoir de dire ce qu'est la bonne littérature ?",
 "Vers mille huit cents, la Révolution supprime les académies. L'écrivain perd ses protecteurs et découvre le public. Beaucoup d'auteurs écrivent en exil, à Londres ou à Coppet. Puis l'Empire de Napoléon surveille les livres.",
 "Quatre voix nous accompagnent. Rousseau, seul face à la nature. Bernardin de Saint-Pierre, avec Paul et Virginie, une idylle sur une île coloniale. Chateaubriand, avec René, publié en mille huit cent deux. Et Germaine de Staël, qui ouvre la France à l'Europe.",
 "Notre énigme : pourquoi toute une jeunesse souffre-t-elle du même mal ? René en est le modèle : il appelle les orages pour être emporté dans une autre vie.",
 "Notre outil est la sociocritique. Trois questions : que dit le texte de sa société ? Comment le dit-il ? Et que tait-il ?",
 "Nous lisons aussi un critique, Philippe Van Tieghem. Pour lui, le préromantisme est d'abord une évolution de la sensibilité, puis du goût littéraire. Il écrit : la mélancolie devient le mal du siècle. Nous discuterons cette explication avec la sociocritique.",
 "Nous commençons aussi le fil rouge du semestre : la nouvelle. Une histoire brève, peu de personnages, une fin forte, souvent publiée d'abord dans un journal.",
 "Enfin, nous découvrons l'Atelier du siècle. La règle est simple : l'IA propose, vous vérifiez dans le texte, et vous écrivez vous-même.",
 "Pour la semaine prochaine, lisez Le Lac de Lamartine et Mateo Falcone de Mérimée.",
],
raw_after_cover=["moi","universite","istanbul","vous"],
site_slide=True,
))

# ---------------------------------------------------------------- S2
W.append(dict(
n=2, dates="19–23 oct.", dates_long="19–23 octobre 2026",
title="La bataille romantique", period="1820–1836",
sub="Lamartine, Hugo, Vigny, Musset · nouvelle : Mérimée, Mateo Falcone",
recit="Mérimée, Mateo Falcone",
hand="Ô temps ! suspends ton vol…",
objectifs=[
 "Je compte les syllabes d'un vers français : e muet, diérèse, césure.",
 "J'explique pourquoi 1830 est une bataille pour la place dans le champ littéraire.",
 "Je lis et je commente Le Lac, texte de la liste A.1.",
 "Je repère la concision et la chute dans une nouvelle de Mérimée.",
],
prog=[("A.1 · paire 1","Lamartine, Méditations poétiques (1820) : Le Lac"),
      ("Partie B","Mérimée, Mateo Falcone (1829)"),
      ("A.2","Hugo, Préface de Cromwell ; Musset, Confession d'un enfant du siècle")],
seances=[("Anciens contre modernes","Le Cénacle, la Préface de Cromwell, Hernani ; Bourdieu : le champ."),
         ("L'atelier du vers","Le Lac : compter, scander, lire à voix haute, traduire."),
         ("Nouvelle et labo IA","Mateo Falcone ; l'IA scande et se trompe ; le jeu d'Hernani.")],
enigme=("Comment une pièce de théâtre peut-elle déclencher une bagarre ?",
        "Paris, Comédie-Française, 25 février 1830 : première d'Hernani, de Victor Hugo.",
        "et le gilet rouge de Gautier…"),
frise=[("1820","Lamartine, Méditations poétiques",0),
       ("1827","Hugo, Préface de Cromwell",0),
       ("1829","Mérimée, Mateo Falcone (Revue de Paris)",0),
       ("1830","Hernani en février ; révolution de Juillet",1),
       ("1835","Vigny, Chatterton",0),
       ("1836","Musset, La Confession d'un enfant du siècle",0)],
frise_titre="Seize ans pour prendre la place",
auteurs=[("Lamartine","1790–1869","La voix intime de l'élégie : l'amour, la nature, le temps qui fuit."),
         ("Hugo","1802–1885","Chef de file : préfaces, théâtre, poésie, puis politique."),
         ("Vigny","1797–1863","Le poète solitaire et stoïque, en conflit avec la société."),
         ("Musset","1810–1857","Le plus jeune : il nomme le mal de toute une génération.")],
outil=("Le champ littéraire","Pierre Bourdieu",
       [("Champ","Un espace de jeu où les écrivains luttent pour la reconnaissance."),("Position","Chacun occupe une place : installé ou nouveau venu."),("Prise de position","Une œuvre, une préface, un manifeste sont des coups dans ce jeu.")],
       "En 1830, les classiques installés s'opposent aux romantiques qui arrivent : Hernani est une prise de position."),
textes=[
 dict(title="Lamartine, Le Lac", quotes=[(["Ô temps ! suspends ton vol, et vous, heures propices !","Suspendez votre cours :","Laissez-nous savourer les rapides délices","Des plus beaux de nos jours !"],
      "Lamartine, Le Lac, Méditations poétiques (1820)")],
      questions=[("Mètre","Comptez : 12, 6, 12, 6. Que produit cette alternance ?"),("Figures","Apostrophe et personnification : à qui parle le poète ?"),("Thème","Que demande-t-il au temps ? Peut-il l'obtenir ?")]),
 dict(title="Hugo, le manifeste", quotes=[(["Mettons le marteau dans les théories, les poétiques et les systèmes."],
      "Hugo, Préface de Cromwell (1827)")],
      questions=[("Image","Quel outil ? Que veut-il briser ?"),("Champ","Qui sont les anciens, qui sont les modernes ?"),("Acte","Une préface peut-elle être une prise de position ?")]),
],
methode=(2,"Compter les syllabes",
  ["e muet : compté devant consonne, élidé devant voyelle et en fin de vers.","Diérèse ou synérèse : li-on ou lion ?","Césure : l'alexandrin se coupe souvent 6//6."],
  "Scander le premier vers du Lac : Ainsi, toujours poussés vers de nouveaux rivages."),
nouvelle=dict(label="Fil rouge · la nouvelle", title="Mérimée, Mateo Falcone (1829)",
  quote=(["Fortunato tomba raide mort."],"dernière page"),
  points=[("Concision","Phrases courtes, narrateur impassible."),
          ("Chute","Un père tue son fils qui a trahi un bandit pour une montre."),
          ("Regard","La Corse vue de Paris : honneur, loi, exotisme.")],
  bas="Partie B de la fiche : Mérimée ouvre notre liste de nouvelles."),
labo=dict(title="L'IA scande… et se trompe",
  steps=[("Demander","Faire scander une strophe du Lac par l'IA."),
         ("Vérifier","Recompter syllabe par syllabe : e muet, diérèse, césure."),
         ("Améliorer","Écrire la règle que l'IA a oubliée.")],
  produit="La scansion corrigée d'une strophe, déposée sur Studium."),
italia=[("1823","Manzoni, Lettre à M. Chauvet : en français, contre les unités de temps et de lieu."),
        ("1844","Hernani devient Ernani, l'opéra de Verdi créé à Venise."),
        ("À faire","Endecasillabo et alexandrin : comment compte-t-on en italien et en français ?")],
avant=["Lire la dernière page du Père Goriot (Balzac).","Lire Gautier, La Morte amoureuse (Studium)."],
production="La scansion corrigée d'une strophe du Lac.",
anthologie=["Hugo, Préface de Cromwell (extrait)","Hugo, Hernani, scène d'ouverture","Musset, Confession d'un enfant du siècle, chapitre II"],
notes=[
 "Semaine technique : la versification est la base du commentaire écrit prévu par la fiche du cours. Annoncer le programme : un poème du programme (Le Lac), un manifeste, une pièce, une nouvelle.",
 "Insister sur l'objectif 1 : les étudiants italianistes connaissent l'endecasillabo, le compte français leur est souvent nouveau.",
 "Séance A : énigme et frise (30 min), auteurs (30 min), outil Bourdieu (30 min), Hugo (30 min). Séance B : tout Le Lac. Séance C : nouvelle, labo, jeu.",
 "Laisser imaginer : générations, goût, politique (1830 est aussi l'année de la révolution de Juillet). Gautier a 18 ans et mène les partisans de Hugo.",
 "Lire la frise comme une conquête : de la préface (1827) à la victoire (1830), puis le malaise de la génération suivante (Musset, 1836).",
 "Faire cartographier au tableau les anciens et les modernes de 1830. Chaque auteur occupe une position différente dans le même camp.",
 "Trois mots seulement : champ, position, prise de position. Ne pas citer Bourdieu longuement ; l'exemple d'Hernani suffit.",
 "Séance B, 60 min. Lecture expressive, puis scansion guidée. Préparer une fiche de référence sur Studium. Faire entendre l'alternance alexandrin et hexasyllabe : le vers court mime la suspension demandée.",
 "Séance A, 20 min. La phrase de Hugo est brève et frappante : bon exemple de prise de position. Faire comparer avec un manifeste italien connu des étudiants.",
 "Méthode, étape 2. Faire scander le premier vers ensemble : Ain-si-tou-jours-pous-sés // vers-de-nou-veaux-ri-va(ges). Le e final de rivages n'est pas compté.",
 "Séance C, 30 min. Mateo Falcone se lit en entier. Faire repérer la dernière phrase : la sécheresse du style rend la violence plus forte.",
 "Séance C, 30 min. L'IA se trompe souvent sur le e muet et la diérèse : c'est un exercice idéal pour vérifier ses propres connaissances.",
 "Le jeu d'Hernani (30 min) : deux camps, slogans, lecture des premiers vers. Apporter un accessoire rouge pour le camp de Gautier.",
 "Rappeler : le Lac est un texte A.1, il faut le relire jusqu'à pouvoir le lire de façon expressive et le traduire.",
],
carnet=dict(objectif="comprendre 1830 comme une révolution des formes et du champ, et maîtriser les bases de la versification.",
  A="Énigme et frise (30 min) ; auteurs (30 min) ; outil : le champ (30 min) ; Hugo, Préface de Cromwell (30 min).",
  B="Le Lac : lecture expressive (15 min), scansion guidée (45 min), méthode étape 2 (30 min), traduction italienne (30 min).",
  C="Mateo Falcone (30 min) ; labo IA scansion (30 min) ; jeu d'Hernani (40 min) ; pont italien et devoirs (20 min).",
  anticiper="Prévoir la fiche de versification sur Studium. Le compte syllabique est nouveau pour beaucoup : faire le parallèle avec l'endecasillabo."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine deux : La bataille romantique.",
 "Le vingt-cinq février mille huit cent trente, à la Comédie-Française, la première d'Hernani, de Victor Hugo, se transforme en bagarre. Pourquoi ? Parce qu'une nouvelle génération veut prendre la place des classiques.",
 "Quatre romantiques occupent quatre positions. Lamartine renouvelle la poésie intime. Hugo est le chef de file. Vigny est le poète solitaire. Musset, le plus jeune, nomme le mal d'une génération.",
 "Notre outil vient de Pierre Bourdieu : le champ littéraire. C'est un jeu où chacun occupe une position, et où chaque œuvre, chaque préface, est une prise de position.",
 "Nous lisons aussi le manuel d'Yves Stalloni. Pour lui, le mot bataille n'est pas trop fort : le romantisme naît dans des salons, des cénacles et des revues, avant d'avoir une doctrine.",
 "Le texte du programme est Le Lac de Lamartine : Ô temps, suspends ton vol. Nous apprenons à compter les syllabes : le e muet, la diérèse, la césure au milieu de l'alexandrin. Écoutez l'alternance des vers longs et des vers courts.",
 "La nouvelle de la semaine est Mateo Falcone, de Mérimée. En Corse, un père tue son fils qui a trahi un bandit pour une montre. Des phrases courtes, un narrateur impassible.",
 "Au labo, l'IA scande une strophe du Lac. Elle se trompe souvent. À vous de trouver ses erreurs.",
 "Côté italien, Hernani devient l'opéra Ernani de Verdi, à Venise, en mille huit cent quarante-quatre.",
],
))

# ---------------------------------------------------------------- S3
W.append(dict(
n=3, dates="26–30 oct.", dates_long="26–30 octobre 2026",
title="Le roman, miroir et marché", period="1830–1848",
sub="Stendhal, Balzac, la presse · nouvelle : Gautier, La Morte amoureuse",
recit="Gautier, La Morte amoureuse",
hand="À nous deux maintenant !",
objectifs=[
 "J'explique comment la presse et le feuilleton changent le roman.",
 "Je lis un personnage comme une trajectoire sociale : Rastignac.",
 "Je formule une problématique à partir de mes observations.",
 "Je reconnais le fantastique dans une nouvelle de Gautier.",
],
prog=[("Partie A","Le roman réaliste et la presse, 1830–1848"),
      ("Partie B","Gautier, La Morte amoureuse (1836)"),
      ("A.2","Stendhal, Le Rouge et le Noir ; Balzac, Le Père Goriot")],
seances=[("Argent, presse, roman","Monarchie de Juillet, La Presse de Girardin, le feuilleton ; Bourdieu : capitaux et trajectoire."),
         ("Atelier du texte","Stendhal et la fin du Père Goriot : du relevé à la problématique."),
         ("Nouvelle et labo IA","La Morte amoureuse ; l'IA propose des problématiques, vous choisissez.")],
enigme=("Un roman peut-il être à la fois une œuvre d'art et une marchandise ?",
        "1836 : un journal à moitié prix, payé par la publicité, publie des romans par épisodes.",
        "la suite au prochain numéro…"),
frise=[("1830","Stendhal, Le Rouge et le Noir",0),
       ("1835","Balzac, Le Père Goriot",0),
       ("1836","Girardin lance La Presse : le roman-feuilleton",1),
       ("1836","Gautier, La Morte amoureuse",0),
       ("1839","Sainte-Beuve, De la littérature industrielle",1),
       ("1842","Balzac, Avant-propos de La Comédie humaine ; Sue, Les Mystères de Paris",0)],
frise_titre="Le roman entre dans le journal",
auteurs=[("Stendhal","1783–1842","Milanais de cœur : le roman comme miroir, l'ambition comme moteur."),
         ("Balzac","1799–1850","La Comédie humaine : toute une société, de la pension au salon."),
         ("Gautier","1811–1872","Le jeune romantique d'Hernani, conteur fantastique."),
         ("Eugène Sue","1804–1857","Les Mystères de Paris : le grand succès du feuilleton.")],
outil=("Capitaux et trajectoire","Pierre Bourdieu",
       [("Capital économique","L'argent, les biens."),("Capital culturel","Le savoir, les diplômes, le goût."),("Capital social","Les relations, les salons.")],
       "Rastignac arrive à Paris avec peu de capital : le roman suit sa trajectoire dans la société."),
textes=[
 dict(title="Stendhal, le miroir", quotes=[(["Un roman est un miroir qui se promène sur une grande route."],
      "Stendhal, Le Rouge et le Noir (1830), livre II, chapitre 19")],
      questions=[("Image","Que reflète le miroir ? Qui le porte ?"),("Défense","Pourquoi Stendhal se défend-il ainsi ?"),("Débat","Un miroir est-il neutre ?")]),
 dict(title="Balzac, le défi", quotes=[(["À nous deux maintenant !"],
      "Balzac, Le Père Goriot (1835), dernière page : Rastignac regarde Paris depuis le Père-Lachaise")],
      questions=[("Lieu","Que voit Rastignac depuis la colline ?"),("Défi","À qui parle-t-il ? Que veut-il conquérir ?"),("Trajectoire","De la pension Vauquer aux salons : quel chemin ?")]),
],
methode=(3,"Trouver une problématique",
  ["Partir de ses relevés (étapes 1 et 2).","Poser une vraie question : comment, en quoi, pourquoi.","Vérifier : la réponse n'est pas évidente et concerne tout le texte."],
  "Trois problématiques par groupe pour la fin du Père Goriot ; on les classe ensemble."),
nouvelle=dict(label="Fil rouge · la nouvelle", title="Gautier, La Morte amoureuse (1836)",
  quote=(["Vous me demandez, frère, si j'ai aimé ; oui."],"première phrase"),
  points=[("Récit","Un vieux prêtre raconte sa double vie avec Clarimonde, une morte."),
          ("Fantastique","Rêve ou réalité ? Le lecteur hésite jusqu'au bout."),
          ("Presse","Publiée dans la Chronique de Paris, la revue de Balzac.")],
  bas="Partie B de la fiche : Gautier, la nouvelle fantastique."),
labo=dict(title="L'IA propose, vous choisissez",
  steps=[("Demander","Faire proposer cinq problématiques sur la fin du Père Goriot."),
         ("Vérifier","Lesquelles sont de vraies questions ? Lesquelles inventent des détails ?"),
         ("Améliorer","Garder la meilleure et la réécrire avec vos mots.")],
  produit="Une problématique déposée dans l'Atelier commentaire."),
italia=[("Stendhal","Arrigo Beyle, Milanese : c'est l'épitaphe qu'il demande."),
        ("1840","Manzoni, I promessi sposi, édition définitive : un autre roman de la société."),
        ("1839","La Chartreuse de Parme : l'Italie vue par Stendhal.")],
avant=["Lire Baudelaire, Le Spleen de Paris : L'Étranger et Enivrez-vous (Studium).","Lire Flaubert, Un cœur simple, chapitre I."],
production="Une problématique rédigée pour la fin du Père Goriot.",
anthologie=["Stendhal, Le Rouge et le Noir, le miroir (II, 19)","Balzac, Le Père Goriot, la dernière page","Balzac, Avant-propos de La Comédie humaine (extrait)"],
notes=[
 "Semaine du roman. Fil conducteur : le roman devient une marchandise de presse, et pourtant il veut dire la vérité de la société.",
 "Objectif central : la problématique. Le commentaire écrit de la fiche du cours en dépend.",
 "Séance A : énigme, frise, auteurs (60 min), outil capitaux (30 min), Stendhal (30 min). Séance B : Balzac et la problématique. Séance C : Gautier et labo.",
 "Faire calculer : un abonnement à moitié prix, financé par les annonces. D'où le besoin de feuilletons qui retiennent le lecteur.",
 "Montrer la date double de 1836 : La Presse et La Morte amoureuse la même année. Sainte-Beuve dénonce une littérature industrielle (1839).",
 "Stendhal et Balzac sont des A.2 possibles : inviter les étudiants à choisir un extrait pour leur anthologie.",
 "Faire classer Rastignac, Goriot et Vautrin selon les trois capitaux. Exercice rapide de 10 minutes.",
 "Séance A, 30 min. Le miroir se défend contre l'accusation d'immoralité : ce n'est pas le romancier qui est coupable, c'est la route. Bonne question de débat.",
 "Séance B, 30 min. Lire la dernière page entière (Studium). Montrer une carte de Paris : pension Vauquer, faubourg Saint-Germain, Chaussée-d'Antin, Père-Lachaise.",
 "Méthode, étape 3 (40 min). Faire écrire trois problématiques par groupe, puis les classer : trop large, trop étroite, juste.",
 "Séance C, 30 min. Présenter le fantastique avec simplicité : hésitation entre explication naturelle et surnaturelle. Lien avec Hernani : Gautier est le gilet rouge de 1830.",
 "Séance C, 30 min. L'IA produit souvent des problématiques générales ou invente un détail du texte : excellent exercice de vérification.",
 "Rappeler que Stendhal vivait à Milan et se voulait milanais : lien naturel avec le public italien.",
 "Annoncer la semaine 4 : premier texte A.1 en prose, Le Spleen de Paris. Lire L'Étranger avant le cours.",
],
carnet=dict(objectif="lire le roman réaliste à la fois comme représentation sociale et comme marchandise de presse.",
  A="Énigme et frise (25 min) ; auteurs (35 min) ; outil capitaux (30 min) ; Stendhal, le miroir (30 min).",
  B="Balzac, dernière page du Père Goriot (40 min) ; méthode étape 3 (50 min) ; mise en commun (30 min).",
  C="La Morte amoureuse (35 min) ; labo IA problématiques (35 min) ; pont italien (20 min) ; devoirs (10 min) et carte de Paris (20 min).",
  anticiper="Prévoir une carte de Paris projetée. Mettre le texte intégral de La Morte amoureuse sur Studium."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine trois : Le roman, miroir et marché.",
 "En mille huit cent trente-six, Émile de Girardin lance La Presse, un journal moins cher, payé par la publicité. Pour garder ses lecteurs, il publie des romans par épisodes : c'est le roman-feuilleton.",
 "Le roman devient une marchandise. Et pourtant, il veut dire la vérité de la société. Stendhal écrit : un roman est un miroir qui se promène sur une grande route.",
 "Balzac construit La Comédie humaine. À la fin du Père Goriot, le jeune Rastignac regarde Paris et lance : à nous deux maintenant !",
 "Notre outil vient encore de Bourdieu : les capitaux. Le capital économique, c'est l'argent. Le capital culturel, c'est le savoir. Le capital social, ce sont les relations. Rastignac doit tout conquérir.",
 "En méthode, nous apprenons à poser une problématique : une vraie question, qui concerne tout le texte.",
 "La nouvelle de la semaine est La Morte amoureuse, de Théophile Gautier. Un vieux prêtre raconte son amour pour Clarimonde, une morte. Rêve ou réalité ? C'est le fantastique.",
 "Au labo, l'IA propose cinq problématiques. Vous choisissez la meilleure, et vous la réécrivez.",
 "Pour la semaine prochaine, lisez L'Étranger et Enivrez-vous, de Baudelaire.",
],
))

# ---------------------------------------------------------------- S4
W.append(dict(
n=4, dates="2–6 nov.", dates_long="2–6 novembre 2026",
title="1857, l'année des procès", period="1835–1877",
sub="Baudelaire, Flaubert, l'art pour l'art · nouvelle : Flaubert, Un cœur simple",
recit="Flaubert, Un cœur simple",
hand="Il faut être toujours ivre.",
objectifs=[
 "J'explique pourquoi Flaubert et Baudelaire sont jugés en 1857.",
 "Je reconnais un poème en prose : Le Spleen de Paris, liste A.1.",
 "Je construis un plan en deux ou trois axes.",
 "J'analyse le style indirect libre dans Un cœur simple.",
],
prog=[("A.1 · paire 3","Baudelaire, Le Spleen de Paris (1869) : L'Étranger, Enivrez-vous"),
      ("Partie B","Flaubert, Un cœur simple (Trois Contes, 1877)"),
      ("A.2","Baudelaire, Les Fleurs du mal : Au lecteur, L'Albatros")],
seances=[("Procès et autonomie","Second Empire et censure ; Gautier et l'art pour l'art ; Bourdieu : le monde à l'envers."),
         ("Atelier du texte","Le Spleen de Paris : qu'est-ce qu'un poème en prose ? Construire un plan."),
         ("Nouvelle et labo IA","Un cœur simple ; l'IA a-t-elle dit vrai ? ; le tribunal de 1857.")],
enigme=("Pourquoi juge-t-on des livres au tribunal ?",
        "1857 : Flaubert est acquitté en février, Baudelaire condamné en août.",
        "outrage à la morale publique…"),
frise=[("1835","Gautier, préface de Mademoiselle de Maupin : l'art pour l'art",0),
       ("1852","Second Empire : la presse sous surveillance",1),
       ("1857","Février : Madame Bovary, acquitté",1),
       ("1857","Août : Les Fleurs du mal, six poèmes condamnés",1),
       ("1869","Le Spleen de Paris (posthume)",0),
       ("1877","Flaubert, Trois Contes",0)],
frise_titre="De l'art pour l'art au tribunal",
auteurs=[("Baudelaire","1821–1867","La beauté tirée du mal, de la ville et de l'ennui ; le poème en prose moderne."),
         ("Flaubert","1821–1880","Le travail du style, un auteur invisible, un procès gagné."),
         ("Gautier","1811–1872","L'art pour l'art : le beau n'a pas à être utile."),
         ("Leconte de Lisle","1818–1894","Le Parnasse : une poésie impassible et savante.")],
outil=("Le monde à l'envers","Pierre Bourdieu, Les Règles de l'art",
       [("Autonomie","L'art veut ses propres règles, contre la morale et le marché."),("À l'envers","Perdre en argent ou au tribunal peut faire gagner en prestige."),("Consécration","Les condamnés de 1857 deviennent des classiques.")],
       "Baudelaire condamné en 1857 est aujourd'hui au programme : qui a gagné ?"),
textes=[
 dict(title="Baudelaire, L'Étranger", quotes=[(["— Qui aimes-tu le mieux, homme énigmatique, dis ? ton père, ta mère, ta sœur ou ton frère ?","— Je n'ai ni père, ni mère, ni sœur, ni frère."],
      "Baudelaire, L'Étranger, Le Spleen de Paris (1869)")],
      questions=[("Forme","Pas de vers, pas de rime : où est la poésie ?"),("Dialogue","Qui interroge ? Qui refuse ?"),("Société","Famille, patrie, argent : que refuse l'étranger ?")]),
 dict(title="Baudelaire, Enivrez-vous", quotes=[(["Il faut être toujours ivre. Tout est là : c'est l'unique question."],
      "Baudelaire, Enivrez-vous, Le Spleen de Paris (1869)")],
      questions=[("Ton","Il faut : quel ton, quelle voix ?"),("Ivresse","De vin, de poésie ou de vertu : de quoi parle-t-il ?"),("Plan","Proposez deux axes pour un commentaire.")]),
],
methode=(4,"Construire un plan",
  ["Deux ou trois axes qui répondent à la problématique.","Chaque axe : une idée, deux ou trois analyses précises.","Aller du plus visible au plus profond."],
  "En groupes, un plan pour L'Étranger ; comparaison des plans au tableau."),
nouvelle=dict(label="Fil rouge · la nouvelle", title="Flaubert, Un cœur simple (1877)",
  quote=(["Pendant un demi-siècle, les bourgeoises de Pont-l'Évêque envièrent à Mme Aubain sa servante Félicité."],"première phrase"),
  points=[("Personnage","Une servante au centre du récit : un choix nouveau."),
          ("Style","Le style indirect libre : on entend Félicité sans qu'elle parle."),
          ("Loulou","Le perroquet, objet d'amour et de foi.")],
  bas="Partie B de la fiche : Flaubert, maître du récit court."),
labo=dict(title="Madame Bovary, c'est moi ?",
  steps=[("Demander","Demander à Flaubert, dans l'Atelier du siècle, s'il a dit cette phrase."),
         ("Vérifier","Chercher la source : un témoignage indirect, rapporté bien plus tard."),
         ("Améliorer","Écrire la réponse juste en deux phrases, avec la source.")],
  produit="Une vérification de citation dans le carnet IA."),
italia=[("Verga","Lecteur de Flaubert : l'auteur qui s'efface derrière ses personnages."),
        ("Scapigliatura","À Milan, de jeunes poètes lisent Baudelaire et se veulent maudits."),
        ("Jeu","Le tribunal de 1857 : comparer notre verdict au verdict réel.")],
avant=["Lire Maupassant, Boule de suif (début) ou Le Horla.","Lire Daudet, La Dernière Classe (Studium)."],
production="Un plan en deux ou trois axes pour L'Étranger.",
anthologie=["Baudelaire, Au lecteur","Baudelaire, L'Albatros","Flaubert, Madame Bovary I, 6 (les lectures d'Emma)"],
notes=[
 "Premier texte A.1 en prose : Le Spleen de Paris. La paire 3 de la fiche oppose Baudelaire et Gide (semaine 7).",
 "L'objectif plan est essentiel pour l'écrit. Le style indirect libre sera repris en semaine 5.",
 "Séance A : énigme, frise, outil (60 min) ; auteurs et Gautier (60 min). Séance B : Baudelaire et le plan. Séance C : Flaubert, labo, tribunal.",
 "Préciser qu'en 1857 il n'y avait pas de jury : c'était un tribunal correctionnel. Les jurés du jeu sont fictifs.",
 "Verdicts réels : Flaubert acquitté le 7 février ; Baudelaire condamné le 20 août à une amende et à la suppression de six poèmes. Le Spleen de Paris paraît deux ans après sa mort.",
 "Flaubert et Baudelaire naissent la même année, 1821. Gautier, le gilet rouge de 1830, est devenu un maître : Baudelaire lui dédie Les Fleurs du mal.",
 "Ne garder que l'idée du monde à l'envers : perdre au tribunal ou en argent peut faire gagner en prestige.",
 "Séance B, 45 min. Dans la dédicace à Arsène Houssaye, Baudelaire rêve d'une prose poétique, musicale sans rythme et sans rime. Lire L'Étranger entier à deux voix.",
 "Séance B, 30 min. Faire relever les trois ivresses (vin, poésie, vertu) : le poème refuse de choisir entre morale et plaisir.",
 "Méthode, étape 4 (45 min). Comparer les plans au tableau : axe thématique ou axe formel ? Les deux sont possibles si la problématique les relie.",
 "Séance C, 30 min. Faire entendre le style indirect libre sur une page du chapitre IV : les pensées de Félicité dans la voix du narrateur.",
 "Séance C, 25 min. La phrase sur Madame Bovary vient d'un témoignage indirect : bon test d'hallucination. Valoriser l'étudiant qui trouve la source.",
 "Le tribunal (40 min) : distribuer les rôles dès la fin de la semaine 3 (Pinard procureur, Senard avocat de Flaubert). Prévoir un chronomètre.",
 "Annoncer la semaine 5 : atelier de commentaire de 2 h, sans note, avec retour écrit.",
],
carnet=dict(objectif="saisir l'autonomie du champ littéraire à travers les procès de 1857 et lire un premier texte A.1 en prose.",
  A="Énigme et frise (30 min) ; outil : le monde à l'envers (30 min) ; auteurs, Gautier et le Parnasse (40 min) ; L'Albatros pour l'anthologie (20 min).",
  B="L'Étranger (45 min) ; Enivrez-vous (30 min) ; méthode étape 4, le plan (45 min).",
  C="Un cœur simple (30 min) ; labo IA citation (25 min) ; tribunal de 1857 (45 min) ; pont italien et devoirs (20 min).",
  anticiper="Distribuer les rôles du tribunal dès la semaine 3. Le jeu prend facilement 45 minutes."),
audio=[
 "Bonjour, et bienvenue dans le résumé audio de la semaine quatre : mille huit cent cinquante-sept, l'année des procès.",
 "Cette année-là, deux écrivains passent au tribunal. Flaubert, pour Madame Bovary, est acquitté en février. Baudelaire, pour Les Fleurs du mal, est condamné en août : six poèmes sont retirés.",
 "Pourquoi juger des livres ? Parce que le Second Empire surveille la presse et la morale. Mais les écrivains veulent une autre règle : l'art pour l'art, défendue par Gautier. Le beau n'a pas à être utile.",
 "Notre outil est le monde à l'envers, selon Bourdieu : perdre au tribunal ou en argent peut faire gagner en prestige. Aujourd'hui, Baudelaire est au programme.",
 "Avec le manuel de Stalloni, nous distinguons trois refus : l'art pour l'art de Gautier, le Parnasse, et le réalisme. Flaubert, lui, refuse toutes les étiquettes.",
 "Le texte du programme est Le Spleen de Paris, des poèmes en prose. Dans L'Étranger, un homme refuse famille, patrie et argent, et n'aime que les nuages. Dans Enivrez-vous, Baudelaire écrit : il faut être toujours ivre.",
 "En méthode, nous construisons un plan en deux ou trois axes.",
 "La nouvelle de la semaine est Un cœur simple, de Flaubert : la vie d'une servante, Félicité, et de son perroquet Loulou.",
 "Au labo, nous demandons à Flaubert s'il a vraiment dit : Madame Bovary, c'est moi. Puis nous cherchons la source.",
 "Pour la semaine prochaine, lisez Boule de suif ou Le Horla, et La Dernière Classe de Daudet.",
],
))
