# Notes de l'enseignant, version développée (semaines 1 à 4).
# Clé = identifiant de diapositive. Format : étiquettes en capitales, une rubrique par ligne.

def N(duree, deroule, questions=None, attendus=None, piege=None, plus=None, source=None):
    parts = [f"DURÉE · {duree}", f"DÉROULÉ · {deroule}"]
    if questions: parts.append(f"QUESTIONS À POSER · {questions}")
    if attendus: parts.append(f"RÉPONSES ATTENDUES · {attendus}")
    if piege: parts.append(f"POINT DE VIGILANCE · {piege}")
    if plus: parts.append(f"POUR ALLER PLUS LOIN · {plus}")
    if source: parts.append(f"SOURCES · {source}")
    return "\n\n".join(parts)

NOTES = {}

NOTES[1] = {
"cover": N("5 min, séance A",
  "Accueillir, se présenter en une phrase, annoncer le principe : huit semaines, trois séances de 2 h, chaque semaine un contexte, un texte du programme, une nouvelle et un labo IA. Dire clairement que l'examen (écrit de commentaire propédeutique, puis oral, en français) est organisé selon la fiche du cours : je ne le fais pas passer, mais tout le cours y prépare.",
  questions="Qui a déjà lu en entier un texte français du XIXe siècle ? Lequel ?",
  piege="Ne pas détailler tout le programme maintenant : renvoyer au site et à Studium."),
"objectifs": N("5 min",
  "Lire les quatre objectifs à voix haute. Montrer les cases : chacun coche en fin de semaine. Expliquer l'encadré Dans la fiche du cours : A.1 = six paires d'œuvres, on en choisit une par paire et on la lit en entier ; B = la nouvelle au XIXe siècle ; A.2 = anthologie personnelle de 50 extraits, à faire valider au moins 30 jours avant l'examen, sans reprendre A.1 ni B.",
  piege="Les étudiants confondent souvent A.1 et A.2. Le dire deux fois et l'écrire au tableau."),
"seances": N("3 min",
  "Présenter le rythme fixe : A contexte, B atelier du texte, C nouvelle et IA. Chaque semaine se termine par une petite production déposée sur Studium : elle sert de trace de travail et de préparation à l'écrit."),
"enigme": N("15 min",
  "Trois minutes de réponses spontanées, l'italien est accepté pour démarrer. Noter les mots au tableau et photographier le tableau : on y revient en séance C, après la lecture critique de Van Tieghem.",
  questions="Qui sont ces jeunes héros tristes ? Werther (1774), René (1802), Jacopo Ortis (1802). Pourquoi le même mal partout en Europe ?",
  attendus="Ennui, désillusion après la Révolution, perte des repères religieux, inadaptation sociale, amour impossible, excès de rêve.",
  piege="Éviter l'anachronisme médical (dépression) : le mal du siècle est une catégorie littéraire et sociale, pas un diagnostic.",
  plus="Réponse de la critique à révéler en fin de semaine : Van Tieghem, p. 10, La mélancolie devient le mal du siècle."),
"frise": N("15 min",
  "Lire la frise de gauche à droite. Idée clé : le préromantisme n'est pas une école, c'est une étiquette posée après coup. Les académies sont supprimées par la Convention le 8 août 1793 ; l'Institut les remplace en 1795. Beaucoup d'œuvres naissent hors de France : Chateaubriand émigré à Londres (1793-1800), Staël exilée à Coppet ; De l'Allemagne est pilonné par la police impériale en 1810 et paraît à Londres en 1813.",
  questions="Pourquoi tant d'œuvres françaises sont-elles écrites hors de France ?",
  attendus="Émigration, exil, censure impériale : la géographie de la littérature suit la politique.",
  plus="Le mot préromantisme est discuté depuis le colloque de Clermont-Ferrand (1972) : Le Préromantisme, hypothèque ou hypothèse ?, dir. Paul Viallaneix, Klincksieck, 1975.",
  source="P. Viallaneix (dir.), 1975 ; Van Tieghem, chap. I."),
"auteurs": N("25 min",
  "Quatre groupes, un auteur par groupe : 5 minutes de lecture d'une fiche (Studium), 1 minute de présentation chacun. Rousseau : Rêveries rédigées en 1776-1778, publiées en 1782 ; La Nouvelle Héloïse (1761). Bernardin : Paul et Virginie (1788), à l'île de France (Maurice). Chateaubriand : voyage en Amérique (1791), émigration, Génie du christianisme (1802). Staël : fille de Necker, éloignée de Paris par Napoléon à partir de 1803.",
  questions="Pour Paul et Virginie : qui travaille dans ce paradis ?",
  attendus="Les esclaves Domingue et Marie : l'idylle repose sur une société esclavagiste.",
  piege="Ne pas transformer la séance en biographies : une idée par auteur suffit."),
"outil": N("15 min",
  "Présenter les trois questions comme un outil, pas comme une théorie. Les appliquer tout de suite à Paul et Virginie : la société de référence (colonie), la forme (idylle pastorale), le non-dit (le travail servile).",
  questions="Quelle différence entre la sociocritique et la biographie ?",
  attendus="La sociocritique part du texte (sa langue, ses formes, ses silences), pas de la vie de l'auteur.",
  piege="Sociocritique ne veut pas dire sociologie de la littérature : on lit d'abord le texte.",
  source="Claude Duchet, Pour une socio-critique ou variations sur un incipit, Littérature, n° 1, 1971."),
"critique-vantieghem": N("20 min, séance A ou C",
  "Lire les deux citations à voix haute. Expliquer la thèse en trois temps : 1. le préromantisme est une transition (de 1750 environ au début de la Restauration) ; 2. il change d'abord la sensibilité, ensuite seulement le goût et les formes ; 3. Rousseau en est le type, Staël et Chateaubriand les maîtres immédiats du romantisme. Insister sur la page 7 : La Nouvelle Héloïse fait passer en littérature ce qui restait dans les journaux intimes et les lettres privées.",
  questions="Une histoire de la sensibilité suffit-elle à expliquer une littérature ? Le mot préromantisme juge-t-il le XVIIIe siècle à partir de la suite ?",
  attendus="Van Tieghem parle d'une civilisation qui passe de la dureté à la sensibilité, avec des images d'enfance et d'adolescence de l'âme romantique : explication psychologique et presque organique. Il admet pourtant des causes d'ordre économique et politique (p. 7) sans les étudier : c'est l'endroit exact où intervient la sociocritique (public, exil, censure, marché).",
  piege="Ne pas disqualifier l'article : c'est une synthèse claire et une très bonne carte des thèmes. On le discute, on ne le rejette pas.",
  plus="Faire relever les métaphores de Van Tieghem (germe, fleurs, climat classique) : le critique écrit lui-même en style préromantique. Bon exercice de lecture critique.",
  source="Van Tieghem, Le Romantisme français, PUF, Que sais-je ?, chap. I, p. 5-14 (Cairn)."),
"critique-vantieghem-frise": N("10 min",
  "Montrer que la sensibilité nouvelle arrive par les traductions : Young traduit par Le Tourneur (1769), Werther traduit dès 1776. Ossian mérite un arrêt : ces poèmes présentés comme des chants gaéliques anciens sont en grande partie composés par James Macpherson. Toute l'Europe les admire, Napoléon compris.",
  questions="Pourquoi la France importe-t-elle sa sensibilité ? Quel rapport entre Ossian et nos labos IA ?",
  attendus="Selon Van Tieghem (p. 12), le classicisme pèse plus lourd en France. Ossian est un faux ancien qui a convaincu tout un continent : la vérification des sources n'est pas un problème né avec l'IA.",
  source="Van Tieghem, p. 12-13."),
"texte1": N("30 min, séance B",
  "Lecture par trois étudiants, puis relevé. Énumération décroissante : frère, prochain, ami, société, jusqu'à moi-même en fin de phrase. La phrase suivante du texte dit que le plus sociable des humains a été proscrit par un accord unanime : lire cette suite à voix haute.",
  questions="Que met en valeur la place de moi-même ? Qui est responsable de cette solitude, selon le texte ?",
  attendus="Isolement total et chute de la phrase sur le moi ; la faute est rejetée sur la société.",
  piege="Le je de Rousseau n'est pas neutre : le texte construit sa propre innocence. C'est une bonne question pour l'axe Que tait-il ?",
  plus="Comparer avec une traduction italienne publiée et faire repérer ce qui se perd dans l'énumération."),
"texte2": N("30 min, séance B",
  "Trois lecteurs pour la phrase des orages. Clé : René parle de lui à la troisième personne (énallage de personne), il se regarde souffrir. Paradoxe : désirer l'orage. Proposer deux traductions et voter : tempeste desiderate, bramate tempeste.",
  questions="Pourquoi René parle-t-il de lui comme d'un autre ? Que cherche-t-il dans l'orage ?",
  attendus="Mise en scène de soi, plaisir de la souffrance, désir d'un ailleurs : une autre vie.",
  piege="Ne pas confondre René et Chateaubriand. Chateaubriand lui-même a pris ses distances avec son héros dans les Mémoires d'outre-tombe.",
  source="Chateaubriand, René, 1802 ; Van Tieghem, p. 10 (vagues passions, ardentes chez Chateaubriand)."),
"methode": N("20 min",
  "Chacun écrit son hypothèse sur une feuille selon le modèle Ce texte montre…, grâce à… Lire cinq hypothèses, les améliorer ensemble. Annoncer la progression : huit étapes jusqu'au commentaire complet de la semaine 8.",
  attendus="Ce texte montre un héros qui désire sa propre perte, grâce à l'apostrophe et à l'impératif.",
  piege="Les hypothèses trop générales (Ce texte parle de la tristesse) : demander toujours grâce à quoi."),
"nouvelle": N("30 min, séance C",
  "Définir simplement : brièveté, une seule action, unité d'effet, chute. Rappeler que la fiche du cours consacre toute la partie B à la nouvelle du XIXe siècle. René n'est pas une nouvelle au sens strict : c'est un récit bref enchâssé dans le Génie du christianisme pour illustrer le chapitre Du vague des passions, puis publié à part en 1805 avec Atala.",
  questions="Nouvelle, conte, récit : quelle différence ?",
  attendus="Le conte accepte le merveilleux ; la nouvelle vise le vraisemblable et la chute ; récit est le terme le plus large.",
  piege="Les frontières sont discutées : un genre est un nom donné après coup, comme préromantisme.",
  source="D. Grojnowski, Lire la nouvelle, Dunod, 1993 ; J.-M. Schaeffer, Qu'est-ce qu'un genre littéraire ?, Seuil, 1989."),
"labo": N("40 min, séance C",
  "Vérifier que chacun ouvre le lien ; sinon projeter. Binômes. Prompt modèle : René, pourquoi appelles-tu les orages ? Puis remplir le carnet IA : question posée, affirmation de l'IA, vérification (page), verdict (vrai, faux, inventé).",
  questions="Quelle affirmation de l'IA avez-vous pu vérifier dans le texte ? Laquelle n'a pas de source ?",
  piege="Erreurs fréquentes de l'IA : citations inventées, dates approximatives, René confondu avec Les Natchez (où il réapparaît). Saluer chaque erreur trouvée.",
  plus="Rapprocher de la diapositive Ossian : un texte crédible n'est pas un texte vrai."),
"italia": N("15 min",
  "Foscolo publie l'édition de 1802 des Ultime lettere di Jacopo Ortis, roman épistolaire inspiré de Werther. L'article de Staël Sulla maniera e la utilità delle traduzioni (Biblioteca italiana, janvier 1816) déclenche la polémique entre classiques et romantiques en Italie.",
  questions="Qui a lu Foscolo au lycée ? Qu'est-ce qui rapproche Ortis de René ?",
  attendus="Exil, amour impossible, patrie blessée, suicide chez Ortis et non chez René."),
"bilan": N("10 min",
  "Revenir à la photo du tableau de l'énigme et lire la citation de Van Tieghem sur la mélancolie. Rappeler la fiche de lecture à déposer et les deux extraits A.2. Annoncer la bataille d'Hernani : répartir les deux camps dès maintenant."),
}

NOTES[2] = {
"cover": N("3 min", "Annoncer une semaine double : le champ littéraire (qui gagne la place en 1830 ?) et la technique du vers, base de l'écrit de commentaire. Vérifier que les fiches de René sont déposées."),
"objectifs": N("5 min", "Insister sur la paire 1 de la liste A.1 : Lamartine (Méditations poétiques) ou René Vivien (semaine 7). Ceux qui choisissent Lamartine commencent la lecture intégrale cette semaine.",
  piege="Le compte des syllabes est souvent nouveau pour des italianistes : rassurer, on y va pas à pas."),
"seances": N("3 min", "A : le champ et Hernani. B : Le Lac, en entier, avec la scansion. C : Mateo Falcone, labo IA, jeu d'Hernani."),
"enigme": N("10 min",
  "Raconter la première du 25 février 1830 : claque romantique placée tôt dans la salle, cheveux longs, Gautier en rouge, sifflets des classiques. Hugo a 28 ans.",
  questions="Qu'est-ce qui pouvait choquer dans une pièce de théâtre ?",
  attendus="Le premier vers coupé par un enjambement (l'escalier / Dérobé), le mélange des registres, un héros bandit, les unités non respectées.",
  piege="Le gilet rouge est la version de la légende ; dans son Histoire du romantisme, Gautier parle d'un pourpoint rose ou cerise."),
"frise": N("10 min",
  "Lire la frise comme une conquête : préface (1827), victoire (1830), puis malaise de la génération suivante (Musset, 1836). Ajouter oralement Stendhal, Racine et Shakespeare (1823-1825).",
  questions="Pourquoi 1830 est-elle une date doublement révolutionnaire ?",
  attendus="Hernani en février et la révolution de Juillet (27-29 juillet) : rupture esthétique et rupture politique la même année.",
  plus="P. Bénichou, Le Sacre de l'écrivain (1973) : comment l'écrivain devient une autorité spirituelle laïque."),
"auteurs": N("20 min",
  "Une idée par auteur. Lamartine : succès immense des Méditations, puis homme politique (ministre des Affaires étrangères en 1848). Hugo : chef de file, puis exil de 1851 à 1870. Vigny : Chatterton (1835), le poète sacrifié par la société. Musset : Lorenzaccio (1834), La Confession (1836).",
  questions="Quelle position chacun occupe-t-il : chef, solitaire, héritier, rebelle ?"),
"outil": N("25 min",
  "Dessiner au tableau deux axes : installés contre nouveaux venus, consécration institutionnelle contre reconnaissance des pairs. Placer l'Académie, les classiques, Hugo, Lamartine, Musset, Vigny. Une prise de position (préface, pièce, manifeste) déplace un acteur sur la carte.",
  questions="Hernani est-il seulement une pièce ?",
  attendus="C'est un coup dans un jeu : une génération prend position contre une autre.",
  piege="Le champ n'est pas un simple milieu : c'est un espace de luttes pour la définition de la bonne littérature.",
  source="P. Bourdieu, Les Règles de l'art, Seuil, 1992."),
"texte1": N("60 min, séance B",
  "Lecture expressive (3 lecteurs), puis scansion au tableau : Ô / temps / sus / pends / ton / vol // et / vous / heu / res / pro / pi(ces) = 12. Le e de heures se prononce devant consonne ; le e final de propices ne compte pas. Suspendez votre cours = 6. Rimes croisées : propices / délices (féminines), cours / jours (masculines). Contexte : souvenir de Julie Charles au lac du Bourget (1816-1817), l'Elvire du poème.",
  questions="Que mime l'alternance 12 / 6 ? Qui parle dans cette strophe ?",
  attendus="Le vers court suspend le mouvement, comme le poète voudrait suspendre le temps. Dans le poème, c'est la voix de la femme aimée, rapportée par le poète.",
  piege="Erreur fréquente : compter le e final des rimes féminines.",
  plus="Faire traduire la strophe en italien en gardant l'alternance long / court."),
"texte2": N("20 min, séance A",
  "Lire la phrase, puis expliquer la Préface de Cromwell : contre les règles et les unités, pour le drame qui mêle le grotesque et le sublime. La phrase suivante de la préface demande d'abattre le vieux plâtre qui masque la façade de l'art.",
  questions="Qui est visé par le marteau ?",
  attendus="Les règles classiques, Boileau, les théoriciens et l'Académie.",
  plus="Comparer avec un manifeste italien connu des étudiants (Berchet, Lettera semiseria, 1816)."),
"methode": N("30 min", "Scansion collective du premier vers du Lac : Ain-si / tou-jours / pous-sés // vers / de / nou-veaux / ri-va(ges) = 12. Distribuer la fiche de versification (Studium).",
  piege="Diérèse et synérèse dépendent souvent de l'étymologie (li-on, mais pied). Donner trois exemples seulement."),
"nouvelle": N("30 min, séance C",
  "Mateo Falcone paraît dans la Revue de Paris en mai 1829, puis dans Mosaïque (1833). Faire lire la fin : un père exécute son fils au nom de l'honneur. Style sec, narrateur extérieur.",
  questions="Mérimée connaissait-il la Corse quand il a écrit ce récit ?",
  attendus="Non : il n'y va qu'en 1839, comme inspecteur des monuments historiques, avant d'écrire Colomba (1840). Sa Corse de 1829 est une Corse imaginée depuis Paris : excellent point sociocritique.",
  piege="Ne pas lire le récit comme un document ethnographique."),
"labo": N("30 min", "Faire scander par l'IA une strophe du Lac, puis recompter. Chaque groupe note la règle que l'IA a oubliée.",
  piege="Erreurs typiques de l'IA : e muet final compté, diérèses oubliées, césure mal placée. C'est le meilleur exercice pour vérifier ses propres connaissances."),
"italia": N("15 min",
  "Manzoni écrit en français la Lettre à M. Chauvet (rédigée en 1820, publiée en 1823) contre les unités de temps et de lieu. Verdi crée Ernani à La Fenice le 9 mars 1844.",
  questions="Comment compte-t-on un endecasillabo ? Un alexandrin ?",
  attendus="L'endecasillabo se définit par sa dernière syllabe accentuée en dixième position ; l'alexandrin compte douze syllabes, le e final des rimes féminines exclu."),
"bilan": N("10 min", "Jeu d'Hernani si le temps le permet (sinon en début de semaine 3). Rappeler la scansion corrigée à déposer et la lecture de la dernière page du Père Goriot."),
}

NOTES[3] = {
"cover": N("3 min", "Fil de la semaine : le roman devient une marchandise de presse et veut pourtant dire la vérité de la société."),
"objectifs": N("5 min", "L'objectif clé est la problématique : sans elle, pas de commentaire écrit. Le fantastique sera repris en semaine 6 avec Villiers."),
"seances": N("3 min", "A : presse et capitaux. B : Stendhal et Balzac, la problématique. C : Gautier, labo IA."),
"enigme": N("15 min",
  "Le 1er juillet 1836, Émile de Girardin lance La Presse (et Dutacq Le Siècle le même jour) : abonnement à 40 francs au lieu de 80, financé par les annonces. Pour garder les abonnés, le roman s'installe en bas de page, en feuilleton. Premier grand essai dans La Presse : La Vieille Fille de Balzac (octobre-novembre 1836).",
  questions="Si le journal est payé par la publicité, que doit faire le roman ?",
  attendus="Retenir le lecteur : suspense, épisodes, fin de chapitre ouverte.",
  source="M.-È. Thérenty et A. Vaillant, 1836. L'An I de l'ère médiatique, Nouveau Monde, 2001."),
"frise": N("10 min",
  "Sainte-Beuve publie De la littérature industrielle dans la Revue des Deux Mondes (1er septembre 1839). Les Mystères de Paris paraissent dans le Journal des débats de juin 1842 à octobre 1843.",
  questions="Pourquoi Sainte-Beuve s'inquiète-t-il ?",
  attendus="Il craint que la logique du marché remplace celle de l'art."),
"auteurs": N("20 min",
  "Stendhal : vit à Milan de 1814 à 1821, puis consul à Civitavecchia. Balzac : imprimeur ruiné en 1828, écrit pour payer ses dettes ; titre La Comédie humaine en 1842. Gautier : le jeune d'Hernani. Sue : le feuilleton qui fait vendre.",
  questions="Lequel de ces écrivains vit de sa plume ?"),
"outil": N("20 min",
  "Faire classer Rastignac, Goriot et Vautrin selon les trois capitaux, en 10 minutes. Rastignac arrive avec un peu de capital culturel (le droit) et presque rien d'autre ; il apprend à convertir le capital social (Mme de Beauséant, Delphine) en position.",
  piege="Ne pas transformer Bourdieu en grille mécanique : l'intérêt est la conversion d'un capital en un autre."),
"texte1": N("30 min, séance A",
  "La phrase vient du livre II, chapitre 19 : le romancier se défend contre l'accusation d'immoralité. La suite oppose l'azur des cieux et la fange des bourbiers. Stendhal avait déjà placé au chapitre 13 du livre I une épigraphe sur le miroir, attribuée à Saint-Réal, très probablement inventée.",
  questions="Si le miroir montre la boue, qui est coupable ?",
  attendus="La route (la société), pas le miroir (le roman).",
  plus="Stendhal attribue des épigraphes à de faux auteurs : une fausse attribution au XIXe siècle, bon lien avec la vérification des sources en labo IA."),
"texte2": N("30 min, séance B",
  "Après l'enterrement de Goriot au Père-Lachaise, Rastignac regarde Paris, entre la colonne de la place Vendôme et le dôme des Invalides, lance son défi, puis part dîner chez Mme de Nucingen. Projeter une carte de Paris.",
  questions="Quel est le premier acte de Rastignac après son défi ?",
  attendus="Aller dîner chez Delphine de Nucingen, fille de Goriot : il entre dans le jeu social qu'il vient de juger."),
"methode": N("40 min", "Trois problématiques par groupe, puis classement : trop large, trop étroite, juste. Exemple juste : En quoi cette dernière page transforme-t-elle un deuil en déclaration de guerre sociale ?"),
"nouvelle": N("30 min, séance C",
  "La Morte amoureuse paraît dans la Chronique de Paris, la revue de Balzac, les 23 et 26 juin 1836. Le prêtre Romuald raconte sa double vie avec la courtisane Clarimonde ; l'abbé Sérapion ouvre la tombe.",
  questions="Peut-on choisir entre rêve et réalité à la fin ?",
  attendus="Non : c'est l'hésitation qui définit le fantastique.",
  source="T. Todorov, Introduction à la littérature fantastique, Seuil, 1970."),
"labo": N("30 min", "Faire produire cinq problématiques par l'IA, puis les trier.",
  piege="L'IA propose souvent des problématiques générales ou invente un détail du texte (un personnage présent, une réplique). Faire vérifier chaque détail dans la page."),
"italia": N("15 min",
  "Épitaphe de Stendhal au cimetière de Montmartre : Arrigo Beyle Milanese, scrisse, amò, visse. Manzoni révise I promessi sposi pour l'édition de 1840-1842 en toscan de Florence (la célèbre risciacquatura in Arno).",
  questions="Pourquoi un Français se veut-il milanais ?"),
"bilan": N("10 min", "Annoncer la semaine 4 et le premier texte A.1 en prose : Le Spleen de Paris. Distribuer les rôles du tribunal de 1857 (procureur Pinard, avocat Senard, Flaubert, Baudelaire, juges)."),
}

NOTES[4] = {
"cover": N("3 min", "Premier texte A.1 en prose. La paire 3 oppose Baudelaire (Le Spleen de Paris) et Gide (Les Nourritures terrestres, semaine 7)."),
"objectifs": N("5 min", "Le plan est l'objectif central pour l'écrit ; le style indirect libre reviendra en semaine 5."),
"seances": N("3 min", "A : procès et autonomie. B : Baudelaire et le plan. C : Flaubert, labo, tribunal."),
"enigme": N("10 min",
  "Flaubert est jugé du 29 au 31 janvier 1857 et acquitté le 7 février ; le procureur Ernest Pinard requiert aussi contre Baudelaire, condamné le 20 août à une amende et à la suppression de six poèmes. La condamnation de Baudelaire n'est annulée qu'en 1949.",
  questions="Qu'est-ce que l'État reproche à un roman ?",
  attendus="Outrage à la morale publique et religieuse : on juge une conception de l'art qui refuse de moraliser.",
  piege="En 1857, pas de jury : un tribunal correctionnel. Les jurés du jeu sont fictifs."),
"frise": N("10 min", "Montrer que la doctrine (Gautier, 1835) précède le conflit avec le régime (1852-1857). Le Spleen de Paris paraît deux ans après la mort de Baudelaire."),
"auteurs": N("20 min", "Flaubert et Baudelaire naissent en 1821. Baudelaire dédie Les Fleurs du mal à Gautier, le gilet rouge de 1830 devenu un maître. Leconte de Lisle : Poèmes antiques (1852).",
  questions="Que montre la dédicace à Gautier ?",
  attendus="Une filiation choisie : l'art pour l'art contre la morale bourgeoise."),
"outil": N("20 min",
  "Expliquer simplement l'économie à l'envers : dans un champ autonome, l'échec commercial ou judiciaire peut devenir un signe de valeur. Exemple : Baudelaire condamné, aujourd'hui au programme.",
  piege="Ne pas idéaliser : l'autonomie se conquiert aussi grâce à des revenus (Flaubert vit de rentes).",
  source="P. Bourdieu, Les Règles de l'art, 1992, première partie."),
"texte1": N("45 min, séance B",
  "L'Étranger ouvre Le Spleen de Paris. Lire à deux voix. Dans la dédicace à Arsène Houssaye, Baudelaire rêve d'une prose poétique, musicale sans rythme et sans rime, et cite Aloysius Bertrand (Gaspard de la nuit, 1842) comme modèle.",
  questions="Que reste-t-il à l'étranger ? Quel mot clôt le poème ?",
  attendus="Les nuages, les merveilleux nuages : un idéal mobile, insaisissable.",
  piege="Ne pas paraphraser le dialogue : analyser la gradation des refus (famille, amis, patrie, beauté, or)."),
"texte2": N("30 min, séance B", "Faire relever les trois ivresses : de vin, de poésie ou de vertu. Le poème refuse de choisir entre morale et plaisir : c'est l'intensité qui compte, pas l'objet.",
  questions="Quel plan pour ce poème ?",
  attendus="I. Une injonction universelle. II. Une ivresse qui échappe à la morale (vin, poésie, vertu)."),
"methode": N("45 min", "Comparer les plans au tableau : axe thématique ou axe formel ? Les deux sont possibles si la problématique les relie. Chaque axe annonce une idée, pas un procédé."),
"nouvelle": N("30 min, séance C",
  "Un cœur simple est écrit en 1876 et paraît dans Trois Contes (1877). Flaubert emprunte un perroquet empaillé au muséum de Rouen pour écrire. Faire entendre le style indirect libre sur une page du chapitre IV.",
  questions="Pourquoi Félicité confond-elle Loulou et le Saint-Esprit ?",
  attendus="Sa foi est concrète et affective ; le texte la montre sans la ridiculiser.",
  piege="Le débat ironie ou tendresse n'a pas de réponse unique : accepter les deux lectures si elles sont argumentées."),
"labo": N("25 min",
  "La phrase Madame Bovary, c'est moi n'apparaît dans aucun écrit de Flaubert : elle est rapportée tardivement (par René Descharmes, d'après Amélie Bosquet). Bon test d'hallucination.",
  questions="L'IA donne-t-elle une source ? Laquelle ?",
  piege="Valoriser l'étudiant qui trouve la vraie source, et celui qui montre que l'IA invente une lettre ou une date."),
"italia": N("15 min", "La Scapigliatura milanaise (Praga, Boito) lit Baudelaire dans les années 1860. Verga retient de Flaubert l'impersonnalité du récit.",
  questions="Le jeu : notre verdict correspond-il au verdict réel ?"),
"bilan": N("10 min", "Prévenir : la séance B de la semaine 5 est un atelier de commentaire de 2 heures, sans note, avec retour écrit."),
}
