# Notes de l'enseignant, semaines 5 à 8 (version du 6 octobre 2026).
from notes_lib import N

STAL = "Y. Stalloni, Écoles et courants littéraires, Armand Colin, 3e éd., 2015, chap. « Le dix-neuvième siècle »"
BAIN = "J. Bainville, Au seuil du siècle. Études critiques, Éditions du Capitole, 1927 (Wikisource)"

NOTES = {}

# =====================================================================  S5
NOTES[5] = {
"cover": N("3 min",
  "Semaine centrale pour la partie B de la fiche : quatre auteurs de la liste et les deux recueils à lire en entier. Premier atelier de commentaire en séance B. Deux lectures critiques : Stalloni (histoire de l'école naturaliste) et Bainville (un adversaire juge Zola en 1902).",
  essentiel="Après la défaite contre la Prusse (1870) et la Commune (1871), la Troisième République s'installe ; l'école devient gratuite et obligatoire (lois Ferry, 1881-1882) ; la loi du 29 juillet 1881 libère la presse. Les journaux se multiplient et publient chaque jour des nouvelles : c'est l'âge d'or du genre. Le naturalisme, autour de Zola, veut appliquer au roman la méthode des sciences (observation, document, hérédité, milieu). Maupassant est le maître de la nouvelle ; Barbey d'Aurevilly et Daudet écrivent des récits brefs hors de l'école.",
  qr=[("Pourquoi la nouvelle triomphe-t-elle après 1870 ?",
       "Parce que la presse libre et bon marché a besoin de textes courts chaque jour (Gil Blas, Le Gaulois), et que les écrivains en vivent : Maupassant publie environ trois cents nouvelles en dix ans.")]),

"objectifs": N("5 min",
  "Nouveau savoir-faire : lire un recueil comme un ensemble. La fiche demande Les Diaboliques et Les Soirées de Médan en édition intégrale.",
  qr=[("Pourquoi lire un recueil en entier, et pas une seule nouvelle ?",
       "Parce que le recueil a un cadre, un ordre et des échos entre les récits : son sens n'est pas la somme des nouvelles. Les Soirées de Médan sont un manifeste collectif ; Les Diaboliques forment une galerie de six femmes.")],
  piege="Les étudiants lisent souvent une seule nouvelle par recueil : montrer pourquoi le cadre et l'ordre comptent."),

"seances": N("3 min",
  "A : Médan, le recueil, les deux lectures critiques. B : atelier de 2 h. C : Barbey, Le Horla, Daudet, labo IA.",
  qr=[("Pourquoi un atelier sans note ?",
       "Parce que l'enseignant ne fait pas passer l'examen : l'atelier sert à s'entraîner et à recevoir un retour écrit précis, sans enjeu de note. Les étudiants osent davantage.")]),

"enigme": N("10 min",
  "Lire la question, puis présenter Médan : la maison de campagne de Zola, achetée en 1878 au bord de la Seine. Six écrivains, six nouvelles sur la guerre de 1870, publiées chez Charpentier en avril 1880.",
  essentiel="Les six nouvelles de Médan : L'Attaque du moulin (Zola), Boule de suif (Maupassant), Sac au dos (Huysmans), La Saignée (Céard), L'Affaire du grand 7 (Hennique), Après la bataille (Alexis). Toutes refusent l'héroïsme patriotique : la guerre montre la lâcheté, l'égoïsme et l'hypocrisie de la société.",
  qr=[("Comment raconter la défaite de 1870 en quelques pages ?",
       "En choisissant un épisode limité (une diligence, un moulin, un hôpital) qui révèle toute la société : c'est la force de la nouvelle. Les auteurs de Médan ne racontent pas des batailles, mais des comportements."),
      ("Pourquoi raconter une défaite plutôt qu'une victoire ?",
       "Pour refuser l'héroïsme officiel et la littérature patriotique de revanche ; la défaite révèle la société (lâcheté bourgeoise, hypocrisie morale)."),
      ("Que veut dire Pendant plusieurs jours de suite… ?",
       "C'est le début de Boule de suif : le récit commence après la débâcle, comme si la guerre était déjà perdue et qu'il ne restait que la société.")]),

"frise": N("10 min",
  "Lire la frise et relier les saisies à la semaine 4.",
  essentiel="La Dernière Classe paraît dans le journal L'Événement en 1872, puis dans les Contes du lundi (1873). Les Diaboliques (Dentu, novembre 1874) sont saisies quelques semaines après leur parution ; Barbey évite le procès en acceptant le retrait des exemplaires. Germinal paraît d'abord en feuilleton dans le Gil Blas (1884-1885). Le Horla, première version en 1886 (Gil Blas), seconde version, en journal intime, en 1887.",
  qr=[("Quel lien entre ces saisies et la semaine 4 ?",
       "La justice continue de juger la littérature au nom des mœurs, même sous la République : l'autonomie du champ n'est jamais acquise."),
      ("Pourquoi 1870 est-il en bleu ?",
       "C'est un événement politique qui change le champ littéraire : la défaite et la Commune deviennent des sujets, et la République transforme la presse et l'école.")]),

"auteurs": N("20 min",
  "Une idée par auteur, puis la question de l'école : qui est dedans, qui est dehors ?",
  essentiel="Zola (1840-1902) : fils d'un ingénieur italien (François Zola, né à Venise) et d'une mère française, élevé à Aix-en-Provence ; employé chez l'éditeur Hachette, journaliste, chef de l'école naturaliste avec Les Rougon-Macquart (20 romans, 1871-1893) ; en 1898, il publie J'accuse… ! dans L'Aurore (13 janvier) pour défendre le capitaine Dreyfus. Maupassant (1850-1893) : disciple de Flaubert, environ 300 nouvelles et 6 romans en une dizaine d'années, publiés d'abord dans Gil Blas et Le Gaulois. Daudet (1840-1897) : né à Nîmes, Lettres de mon moulin (1869), Contes du lundi (1873), romans de mœurs ; ami de Mistral. Barbey d'Aurevilly (1808-1889) : Normand, catholique, dandy (Du dandysme et de George Brummell, 1845), critique redouté, surnommé le connétable des lettres.",
  qr=[("Qui appartient à l'école naturaliste, qui reste en dehors ?",
       "Zola et Maupassant sont dedans (Médan). Daudet est proche, ami de Zola, mais indépendant. Barbey est franchement hostile : il méprise le naturalisme et la démocratie."),
      ("Pourquoi Maupassant se dit-il disciple de Flaubert plutôt que de Zola ?",
       "Flaubert, ami de sa mère, lui a appris le travail du style ; Maupassant refuse les prétentions scientifiques de Zola et parle d'illusion du vrai (préface de Pierre et Jean, 1888).")],
  citations=[("Les Réalistes de talent devraient s'appeler plutôt des Illusionnistes.","Maupassant, « Le Roman », préface de Pierre et Jean, 1888, cité par Stalloni")]),

"outil": N("25 min",
  "Faire remplir un tableau à trois colonnes pour chaque recueil : cadre, échos, position.",
  qr=[("Cadre : qui réunit les récits ?",
       "Médan : un lieu et des soirées (le titre fait croire que les nouvelles ont été racontées chez Zola, ce qui est une fiction publicitaire). Les Diaboliques : pas de cadre unique, mais six narrateurs de salon qui racontent à voix basse."),
      ("Échos : quels thèmes reviennent ?",
       "Médan : la guerre de 1870, la lâcheté, le corps, l'argent. Les Diaboliques : la passion, le crime caché, le secret, la femme fatale, le catholicisme."),
      ("Position : un recueil collectif est-il un manifeste ?",
       "Oui : Les Soirées de Médan proclament l'existence d'un groupe autour de Zola, avec un sujet commun et une esthétique commune. Barbey, lui, signe seul un recueil contre son époque."),
      ("Pourquoi les Diaboliques sont-elles diaboliques ?",
       "Parce que ce sont six histoires de femmes criminelles ou dévorées de passion, racontées par un catholique qui croit au mal : Barbey dit que le diable est le vrai sujet.")],
  piege="Un recueil n'est pas une simple addition : l'ordre des textes construit un sens."),

"critique-stalloni-naturalisme": N("20 min, séance A",
  "Présenter les trois phases sur la frise de la diapositive suivante. Lire la formule de Zola (le tempérament) et le télégramme d'Alexis (moment comique, qui montre une école en difficulté). Puis la question du débat.",
  essentiel="Stalloni situe l'école naturaliste entre 1865 (Germinie Lacerteux des Goncourt) et 1891 (Enquête sur l'évolution littéraire de Jules Huret dans L'Écho de Paris, où la plupart des écrivains déclarent le naturalisme mort). Il suit trois phases (d'après Colette Becker). Formation (1865-1876) : Zola se fait connaître par un recueil de critiques, Mes Haines (1866), et Thérèse Raquin (1867). Âge d'or (1876-1884) : L'Assommoir (1877), le dîner chez Trapp le 16 avril 1877 (les jeunes Huysmans, Céard, Hennique, Alexis, Mirbeau, Maupassant invitent Flaubert, Goncourt et Zola), Les Soirées de Médan et Le Roman expérimental (1880), où Zola applique à la littérature la médecine expérimentale de Claude Bernard. Éclatement (1884-1893) : Huysmans quitte l'école avec À rebours (1884) ; en 1887, cinq jeunes écrivains publient dans Le Figaro le Manifeste des Cinq contre La Terre. Stalloni consacre aussi une section au Félibrige : le mouvement fondé en 1854 par Frédéric Mistral et six poètes pour faire revivre la langue provençale ; Mireille (1859) ; prix Nobel de Mistral en 1904. Daudet en est proche.",
  qr=[("Une école qui se dit scientifique peut-elle échapper aux luttes de groupes ?",
       "Non : l'histoire racontée par Stalloni est celle d'un groupe, avec un dîner fondateur, un recueil collectif, des manifestes, des ruptures et une enquête de presse qui l'enterre. La science sert de légitimité, mais l'école vit comme toutes les écoles, par des alliances et des conflits."),
      ("Que reproche le Manifeste des Cinq à Zola ?",
       "D'être descendu au fond de l'immondice avec La Terre, de chercher le scandale et la vente : ce sont des disciples qui se séparent publiquement du maître."),
      ("Pourquoi parler du Félibrige dans un cours de littérature française ?",
       "Parce qu'il montre une autre bataille : celle d'une langue régionale (le provençal) contre la centralisation de la langue nationale. Stalloni rappelle que les manuels l'oublient souvent. Pour des étudiants siciliens, le parallèle avec la littérature en dialecte est direct (voir le pont italien)."),
      ("Que veut dire un coin de la création vu à travers un tempérament ?",
       "Qu'une œuvre n'est pas une photographie : elle montre une partie du réel (un coin) à travers la personnalité de l'artiste (le tempérament). Même le naturalisme reconnaît le rôle de l'auteur.")],
  citations=[("Le romancier expérimental n'est qu'un savant spécial qui emploie l'outil des autres savants, l'observation et l'analyse.","Zola, Le Roman expérimental, 1880, cité par Stalloni"),
             ("Le public aime les romans faux : ce roman est un roman vrai.","Goncourt, préface de Germinie Lacerteux, 1865, citée par Stalloni")],
  piege="Le manuel date Jack de Daudet de 1896 : c'est 1876. Le signaler en passant.",
  source=f"{STAL}, sections « Le Naturalisme » et « Le Félibrige »."),

"critique-stalloni-naturalisme-frise": N("10 min",
  "Lire la frise comme la vie d'un groupe : naissance (1865), fête (1877), œuvre collective (1880), départ d'un membre (1884), révolte des disciples (1887), enterrement par la presse (1891).",
  qr=[("Qu'est-ce que le dîner Trapp ?",
       "Un dîner au restaurant Trapp, à Paris, le 16 avril 1877, offert par six jeunes écrivains à Flaubert, Edmond de Goncourt et Zola ; la presse y voit la naissance officielle de l'école naturaliste."),
      ("Que dit l'enquête de Huret en 1891 ?",
       "Interrogés par le journaliste Jules Huret, la plupart des écrivains déclarent le naturalisme fini et parlent de psychologues et de symbolistes. Paul Alexis répond par télégramme : Naturalisme pas mort. Lettre suit.")]),

"critique-bainville-zola": N("25 min, séance A ou C",
  "Présenter l'auteur et la date avant de lire. Lire les deux citations de la diapositive. Puis lire en classe deux passages de l'article (Wikisource) : l'éloge de Flaubert et d'Un cœur simple, et la phrase sur le certificat d'études. Signaler, sans le lire à voix haute, le passage raciste sur les origines italiennes de Zola : le décrire comme un fait et l'analyser. Conclure avec la question du débat.",
  essentiel="Jacques Bainville (1879-1936) est un journaliste et historien, proche de Charles Maurras et de l'Action française (mouvement nationaliste, antidreyfusard, puis royaliste) ; il entrera à l'Académie française en 1935. En 1927, René Groos réunit ses articles de jeunesse (1900-1913) sous le titre Au seuil du siècle. Dans l'avant-propos, Bainville reconnaît beaucoup de naïve impertinence dans ces pages. L'article L'école naturaliste est daté du 4 octobre 1902, cinq jours après la mort de Zola (asphyxié chez lui le 29 septembre 1902), en pleine affaire Dreyfus. Le texte fait un tri : Flaubert (un artiste et un aristocrate), les Goncourt, Daudet, Maupassant sont des gentilshommes ; Zola seul est peuple. Les armes du critique sont le mépris de classe (le certificat d'études primaires, le mariage avec la fille d'une débitante de vins), le vocabulaire de la maladie (Charcot soignait de tels malades) et un racisme explicite contre l'ascendance italienne et grecque de Zola, présenté comme un métis. Le vrai reproche est politique : Zola est devenu dreyfusard, socialiste et prophète d'une cité future.",
  qr=[("Ce texte nous apprend-il plus sur Zola ou sur la place que Bainville veut occuper dans le champ ?",
       "Sur Bainville. Il ne dit rien de précis sur les romans de Zola ; il construit un camp (les gentilshommes du naturalisme, l'art, la tradition) contre un ennemi (Zola, le peuple, la République dreyfusarde). C'est une prise de position d'un jeune critique de 23 ans qui veut se faire un nom dans la presse de droite."),
      ("Pourquoi Bainville fait-il l'éloge de Flaubert et de Daudet ?",
       "Pour isoler Zola : en sauvant les autres naturalistes, il présente Zola comme une exception vulgaire et non comme le chef de l'école. Daudet est d'ailleurs le père de Léon Daudet, l'un des chefs de l'Action française (voir l'article Un père et un fils)."),
      ("Quels sont les procédés de dévalorisation ?",
       "Le mépris social (certificat d'études, cours du soir, commis de librairie), la pathologie (malade, besoin de souiller), l'animalisation (comparaison avec un verrat), le racisme (sang mêlé, métis). Ce sont des procédés de pamphlet, pas d'analyse littéraire."),
      ("Que dit la phrase de 1927 Ce qui est écrit pour un jour devrait périr avec le jour ?",
       "Que la critique de presse est un genre éphémère, lié à l'actualité. Paradoxe : Bainville republie quand même ses articles en 1927, quand il est devenu célèbre ; le livre sert sa propre consécration."),
      ("Pourquoi lire en classe un texte raciste ?",
       "Pour comprendre comment la valeur littéraire se fabrique aussi par des combats politiques, et pour apprendre à reconnaître ces procédés. On le lit comme un document d'époque, avec distance, sans le reprendre à son compte.")],
  citations=[("Flaubert, les Goncourt, Daudet ni Maupassant n'auraient voulu de cette fin-là.","Bainville, 4 octobre 1902, dernière phrase"),
             ("Il s'est seulement appliqué à proportionner la valeur et le nombre des mots qu'il employait à l'importance de la matière.","Bainville sur Flaubert et Un cœur simple, 1902")],
  piege="Le passage sur les origines italiennes de Zola est directement raciste. Devant un public italien, le nommer clairement comme tel, rappeler que le père de Zola était un ingénieur vénitien respecté (le canal Zola à Aix porte son nom), et ne pas en faire un sujet de débat sur la valeur des personnes. Si un étudiant est blessé, le dire en classe : c'est précisément ce que le texte cherche à produire.",
  plus="Christophe Charle, Naissance des « intellectuels » (1990) : l'affaire Dreyfus divise le champ littéraire en deux camps, et le mot intellectuel naît en 1898 comme une insulte des antidreyfusards.",
  source=f"{BAIN}, « L'école naturaliste », 4 octobre 1902 ; avant-propos du 8 septembre 1927."),

"critique-bainville-zola-frise": N("10 min",
  "Lire la frise : la valeur de Zola se décide aussi dans la presse, les ligues, les tribunaux et les cérémonies.",
  qr=[("Qui a gagné le procès de la postérité ?",
       "Zola : Dreyfus est réhabilité en 1906, et les cendres de Zola entrent au Panthéon en juin 1908. Bainville sera élu à l'Académie française en 1935 : chacun reçoit sa consécration, mais pas du même côté du champ."),
      ("Pourquoi 1927 compte-t-il ?",
       "Bainville réédite ses articles en pleines Années folles (semaine 8) : un critique consacré relit sa jeunesse et transforme des articles d'un jour en livre.")]),

"texte1": N("30 min, séance A",
  "Lecture de la première phrase, puis présentation de toute la nouvelle.",
  essentiel="Boule de suif : pendant l'hiver 1870-1871, à Rouen occupé par les Prussiens, dix voyageurs prennent la diligence pour Le Havre : un marchand de vin et sa femme (les Loiseau), un industriel et sa femme (les Carré-Lamadon), un comte et une comtesse (les Bréville), deux religieuses, un démocrate (Cornudet) et une prostituée surnommée Boule de suif. Bloqués à l'auberge de Tôtes, ils dépendent d'un officier prussien qui exige de passer la nuit avec elle ; la société respectable la pousse à céder, puis la méprise dans la diligence. Flaubert, qui meurt quelques semaines après la parution, la salue comme un chef-d'œuvre.",
  qr=[("Image : lambeaux d'armée, quelle image de la défaite ?",
       "Une armée déchiquetée, réduite à des morceaux de tissu : plus de troupes, plus d'ordre, plus de gloire."),
      ("Temps : plus-que-parfait, pourquoi commencer après les faits ?",
       "Le récit commence après la débâcle : la guerre est déjà perdue, il ne reste que la société, et c'est elle que la nouvelle va juger."),
      ("Recueil : que partagent les six nouvelles de Médan ?",
       "La guerre de 1870, le refus de l'héroïsme, la peinture critique de la société."),
      ("Que dit la diligence de la société ?",
       "C'est un modèle réduit de la France de 1870 : noblesse, grande bourgeoisie, commerce, Église, républicain, prostituée. La plus méprisée est la seule généreuse.")],
  citations=[("Pendant plusieurs jours de suite des lambeaux d'armée en déroute avaient traversé la ville.","Maupassant, Boule de suif, première phrase"),
             ("Et Boule de suif pleurait toujours ; et parfois un sanglot, qu'elle n'avait pu retenir, passait, entre deux couplets, dans les ténèbres.","dernière phrase (les couplets de La Marseillaise sifflée par Cornudet)")],
  plus="Sociocritique : faire repérer qui mange les provisions de Boule de suif au début, et qui ne partage rien à la fin."),

"texte2": N("30 min, séance C",
  "Lire la première phrase, puis raconter le cadre et l'histoire.",
  essentiel="Le Rideau cramoisi ouvre Les Diaboliques. Le narrateur voyage de nuit en diligence avec le vicomte de Brassard, un vieux dandy ancien officier. La voiture s'arrête dans une petite ville devant une fenêtre éclairée, derrière un rideau rouge (cramoisi) : Brassard raconte alors ce qui lui est arrivé là, jeune officier. Alberte, la fille silencieuse de ses logeurs, est venue chaque nuit dans sa chambre ; une nuit, elle est morte dans ses bras ; il a fui sans jamais savoir de quoi. La fin laisse le mystère entier.",
  qr=[("Voix : qui raconte ? À qui ?",
       "Deux narrateurs : un premier narrateur anonyme, et le vicomte de Brassard qui lui raconte son aventure de jeunesse, de nuit, dans la diligence. C'est un récit enchâssé."),
      ("Adverbe : terriblement d'années, quel effet ?",
       "Une expression incorrecte et expressive : l'adverbe d'intensité remplace beaucoup et colore déjà le récit de terreur. Le temps lui-même devient effrayant."),
      ("Cadre : une histoire racontée de nuit, en voiture, pourquoi ?",
       "La nuit, l'arrêt forcé et le rideau éclairé créent le mystère et justifient la confidence : on raconte ce qu'on ne dit pas le jour. Le cadre transmet le secret oralement, sans le résoudre."),
      ("Pourquoi Barbey multiplie-t-il les narrateurs ?",
       "Le mystère se transmet oralement ; personne ne sait tout ; l'horreur reste voilée.")],
  citations=[("Il y a terriblement d'années, je m'en allais chasser le gibier d'eau dans les marais de l'Ouest…","Barbey d'Aurevilly, Le Rideau cramoisi, 1874, première phrase")]),

"methode": N("2 h, séance B",
  "Atelier non noté : une introduction sur Boule de suif ou Le Horla (au choix), puis une première partie si le temps le permet. Corriger avec la grille du cours. Retour écrit pour la semaine 6.",
  essentiel="L'introduction a quatre temps. 1. Amorce : situer l'auteur, l'œuvre, le mouvement, la date. 2. Présentation du passage (où il se place, de quoi il parle). 3. Problématique. 4. Annonce du plan, en une phrase. Elle tient en un paragraphe de 8 à 12 lignes.",
  qr=[("Donner un exemple d'introduction pour le début de Boule de suif.",
       "En 1880, Maupassant publie Boule de suif dans Les Soirées de Médan, recueil collectif où six écrivains réunis autour de Zola racontent la guerre de 1870 sans héroïsme. Le début de la nouvelle montre Rouen au moment où l'armée française vaincue traverse la ville et où les Prussiens arrivent. Comment ce tableau de la débâcle prépare-t-il la critique d'une société plus soucieuse de ses biens que de la patrie ? Nous verrons d'abord une défaite sans gloire, puis une bourgeoisie qui se protège."),
      ("Quels critères pour corriger ?",
       "Amorce précise (auteur, œuvre, date, mouvement), passage situé, problématique qui est une vraie question, plan annoncé clairement, langue correcte.")],
  piege="Les amorces trop générales (Depuis toujours…, De tout temps…) : exiger auteur, œuvre, date, mouvement dès la première phrase."),

"nouvelle": N("30 min, séance C",
  "Le Horla : lire les premières lignes et la dernière, raconter la progression. La Dernière Classe : la lire en entier à voix haute (dix minutes).",
  essentiel="Le Horla existe en deux versions : 1886 (un malade raconte son histoire à des médecins) et 1887 (journal intime). Dans la seconde, le narrateur, qui vit au bord de la Seine près de Rouen, salue le 8 mai un trois-mâts brésilien ; ensuite il sent une présence invisible qui boit son eau et son lait, le domine, et qu'il appelle le Horla ; il finit par brûler sa maison, avec ses domestiques, pour le détruire, et envisage de se tuer. La Dernière Classe (1872) : en Alsace annexée par la Prusse, le petit Franz arrive en retard à l'école ; M. Hamel donne son dernier cours de français, l'ordre étant venu de Berlin de n'enseigner que l'allemand ; il écrit au tableau VIVE LA FRANCE !",
  qr=[("Journal : pourquoi un journal intime pour Le Horla ?",
       "Un seul témoin, aucun contrôle extérieur : le lecteur ne peut pas vérifier si le narrateur est fou ou lucide. Les dates donnent une impression de vérité et montrent la progression de l'angoisse."),
      ("Fantastique : folie ou présence ?",
       "Le texte ne tranche pas : indices de folie (insomnies, hallucinations, incendie meurtrier) et indices d'une présence réelle (l'eau bue, la rose cueillie). L'hésitation demeure jusqu'à la dernière phrase."),
      ("Daudet : que dit La Dernière Classe de la langue ?",
       "Que la langue est la patrie et la liberté : tant qu'un peuple garde sa langue, il garde la clef de sa prison. La nouvelle fait de l'école et du français un symbole national."),
      ("Que tait La Dernière Classe ?",
       "Que la plupart des élèves alsaciens parlaient surtout un dialecte germanique (l'alsacien) : le récit construit une Alsace entièrement francophone qui sert la mémoire nationale de la revanche. Bel exercice sociocritique.")],
  citations=[("8 mai. — Quelle journée admirable !","Maupassant, Le Horla, 1887, première entrée"),
             ("Alors… alors… il va donc falloir que je me tue, moi !…","dernière phrase"),
             ("Quand un peuple tombe esclave, tant qu'il tient bien sa langue, c'est comme s'il tenait la clef de sa prison.","Daudet, La Dernière Classe, M. Hamel")],
  piege="Ne pas moquer le patriotisme de Daudet : l'analyser comme une prise de position de 1872, au moment de l'annexion."),

"labo": N("30 min",
  "Chaque étudiant dépose son introduction dans l'Atelier commentaire ; comparer le retour de l'IA et le retour de l'enseignant sur la même introduction.",
  qr=[("Où l'IA et l'enseignant sont-ils d'accord ?",
       "Souvent sur la structure (présence des quatre temps) et la langue. Les désaccords portent sur la précision de l'amorce et la qualité de la problématique."),
      ("Quels sont les défauts typiques du retour de l'IA ?",
       "Trop général (bonne introduction, à approfondir), trop indulgent, parfois faux sur les faits (date de Boule de suif, auteur de Médan). Faire repérer un conseil juste et un conseil vide.")],
  piege="L'IA est souvent trop générale ou trop indulgente : la confronter au retour humain."),

"italia": N("15 min",
  "Verga, Capuana, le verismo, puis le Félibrige et la littérature en sicilien.",
  essentiel="Giovanni Verga, né à Catania en 1840, publie Vita dei campi en 1880, l'année de Médan (Rosso Malpelo, Cavalleria rusticana, La Lupa), puis I Malavoglia en 1881 (une famille de pêcheurs d'Aci Trezza). Luigi Capuana, né à Mineo, théorise le verismo et dédie son roman Giacinta (1879) à Zola. La Casa Verga se visite via Sant'Anna, à Catania. Le Félibrige provençal (Mistral, 1854) a un équivalent sicilien : la poésie et le théâtre en dialecte, de Giovanni Meli à Nino Martoglio, né à Belpasso, près de Catania.",
  qr=[("Quelle différence entre le narrateur de Zola et celui de Verga ?",
       "Zola garde un narrateur savant qui explique (hérédité, milieu) ; Verga laisse parler le chœur du village, avec ses proverbes et sa façon de voir : la parole collective remplace le savant."),
      ("Pourquoi le Félibrige intéresse-t-il des étudiants siciliens ?",
       "Parce qu'il pose la même question qu'en Sicile : peut-on faire de la grande littérature dans une langue régionale, face à une langue nationale qui s'impose par l'école ? Mistral obtient le prix Nobel en 1904 en écrivant en provençal.")]),

"bilan": N("10 min",
  "Semaine lourde en correction : annoncer la date du retour écrit (semaine 6). Rappeler la lecture du Bateau ivre (strophes 1 à 5), du manifeste de Moréas et de Véra.",
  qr=[("Que faut-il déposer ?",
       "L'introduction réécrite (version 2), en tenant compte des deux retours.")]),
}

# =====================================================================  S6
NOTES[6] = {
"cover": N("3 min",
  "Deux textes A.1 : Le Bateau ivre (paire 2, face à Cendrars en semaine 8) et Le Symbolisme de Moréas (paire 4, face à Marinetti en semaine 8).",
  qr=[("Pourquoi parler de poésie en crise ?",
       "Parce que les règles du vers (nombre de syllabes, rime, sujets nobles) sont contestées, que la langue poétique se sépare de la langue commune, et que le public de la poésie se réduit à quelques cercles : Mallarmé parle lui-même d'une crise de vers (1897).")],
  essentiel="Entre 1871 et 1886, la poésie française change de langue. Rimbaud (16-17 ans en 1871) veut que le poète se fasse voyant ; Verlaine cherche la musique ; Mallarmé fait de l'obscurité une exigence ; les jeunes poètes se disent décadents, puis symbolistes (manifeste de Moréas, 1886). Ces poètes publient dans de petites revues pour un public minuscule : la difficulté devient une manière de se distinguer du public bourgeois et de la presse."),

"objectifs": N("5 min",
  "Annoncer que les manifestes seront comparés en semaine 8 : garder ses notes.",
  qr=[("Qu'est-ce qu'un paragraphe d'analyse ?",
       "Un paragraphe qui avance une idée, la prouve par une citation courte intégrée à la phrase, et analyse l'effet du procédé, sans raconter le texte.")],
  piege="Mallarmé peut décourager : un vers ou deux, jamais un poème entier."),

"seances": N("3 min",
  "A : voyants, décadents, symbolistes, lecture critique de Stalloni, Zima. B : Rimbaud et le paragraphe d'analyse. C : Véra, traductions, manifeste express.",
  qr=[("Qu'est-ce que le manifeste express ?",
       "Un jeu d'écriture de 20 minutes : en groupes, inventer une école en -isme et écrire son manifeste en cinq phrases, avec les marques du genre repérées chez Moréas.")]),

"enigme": N("10 min",
  "Lire la question, laisser répondre, puis donner le contexte des petites revues : La Vogue, Le Décadent, Le Symboliste (1886), tirages minuscules, lectures entre poètes.",
  qr=[("Pourquoi des poètes choisissent-ils d'être difficiles ?",
       "Pour refuser le public bourgeois, la presse et la langue de tous ; pour choisir leurs lecteurs ; pour se distinguer et affirmer que la poésie est un art exigeant, pas une marchandise. Au sens de Bourdieu, c'est une stratégie de distinction dans un champ à l'envers."),
      ("Que veut dire De la musique avant toute chose ?",
       "C'est le premier vers de l'Art poétique de Verlaine : la poésie doit d'abord être musique (sons, rythme, vers impairs), avant d'être idée ou description.")],
  citations=[("De la musique avant toute chose, / Et pour cela préfère l'Impair…","Verlaine, Art poétique, 1874 (publié en 1882)"),
             ("Et tout le reste est littérature.","Art poétique, dernier vers")]),

"frise": N("10 min",
  "Lire la frise : quinze ans entre la lettre du Voyant et le manifeste.",
  essentiel="Je est un autre apparaît dans la lettre à Georges Izambard (13 mai 1871) et dans la lettre à Paul Demeny (15 mai 1871), dites lettres du Voyant. Le Bateau ivre est écrit à l'été 1871, avant l'arrivée de Rimbaud à Paris ; il est publié en 1883 dans les articles de Verlaine sur les Poètes maudits (livre en 1884). Les Illuminations paraissent dans La Vogue en 1886, sans que Rimbaud, alors en Afrique, le sache.",
  qr=[("Combien de temps entre l'écriture et la publication du Bateau ivre ?",
       "Douze ans (1871-1883) : la gloire arrive par d'autres poètes (Verlaine), pas par le public."),
      ("Pourquoi le 18 septembre 1886 est-il en bleu ?",
       "Parce que c'est un événement du champ : un manifeste publié dans un grand quotidien, Le Figaro, qui donne un nom au groupe.")],
  citations=[("Car Je est un autre.","Rimbaud, lettre à Paul Demeny, 15 mai 1871"),
             ("Le Poète se fait voyant par un long, immense et raisonné dérèglement de tous les sens.","même lettre, citée par Stalloni")]),

"auteurs": N("20 min",
  "Une idée par auteur, puis la remarque sur les étrangers.",
  essentiel="Rimbaud (1854-1891) : écrit toute son œuvre entre 15 et 20 ans environ, vit une liaison orageuse avec Verlaine (Verlaine lui tire dessus à Bruxelles en 1873 et va en prison), abandonne la poésie vers 21 ans, devient commerçant entre Aden et Harar. Verlaine (1844-1896) : poète de la musique et de la nuance (Fêtes galantes, Romances sans paroles), converti en prison ; il popularise l'expression poètes maudits. Mallarmé (1842-1898) : professeur d'anglais, reçoit le mardi soir rue de Rome les jeunes poètes ; poésie de la suggestion et de l'absence. Moréas (1856-1910) : né à Athènes (Ioannis Papadiamantopoulos), il donne son nom au symbolisme en 1886, puis le quitte en 1891 pour l'École romane.",
  qr=[("Pourquoi tant d'étrangers dans le symbolisme ?",
       "Moréas (Grec), Maeterlinck et Verhaeren (Belges), Stuart Merrill et Viélé-Griffin (Américains) : Paris est alors la capitale qui consacre les avant-gardes, et le français la langue internationale de la poésie. Pascale Casanova parle de République mondiale des lettres."),
      ("Qu'est-ce qu'un poète maudit ?",
       "Un poète rejeté ou ignoré par la société et le public, que ses pairs reconnaissent : l'expression vient du livre de Verlaine (Corbière, Rimbaud, Mallarmé, puis Desbordes-Valmore, Villiers, Pauvre Lélian, c'est-à-dire Verlaine lui-même).")]),

"outil": N("20 min",
  "Une définition, un exemple. Le sociolecte est la langue d'un groupe social, avec ses valeurs. Le refus de la langue commune est une prise de position.",
  essentiel="Pierre Zima (né en 1946), théoricien de la sociocritique, propose d'étudier les sociolectes : chaque groupe social parle une langue particulière (vocabulaire, tournures, valeurs). Un texte littéraire reprend, mélange ou refuse ces langages. Les symbolistes refusent la langue du journal et de la bourgeoisie ; ils cherchent des mots rares (Moréas veut des vocables impollués). Être difficile devient un signe d'appartenance au groupe des poètes.",
  qr=[("Sociolecte : donnez un exemple d'aujourd'hui.",
       "La langue des réseaux sociaux, celle des juristes, celle des supporters de football : chaque groupe a ses mots, ses tournures et ses valeurs."),
      ("Le Bateau ivre invente sa propre langue : en quoi est-ce une prise de position ?",
       "Mots rares (Péninsules démarrées, Léviathan, Maelstroms), images inouïes, alexandrins disloqués : le poème refuse la langue commune et la poésie installée (le Parnasse qui l'a écarté) et revendique une place à part.")],
  source="P. V. Zima, Manuel de sociocritique, Picard, 1985 (rééd. L'Harmattan, 2000)."),

"critique-stalloni-symbolisme": N("20 min, séance A",
  "Lire la citation de Mallarmé à voix haute, lentement. Puis la phrase de Stalloni sur les grands créateurs en marge. Présenter les quatre idées. Montrer l'erreur de date du manuel et demander aux étudiants de la trouver eux-mêmes (le manuel dit septembre 1866 au lieu de 1886).",
  essentiel="Stalloni décrit le symbolisme en trois temps. 1. Les précurseurs : Hugo, Nerval et surtout Baudelaire (Correspondances), que Moréas appelle le véritable précurseur. 2. Une étape nécessaire, la Décadence : après 1870 et la Commune, de jeunes poètes pessimistes forment des groupes provocateurs (Zutistes de Charles Cros, Hydropathes, Hirsutes, Fumistes), fréquentent les cafés du Quartier latin et le cabaret du Chat noir ; Verlaine écrit en 1883 Je suis l'Empire à la fin de la Décadence ; Huysmans crée Des Esseintes (À rebours, 1884) ; Anatole Baju fonde Le Décadent (1886). 3. L'école symboliste : manifeste de Moréas, revues (Le Symboliste de Gustave Kahn, 1886 ; La Plume, 1889 ; Mercure de France, 1890 ; La Revue blanche, 1891), poètes belges (Verhaeren, Maeterlinck). Esthétique : suggestion, musique, vers libre (théorisé par Kahn), langue rare. Paradoxe : les grands (Mallarmé, Verlaine, Rimbaud) restent en marge de l'école, qui compte surtout des poètes aujourd'hui oubliés.",
  qr=[("Pourquoi Rimbaud, Verlaine et Mallarmé restent-ils en marge de l'école qui se réclame d'eux ?",
       "Parce qu'ils sont plus âgés, déjà reconnus par les jeunes, et qu'une école est un instrument de jeunes qui cherchent une place : les maîtres n'en ont pas besoin. Leur originalité ne se laisse pas réduire à une doctrine. Le même phénomène existe pour le Parnasse."),
      ("Quelle erreur trouve-t-on dans le manuel ?",
       "Stalloni date le manifeste de Moréas de septembre 1866 : c'est le 18 septembre 1886. Une faute de frappe dans un manuel imprimé : on vérifie toujours, même les livres."),
      ("Que veut dire suggérer plutôt que nommer ?",
       "Ne pas décrire l'objet directement, mais créer, par les sons et les images, l'impression ou l'état d'âme qu'il produit : le lecteur devine peu à peu, et ce travail est son plaisir."),
      ("Qu'est-ce que le vers libre ?",
       "Un vers qui ne compte plus un nombre fixe de syllabes et ne rime pas forcément : son rythme suit le souffle et le sens. Gustave Kahn le théorise ; Laforgue et Viélé-Griffin le pratiquent.")],
  citations=[("Nommer un objet, c'est supprimer les trois-quarts de la jouissance du poème qui est faite du bonheur de deviner peu à peu ; le suggérer, voilà le rêve.","Mallarmé, réponse à l'enquête de Huret, 1891, cité par Stalloni"),
             ("Je suis l'Empire à la fin de la Décadence.","Verlaine, Langueur, 1883, cité par Stalloni")],
  source=f"{STAL}, « Le Symbolisme »."),

"texte1": N("40 min, séance B",
  "Faire relire les cinq premières strophes à voix haute. Le je est le bateau : la métaphore est filée sur tout le poème.",
  essentiel="Le Bateau ivre compte vingt-cinq quatrains d'alexandrins (cent vers). Un bateau fluvial, libéré de ses haleurs (tués par des Peaux-Rouges dès la première strophe) et de son équipage, descend les fleuves jusqu'à la mer et vit une suite de visions ; à la fin, épuisé, il ne désire plus qu'une flache (une flaque) d'Europe où un enfant lâche un bateau de papier. Rimbaud l'écrit à 16 ans, sans avoir jamais vu la mer, pour se présenter aux poètes parisiens.",
  qr=[("Je : qui dit je, un homme, un bateau ?",
       "Le bateau : c'est lui qui parle tout au long du poème. Mais le bateau est aussi une image du poète et de la poésie libérée des règles. Les trois lectures sont possibles si on les justifie."),
      ("Majuscule : pourquoi Fleuves avec une majuscule ?",
       "La majuscule personnifie et agrandit les fleuves : ils deviennent des puissances presque divines, impassibles comme des dieux indifférents."),
      ("Liberté : que perd le bateau ? Que gagne-t-il ?",
       "Il perd ses guides (les haleurs), sa cargaison, son gouvernail, sa sécurité. Il gagne la liberté, les visions, le Poème de la Mer ; mais à la fin il éprouve la fatigue et la nostalgie : la liberté a un prix."),
      ("Qui sont les haleurs ?",
       "Les hommes qui tiraient les bateaux le long des fleuves avec des cordes, depuis la rive. Symboliquement : les règles, les maîtres, la tradition.")],
  citations=[("Comme je descendais des Fleuves impassibles, / Je ne me sentis plus guidé par les haleurs…","Rimbaud, Le Bateau ivre, vers 1-2"),
             ("Mais, vrai, j'ai trop pleuré ! Les Aubes sont navrantes.","Le Bateau ivre, strophe 23")],
  piege="Ne pas réduire le poème à une biographie de Rimbaud (16 ans, fugues)."),

"texte2": N("30 min, séance A",
  "Le manifeste paraît dans le supplément littéraire du Figaro, le 18 septembre 1886. Faire relever les marques du genre : ennemis désignés, ton affirmatif, programme, nom d'école.",
  qr=[("Ennemis : contre quoi le manifeste se dresse-t-il ?",
       "Contre l'enseignement (la poésie qui veut instruire), la déclamation (l'éloquence romantique), la fausse sensibilité (le lyrisme facile) et la description objective (le Parnasse et le naturalisme)."),
      ("Programme : que veut dire vêtir l'Idée d'une forme sensible ?",
       "Donner à une idée abstraite une apparence concrète (image, son, couleur) qui la fait sentir sans la nommer : la forme n'est pas un but en soi, elle conduit vers l'Idée. Moréas reprend un vocabulaire platonicien."),
      ("Genre : quelles sont les marques d'un manifeste ?",
       "Un nom d'école, des ennemis désignés, un programme, un ton affirmatif et collectif, une publication spectaculaire (ici, un grand journal)."),
      ("Pourquoi publier un manifeste dans un grand journal ?",
       "Pour faire date et nommer le groupe devant le grand public : on retrouvera le même geste chez Marinetti en 1909, dans le même journal.")],
  citations=[("Ennemie de l'enseignement, la déclamation, la fausse sensibilité, la description objective, la poésie symbolique cherche à vêtir l'Idée d'une forme sensible…","Moréas, Le Symbolisme, Le Figaro, 18 septembre 1886")]),

"methode": N("40 min",
  "Distribuer un paragraphe qui paraphrase Le Bateau ivre et le faire réécrire en groupes : idée, citation courte intégrée, analyse de l'effet.",
  qr=[("Exemple de paraphrase à corriger.",
       "Le bateau descend les fleuves et n'a plus de haleurs, puis il va dans la mer et voit beaucoup de choses. (Aucune idée, aucune analyse.)"),
      ("Exemple de paragraphe d'analyse.",
       "Dès le début, le poème transforme une perte en libération. Le bateau ne se sent plus guidé par les haleurs : le passé simple marque une rupture brutale, et la négation fait du manque de guides le point de départ d'une aventure. La majuscule des Fleuves impassibles agrandit le décor et annonce une liberté presque cosmique.")],
  piege="La citation n'est pas une preuve en soi : elle doit être commentée."),

"nouvelle": N("25 min, séance C",
  "Raconter Véra en cinq minutes, puis lire la fin.",
  essentiel="Véra (dans les Contes cruels, 1883) : le comte d'Athol a perdu sa jeune femme, Véra, morte au terme d'une nuit d'amour. Après l'enterrement, il jette la clef du tombeau à l'intérieur du caveau et décide, avec son vieux domestique Raymond, de vivre comme si elle était vivante. Au bout d'un an, la présence de Véra devient sensible. Mais un soir il se rappelle qu'elle est morte : l'illusion s'efface. Il demande alors le chemin pour la rejoindre, et la clef du tombeau tombe sur le lit. Villiers (1838-1889), noble ruiné, ami de Mallarmé, est l'un des poètes maudits de Verlaine.",
  qr=[("Deuil : que fait le comte ?",
       "Il refuse la mort de sa femme et organise sa vie comme si elle était là : la volonté et l'amour contre la mort."),
      ("Fantastique : la volonté peut-elle ressusciter ?",
       "Le conte le suggère sans le prouver : la présence devient presque réelle, puis disparaît dès que le comte se souvient. La clef qui tombe à la fin est le seul signe matériel, et il reste inexplicable."),
      ("Conte cruel : en quoi la fin est-elle cruelle ?",
       "Au moment même où l'illusion triomphe, un seul souvenir la détruit ; la clef qui tombe semble une réponse, mais elle ouvre seulement le tombeau : la seule voie vers Véra est la mort."),
      ("Quel lien avec La Morte amoureuse ?",
       "Deux amours plus forts que la mort (semaine 3) ; mais chez Gautier la morte revient vers le vivant, chez Villiers c'est le vivant qui la fait revenir par la volonté.")],
  citations=[("L'amour est plus fort que la Mort, a dit Salomon : oui, son mystérieux pouvoir est illimité.","Villiers de l'Isle-Adam, Véra, première phrase"),
             ("…c'était la clef du tombeau.","Véra, fin")]),

"labo": N("35 min",
  "Une strophe, trois versions italiennes : publiée, IA, étudiante. Critères : sens, rythme, images.",
  qr=[("Que vérifier dans la traduction de l'IA ?",
       "Le sens exact des mots rares (haleurs, flache, Léviathan), la conservation des images, le rythme (un endecasillabo ou un vers libre ?), et les ajouts : l'IA explique souvent au lieu de traduire."),
      ("Que vérifier dans la biographie que l'IA donne de Rimbaud ?",
       "L'âge (16 ans en 1871), la date du Bateau ivre (été 1871), la publication (1883), la mort (Marseille, 1891). Les erreurs de date sont fréquentes.")],
  piege="Faire aussi vérifier les dates biographiques de Rimbaud données par l'IA : âge, dates de publication."),

"italia": N("15 min",
  "Pascoli et D'Annunzio, puis le jeu du manifeste express.",
  essentiel="Giovanni Pascoli publie Il fanciullino en 1897 : le poète est un enfant intérieur qui voit les choses pour la première fois, une autre poétique du symbole. Gabriele D'Annunzio publie Il piacere en 1889 : Andrea Sperelli, esthète romain, est le cousin italien de Des Esseintes.",
  qr=[("Comment réussir le manifeste express ?",
       "Cinq phrases : un nom d'école en -isme, deux ennemis, un programme en une image, un ton affirmatif au nous, une date et un lieu de publication imaginaires. À relire avec les marques du manifeste de Moréas."),
      ("Pourquoi Il piacere est-il proche d'À rebours ?",
       "Deux romans de l'esthète décadent, qui fait de sa vie une œuvre d'art et méprise la vie ordinaire, en 1884 et en 1889.")]),

"bilan": N("10 min",
  "Distribuer les rôles d'Ubu et de Salomé pour la lecture jouée de la semaine 7. Les textes sont sur Classroom.",
  qr=[("Que faut-il lire ?",
       "Ubu Roi, acte I, scène 1 ; la première page de Salomé ; Les Nourritures terrestres, Livre I (extraits).")]),
}

# =====================================================================  S7
NOTES[7] = {
"cover": N("3 min",
  "Trois paires A.1 cette semaine : théâtre (paire 5), poèmes en prose (paire 3, Gide), recueil de poèmes (paire 1, Vivien). Lecture critique : Bainville sur ce que deviennent les poètes de 1889.",
  qr=[("Que veut dire fin de siècle ?",
       "L'expression désigne les années 1890 et l'état d'esprit qu'on leur prête : sentiment de décadence, raffinement, goût du scandale et de l'étrange, attente d'un monde nouveau. C'est, comme Années folles, un nom d'époque.")],
  essentiel="La fin de siècle (1890-1900) est l'époque du symbolisme au théâtre (Lugné-Poe, Maeterlinck), des scandales (Wilde condamné en 1895, Ubu en 1896), de l'affaire Dreyfus (1894-1906) qui coupe le monde littéraire en deux, et d'une jeunesse qui cherche la ferveur (Gide). Les étrangers qui écrivent en français (Wilde, Vivien, Moréas) montrent l'attraction de Paris."),

"objectifs": N("5 min",
  "Présenter René Vivien simplement : poétesse de la Belle Époque, née Pauline Tarn à Londres en 1877, morte à Paris en 1909, traductrice de Sappho, amours féminines assumées (Natalie Clifford Barney).",
  qr=[("Pourquoi René Vivien a-t-elle un prénom masculin ?",
       "René est un pseudonyme (prénom mixte en français, à l'époque surtout masculin) : il permet d'entrer dans un monde poétique dominé par les hommes, et il joue avec l'identité. Elle signe d'abord R. Vivien.")],
  piege="La fiche indique 1902 pour Études et préludes ; l'édition originale chez Lemerre est généralement datée de 1901. Vérifier dans l'édition et le dire aux étudiants."),

"seances": N("3 min",
  "A : le Théâtre de l'Œuvre, Vivien, Bainville. B : Gide et la conclusion. C : lecture jouée et labo.",
  qr=[("Pourquoi une lecture jouée ?",
       "Parce qu'un texte de théâtre est écrit pour la voix et le corps : jouer Ubu et Salomé fait comprendre leur rythme et leur ton mieux qu'une analyse, et prépare la lecture expressive de l'oral.")]),

"enigme": N("10 min",
  "Raconter les deux soirées de 1896 au Théâtre de l'Œuvre, puis poser la question.",
  essentiel="Le Théâtre de l'Œuvre, fondé en 1893 par Aurélien Lugné-Poe, joue le théâtre symboliste et étranger (Ibsen, Maeterlinck) pour un public choisi d'abonnés. Il crée Salomé le 11 février 1896, pendant que Wilde est en prison à Reading (condamné en 1895 pour homosexualité), puis Ubu Roi le 10 décembre 1896, avec Firmin Gémier dans le rôle d'Ubu. Le premier mot, Merdre, provoque un quart d'heure de tumulte ; le poète irlandais Yeats est dans la salle.",
  qr=[("Comment un même théâtre peut-il jouer un drame sacré et une farce ?",
       "Parce que le Théâtre de l'Œuvre est un théâtre d'avant-garde : ce qui unit Salomé et Ubu n'est pas le genre, mais le refus du théâtre commercial (boulevard, vaudeville) et la recherche d'une forme nouvelle, pour un public d'initiés."),
      ("Qu'ont en commun ces deux pièces que tout oppose ?",
       "Un public choisi, une scène d'avant-garde, le scandale comme mode d'existence, une langue inventée ou stylisée.")]),

"frise": N("10 min",
  "Lire la frise : dix ans de scandales et de ferveur.",
  essentiel="Salomé, écrite en français à Paris en 1891, est interdite à Londres en juin 1892 pendant les répétitions avec Sarah Bernhardt : la censure anglaise interdisait de représenter des personnages bibliques. Elle paraît à Paris en 1893. Un coup de dés de Mallarmé paraît dans la revue Cosmopolis en 1897. Les Nourritures terrestres (1897) se vendent très peu avant de devenir, après 1918, le livre d'une génération.",
  qr=[("Pourquoi Salomé est-elle interdite à Londres ?",
       "Une loi ancienne interdisait de mettre en scène des personnages de la Bible ; s'y ajoutent le scandale moral (le désir de Salomé, la tête coupée) et la réputation de Wilde."),
      ("Pourquoi 1896 est-il en bleu ?",
       "Parce que le Théâtre de l'Œuvre est une institution du champ : une petite scène qui consacre l'avant-garde.")]),

"auteurs": N("20 min",
  "Une idée par auteur, puis la question des étrangers.",
  essentiel="Oscar Wilde (1854-1900) : Irlandais, dandy, auteur du Portrait de Dorian Gray (1890) ; condamné à deux ans de travaux forcés en 1895, il meurt à Paris. Alfred Jarry (1873-1907) : Ubu naît d'une farce de lycéens à Rennes contre un professeur de physique (M. Hébert) ; Jarry finit par vivre comme son personnage. André Gide (1869-1951) : fils de la bourgeoisie protestante, il découvre en Afrique du Nord (1893-1895) la liberté du désir ; prix Nobel 1947. René Vivien (1877-1909) : poétesse anglaise de langue française, Sappho est son modèle.",
  qr=[("Pourquoi Wilde et Vivien écrivent-ils en français ?",
       "Parce que le français est vers 1900 la langue de l'art et de la liberté à Paris, et qu'il leur permet d'écrire ce que la morale anglaise interdit (le désir, l'homosexualité)."),
      ("Gide et Jarry ont presque le même âge que leurs lecteurs : pourquoi est-ce important ?",
       "Parce que ce sont des jeunes qui écrivent pour des jeunes contre la génération installée : c'est la logique des nouveaux venus dans le champ.")]),

"outil": N("15 min",
  "Comparer trois scandales : Hernani (1830), les procès (1857), le Théâtre de l'Œuvre (1896). Revenir à la question du semestre.",
  qr=[("Scandale : pourquoi un scandale peut-il servir une œuvre ?",
       "Parce qu'on en parle : la presse, les camps, les débats font exister l'œuvre bien au-delà de son public réel."),
      ("Petite scène : que change un public choisi ?",
       "Le jugement des pairs et des initiés compte plus que celui du grand public : on peut échouer commercialement et gagner en prestige."),
      ("Même question qu'en 1830 et 1857 : qui a le pouvoir de dire ce qu'est la bonne littérature ?",
       "En 1830, la Comédie-Française et le public ; en 1857, les tribunaux ; en 1896, les groupes et les petites scènes. Le pouvoir de consacrer passe des institutions aux pairs, puis, plus tard, à l'école qui met tout le monde au programme.")]),

"critique-bainville-symbolistes": N("20 min, séance A",
  "Lire les deux citations. Présenter les trois articles (1901, 1904). Puis la question du débat.",
  essentiel="Dans Un poète vraiment mystique (30 juillet 1904), Bainville décrit avec ironie les années héroïques du symbolisme (vers 1885-1890) : cénacles, petites revues, livres tirés à cinquante exemplaires, mépris de tout ce qui n'est pas le culte du verbe ; Verlaine était prince, Laforgue passait dieu, Mallarmé groupait des disciples. Vingt ans après, les poètes ont dû vivre : Gustave Kahn joint la Bourse au vers libre, d'autres font un riche mariage, écrivent des romans licencieux pour la presse, ou trouvent leur salut dans l'affaire Dreyfus. Seul l'abbé Le Cardonnel, devenu prêtre en Provence, aurait dignement fini. Dans Le poète maudit (13 avril 1904), Verlaine est rejeté par les catholiques (à cause de sa vie) et par les révolutionnaires (à cause de sa foi et de son patriotisme). Dans Une confession des enfants du siècle (21 juin 1901), Bainville commente l'enquête d'Eugène Montfort sur ce que la jeunesse née entre 1870 et 1880 attend du XXe siècle.",
  qr=[("Vers 1900, qui consacre un poète : ses pairs, l'Église, l'État, la presse ou le public ?",
       "Selon Bainville, tout le monde à la fois, et c'est le problème : Verlaine reçoit des pairs une gloire que lui refusent l'État (son buste refusé au Luxembourg pour immoralité, selon Bainville), l'Église et les partis. La consécration se joue dans un champ divisé par l'affaire Dreyfus."),
      ("Le critique décrit-il le champ ou le juge-t-il ?",
       "Il le juge : il distribue de bons destins (le prêtre poète, le Verlaine patriote) et de mauvais (les dreyfusards, la Ligue des droits de l'homme). Mais en jugeant, il décrit très bien la réalité matérielle des poètes : tirages minuscules, besoin d'argent, reconversions."),
      ("Que nous apprend le chiffre de cinquante exemplaires ?",
       "Que la poésie d'avant-garde vit hors du marché : on imprime pour les pairs, pas pour vendre. C'est le monde à l'envers de Bourdieu (semaine 4).")],
  citations=[("On méprisait absolument tout ce qui n'était pas le culte du verbe.","Bainville, 30 juillet 1904"),
             ("Verlaine est bien un poète maudit.","Bainville, 13 avril 1904")],
  piege="Bainville écrit depuis un camp (nationaliste, catholique de tradition, antidreyfusard). Ses éloges et ses moqueries sont des prises de position ; le dire avant la lecture.",
  source=f"{BAIN}, « Un poète vraiment mystique », « Le poète maudit », « Une confession des enfants du siècle »."),

"texte1": N("30 min",
  "Lire les deux premières répliques très différemment : Salomé, lente, répétitive, lunaire ; Ubu, forte, grossière, comique. L'orthographe estes imite l'ancien français.",
  essentiel="Salomé : à la cour d'Hérode, la princesse Salomé désire le prophète Iokanaan (Jean-Baptiste), prisonnier dans une citerne, qui la repousse. Hérode lui promet ce qu'elle veut si elle danse : elle danse la danse des sept voiles et demande la tête de Iokanaan, qu'elle embrasse. Horrifié, Hérode ordonne : Tuez cette femme ! Ubu Roi : poussé par Mère Ubu, le Père Ubu, officier du roi de Pologne, tue le roi, prend le trône, massacre les nobles pour prendre leurs biens (la phynance), fuit devant l'armée russe et s'embarque pour la France.",
  qr=[("Ouverture : que promet chaque première réplique ?",
       "Salomé : un désir et une fascination (le regard du jeune Syrien sur la princesse, sous la lune), donc un drame du regard et de la mort. Ubu : une agression du public et du langage, donc une farce violente contre toutes les règles."),
      ("Langue : langue biblique, mot inventé, orthographe ancienne, quels effets ?",
       "Chez Wilde, des phrases simples et répétées, comme une incantation biblique, créent une musique hypnotique. Chez Jarry, le mot inventé merdre (un r ajouté) choque et fait rire, et l'orthographe ancienne (estes) parodie le théâtre classique."),
      ("Scandale : pourquoi l'une est-elle interdite, l'autre sifflée ?",
       "Salomé est interdite par la censure anglaise pour des raisons morales et religieuses ; Ubu est sifflé par le public parisien pour sa grossièreté et son refus de toutes les conventions théâtrales.")],
  citations=[("Comme la princesse Salomé est belle ce soir !","Wilde, Salomé, 1893, le jeune Syrien"),
             ("Ah ! j'ai baisé ta bouche, Iokanaan, j'ai baisé ta bouche.","Salomé, fin"),
             ("PÈRE UBU. — Merdre. / MÈRE UBU. — Oh ! voilà du joli, Père Ubu, vous estes un fort grand voyou.","Jarry, Ubu Roi, I, 1")]),

"texte2": N("40 min, séance B",
  "Faire repérer l'impératif, le futur, le tutoiement : une prose qui enseigne. Lire ensuite un sonnet de Vivien (Classroom) et comparer deux libertés de 1900.",
  essentiel="Les Nourritures terrestres (1897) sont un livre en prose poétique, adressé à un disciple imaginaire, Nathanaël : Gide lui enseigne la ferveur, le désir, la disponibilité, le refus des attaches (famille, maison, morale). Le livre se termine en demandant à Nathanaël de jeter le livre.",
  qr=[("Destinataire : qui est Nathanaël ? Pourquoi le tutoiement ?",
       "Un disciple imaginaire, jeune lecteur idéal ; le tutoiement crée l'intimité d'un maître et d'un élève, et fait du lecteur réel le destinataire."),
      ("Prose : vers ou prose ? Où est le rythme ?",
       "Prose, mais rythmée : phrases courtes, versets, répétitions, impératifs, énumérations. C'est une prose poétique, comme Le Spleen de Paris (paire 3)."),
      ("Vivien : comparer avec un sonnet de René Vivien, deux libertés de 1900.",
       "Gide libère le désir dans une prose qui casse les formes ; Vivien exprime un amour féminin dans des formes très régulières (sonnet, alexandrin) : la liberté du sujet chez elle passe par la forme classique, chez lui par la forme nouvelle."),
      ("Que veut dire Que l'importance soit dans ton regard, non dans la chose regardée ?",
       "Ce qui compte n'est pas l'objet mais l'intensité du regard qu'on lui porte : une morale de la ferveur, proche de l'ivresse de Baudelaire (semaine 4).")],
  citations=[("Familles, je vous hais ! foyers clos ; portes refermées ; possessions jalouses du bonheur.","Gide, Les Nourritures terrestres, Livre IV"),
             ("Nathanaël, à présent, jette mon livre.","fin de l'ouvrage")],
  piege="Ne pas réduire Gide à l'autobiographie : la voix des Nourritures est construite."),

"methode": N("40 min",
  "Trois ouvertures possibles pour un même commentaire ; écarter les généralités du type De tout temps. Une bonne ouverture nomme une œuvre précise.",
  essentiel="La conclusion a deux temps : 1. un bilan qui répond nettement à la problématique en rappelant le chemin (une phrase par partie) ; 2. une ouverture vers une autre œuvre précise, qui prolonge ou contredit la lecture.",
  qr=[("Donner trois ouvertures pour un commentaire de la première scène d'Ubu Roi.",
       "1. Vers Hernani (1830) : un autre premier vers qui fait scandale. 2. Vers Six personnages en quête d'auteur de Pirandello (1921, Paris 1923) : un autre théâtre qui casse les conventions. 3. Vers Macbeth : Ubu parodie le couple Macbeth, poussé au meurtre par sa femme. La meilleure est la troisième, parce qu'elle éclaire le texte."),
      ("Qu'est-ce qu'une mauvaise ouverture ?",
       "Une généralité (De tout temps, les hommes ont aimé rire) ou une question vague (Et aujourd'hui ?).")]),

"nouvelle": N("40 min, séance C",
  "Lecture jouée en petits groupes. Ne pas chercher la perfection : l'excès d'Ubu doit s'entendre. Terminer par cinq minutes sur les recueils de la partie B : comment les présenter à l'oral.",
  qr=[("Ubu : comment jouer ?",
       "Très fort, avec des gestes excessifs, une voix mécanique de marionnette : Jarry voulait des acteurs comme des pantins."),
      ("Salomé : comment lire ?",
       "Lentement, avec des répétitions et des pauses : c'est une musique. Trois voix (le jeune Syrien, le page d'Hérodias, les soldats)."),
      ("Recueils : comment présenter Les Diaboliques ou Médan à l'oral ?",
       "En trois points : le cadre (qui réunit les récits), les échos (thèmes communs), la position (ce que le recueil dit de son époque et de son groupe), avec une nouvelle choisie comme exemple.")]),

"labo": N("30 min",
  "L'IA installe Ubu à Catania aujourd'hui. Comparer avec Jarry.",
  qr=[("Qu'a gardé l'IA de Jarry : langue, excès, critique du pouvoir ?",
       "Souvent la situation (un tyran ridicule) et quelques jurons ; rarement la violence, l'absurde et la grossièreté de la langue."),
      ("Qu'a-t-elle perdu ?",
       "La cruauté comique, l'invention verbale (merdre, phynance, oneille), le rythme de marionnette. L'IA rend Ubu gentil ou moralisateur."),
      ("Pourquoi l'IA adoucit-elle Ubu ?",
       "Parce qu'elle est entraînée à éviter la grossièreté et la violence, et à expliquer : c'est l'inverse du projet de Jarry, qui veut choquer.")],
  piege="L'IA tend à rendre Ubu gentil ou moralisateur : excellent départ pour parler de la violence comique de Jarry."),

"italia": N("15 min",
  "D'Annunzio en français, la Salomé de Strauss, puis la traduction des mots d'Ubu.",
  essentiel="D'Annunzio écrit en français Le Martyre de saint Sébastien (1911), musique de Debussy, avec Ida Rubinstein. La Salomé de Richard Strauss (Dresde, 1905) reprend la pièce de Wilde dans sa traduction allemande et fait le tour des opéras d'Europe.",
  qr=[("Traduire en italien merdre, phynance, oneille.",
       "Pas de solution unique ; on peut proposer : merdre, merdra (une lettre ajoutée au gros mot italien) ; phynance, phinanza ou fynanza (orthographe fantaisiste de finanza) ; oneille, onecchia (orecchia déformée). L'important est de garder la déformation, pas seulement le sens.")]),

"bilan": N("10 min",
  "Chacun annonce son roman bref (paire 6) pour la semaine 8 et relit les étapes de méthode avant l'atelier final.",
  qr=[("Que faut-il lire ?",
       "Le Manifeste du futurisme (extraits) et le premier chapitre du roman bref choisi : Le Grand Meaulnes ou Les Caves du Vatican.")]),
}

# =====================================================================  S8
NOTES[8] = {
"cover": N("3 min",
  "Dernière semaine : trois paires A.1 (manifeste, poème long, roman bref), l'atelier final et le bilan. Rester au niveau des extraits : la lecture intégrale reste personnelle.",
  qr=[("Pourquoi le cours s'arrête-t-il vers 1929 ?",
       "Parce que la fiche du cours va du préromantisme aux Années folles : la crise de 1929 et les années 1930 ouvrent une autre période (engagement, montée des fascismes), étudiée dans un autre cours.")],
  essentiel="De 1909 à 1929, trois moments : les avant-gardes d'avant-guerre (futurisme, 1909 ; l'année 1913 avec Cendrars, Apollinaire, Alain-Fournier, Proust), la Grande Guerre (1914-1918, environ 1,4 million de soldats français morts), puis l'après-guerre qu'on appelle les Années folles (Dada, surréalisme, jazz, mode), dont les historiens discutent la réalité. René Maran, premier écrivain noir lauréat du Goncourt (1921), ouvre vers les littératures francophones."),

"objectifs": N("5 min",
  "Garder 20 minutes en fin de séance C pour le bilan IA du semestre.",
  qr=[("Qu'est-ce qu'un chrononyme ?",
       "Un nom donné à une période (la Belle Époque, les Années folles, les Trente Glorieuses). Il produit une image de l'époque, souvent après coup, et simplifie la réalité.")]),

"seances": N("3 min",
  "A : avant-gardes, guerre, romans brefs. B : atelier final. C : Années folles et bilan.",
  qr=[("Comment se déroule l'atelier final ?",
       "Deux heures, un extrait du domaine public, un commentaire complet (introduction, deux ou trois parties, conclusion) corrigé avec la grille du cours ; retour écrit, sans note.")]),

"enigme": N("10 min",
  "Donner le chiffre : environ 1,4 million de soldats français morts entre 1914 et 1918. Laisser les étudiants proposer.",
  qr=[("Les Années folles ont-elles vraiment été folles ?",
       "Pour une minorité urbaine et aisée, surtout à Paris et après 1924 : jazz, cabarets, mode, avant-gardes. Pour la majorité, les années 1920 sont celles du deuil, de la reconstruction et de l'inflation. L'expression dit une partie de la réalité, pas toute."),
      ("Fête pour oublier, fête de quelques-uns, ou deuil partout ?",
       "Les trois : la fête est urbaine et minoritaire, le deuil est national (monuments aux morts dans presque toutes les communes).")]),

"frise": N("10 min",
  "Mettre en relief 1913, année extraordinaire, puis la rupture d'août 1914.",
  essentiel="Le manifeste de Marinetti paraît d'abord en italien dans plusieurs journaux de la péninsule début février 1909, mais c'est la une du Figaro du 20 février qui fait date. En 1913 paraissent Alcools d'Apollinaire, la Prose du Transsibérien de Cendrars, Le Grand Meaulnes (qui manque le prix Goncourt) et Du côté de chez Swann de Proust. Alain-Fournier est tué le 22 septembre 1914. Valéry publie La Crise de l'esprit en 1919 ; Breton, Aragon et Soupault fondent la revue Littérature la même année.",
  qr=[("Pourquoi Marinetti publie-t-il à Paris ?",
       "Paris est alors la capitale qui consacre les avant-gardes, et Le Figaro donne un retentissement international ; Marinetti, né à Alexandrie et formé en français, écrit naturellement en français."),
      ("Pourquoi 1913 est-elle une année extraordinaire ?",
       "Parce que paraissent la même année des œuvres qui fondent la modernité : Alcools, la Prose du Transsibérien, Du côté de chez Swann, Le Grand Meaulnes (et Le Sacre du printemps de Stravinsky à Paris).")],
  citations=[("Nous autres, civilisations, nous savons maintenant que nous sommes mortelles.","Valéry, La Crise de l'esprit, 1919"),
             ("À la fin tu es las de ce monde ancien","Apollinaire, Zone, Alcools, 1913, premier vers")]),

"auteurs": N("15 min",
  "Une idée par auteur, puis chacun annonce son roman bref.",
  essentiel="Marinetti (1876-1944) : né à Alexandrie d'Égypte, poète d'expression française, fondateur du futurisme ; il glorifie la vitesse, la machine et la guerre, et se rapprochera du fascisme. Cendrars (1887-1961) : Suisse (Frédéric Sauser), voyageur ; la Prose du Transsibérien, conçue avec la peintre Sonia Delaunay, est un livre dépliant d'environ deux mètres ; il perd le bras droit à la guerre en 1915. Alain-Fournier (1886-1914) : un seul roman, Le Grand Meaulnes. Gide : Les Caves du Vatican (1914) est une sotie (récit satirique) où Lafcadio pousse un inconnu, Amédée Fleurissoire, hors d'un train entre Rome et Naples, sans motif.",
  qr=[("Quel roman bref choisissez-vous pour la paire 6, et pourquoi ?",
       "Réponse personnelle. Le Grand Meaulnes pour ceux qui aiment le récit d'adolescence, le mystère et la nostalgie ; Les Caves du Vatican pour ceux qui aiment l'ironie, la satire et les questions morales (l'acte gratuit). Exiger une raison littéraire, pas seulement la longueur.")]),

"outil": N("15 min",
  "Une définition, deux historiens, la question qui revient de la semaine 1.",
  essentiel="Myriam Juan (Les Années folles, Que sais-je ?) montre que l'expression est un chrononyme : une image culturelle surtout parisienne et élitaire, largement fixée après coup. Jean-Yves Le Naour (1922-1929. Les années folles ?, Perrin, 2022) rappelle le deuil, la reconstruction, l'inflation et le refus du vote des femmes : la Chambre vote le suffrage féminin le 20 mai 1919, le Sénat le refuse le 21 novembre 1922 ; les Françaises voteront en 1945. Pour lui, l'optimisme ne s'installe vraiment que vers 1924-1925.",
  qr=[("Manifeste : comment une avant-garde date-t-elle sa naissance ?",
       "En publiant un manifeste daté et spectaculaire : 18 septembre 1886 pour le symbolisme, 20 février 1909 pour le futurisme, 1924 pour le surréalisme."),
      ("Qui nomme une époque ?",
       "Rarement ceux qui la vivent : des journalistes, puis des historiens et des manuels, après coup. Même question que pour le préromantisme en semaine 1."),
      ("Envers : qui manque aux images de la fête ?",
       "Les veuves, les orphelins, les mutilés (les gueules cassées), les campagnes, les ouvriers, les femmes privées du vote.")],
  source="M. Juan, Les Années folles, PUF, Que sais-je ? ; J.-Y. Le Naour, 1922-1929. Les années folles ?, Perrin, 2022."),

"envers": N("15 min, séance C",
  "But de la diapositive : répondre à l'énigme en montrant qui manque aux images de la fête. Chiffres à garder simples : environ 1,4 million de morts, deux tiers des communes ont déjà leur monument en 1922, reconstruction presque achevée vers 1924. Montrer le monument pacifiste de Gentioux (Maudite soit la guerre) comme contrepoint. Lien avec les textes : Radiguet (la guerre vue de l'arrière), La Garçonne (la peur de la femme libre), Dorgelès, Le Réveil des morts (les profiteurs de la reconstruction).",
  essentiel="Le Naour, dans la première partie de son livre (Le boulet de la guerre), montre que le deuil pèse sur toute la décennie. Juan et Le Naour sont deux lectures complémentaires : la modernité réelle (jazz, avant-gardes, femmes qui travaillent) et le deuil persistant.",
  qr=[("Que montre le monument de Gentioux ?",
       "Un enfant orphelin montrant du poing l'inscription Maudite soit la guerre : un des rares monuments pacifistes, au milieu de milliers de monuments patriotiques."),
      ("Quand les Françaises votent-elles pour la première fois ?",
       "En 1945 (municipales d'avril). Le Sénat avait rejeté le vote des femmes le 21 novembre 1922, par 156 voix contre 134.")],
  source="J.-Y. Le Naour, 1922-1929. Les années folles ?, Perrin, 2022, première partie."),

"texte1": N("30 min, séance A",
  "Comparer les marques du manifeste avec Moréas (semaine 6). Lire le premier vers de Cendrars et décrire le livre-objet.",
  qr=[("Manifeste : comparer avec Moréas, mêmes marques ?",
       "Oui : publication dans Le Figaro, nom d'école, ennemis (le passé, les musées, les académies), programme, ton affirmatif au nous. Mais le ton de Marinetti est violent et provocateur (glorifier la guerre, brûler les musées), quand Moréas restait obscur et mesuré."),
      ("Vitesse : train, auto, poème, comment la forme accélère-t-elle ?",
       "Vers libres de longueur variable, énumérations, noms de lieux, absence de ponctuation, ruptures, présent : le poème avance comme le train ; chez Marinetti, l'automobile devient plus belle qu'une statue antique."),
      ("Choix : paire 2 et paire 4, quel texte choisirez-vous ?",
       "Réponse personnelle : paire 2, Le Bateau ivre (Rimbaud, semaine 6) ou la Prose du Transsibérien (Cendrars) ; paire 4, Le Symbolisme (Moréas) ou le Manifeste du futurisme (Marinetti). Justifier par un critère littéraire."),
      ("Comment un poème peut-il aller vite ?",
       "Vers libres, énumérations, absence de ponctuation, ruptures, noms de lieux.")],
  citations=[("Une automobile rugissante, qui a l'air de courir sur de la mitraille, est plus belle que la Victoire de Samothrace.","Marinetti, Manifeste du futurisme, Le Figaro, 20 février 1909")],
  piege="Cendrars n'est pas dans le domaine public : courtes citations seulement. Marinetti glorifie la guerre et le mépris de la femme : le dire, et rappeler son ralliement au fascisme."),

"texte2": N("30 min, séance A",
  "Lire la première phrase du Grand Meaulnes, puis raconter simplement la scène du train des Caves du Vatican.",
  essentiel="Le Grand Meaulnes : à Sainte-Agathe, en Sologne, François Seurel, fils de l'instituteur, raconte l'arrivée d'Augustin Meaulnes, un grand garçon de 17 ans qui s'égare et découvre une fête étrange dans un domaine mystérieux, où il rencontre Yvonne de Galais ; toute sa vie sera la recherche de ce domaine perdu. Les Caves du Vatican : une escroquerie fait croire que le pape est séquestré ; dans le train, le jeune Lafcadio pousse Amédée Fleurissoire par la portière, sans raison, pour voir s'il en est capable : c'est l'acte gratuit.",
  qr=[("Date : 189…, pourquoi une date incomplète ?",
       "Le narrateur se souvient : la date effacée crée un temps de légende, flou, déjà lointain, et universalise l'histoire."),
      ("Narrateur : qui raconte l'arrivée de Meaulnes ?",
       "François Seurel, le fils de l'instituteur, devenu adulte : un témoin, pas le héros."),
      ("Gide : Lafcadio pousse un inconnu d'un train, un acte sans motif est-il possible ?",
       "C'est la question du roman : Lafcadio veut prouver sa liberté par un acte sans cause ; mais il obéit peut-être à une curiosité ou à un défi, ce qui est déjà un motif. Gide pose la question sans la résoudre, avec ironie.")],
  citations=[("Il arriva chez nous un dimanche de novembre 189…","Alain-Fournier, Le Grand Meaulnes, 1913, première phrase")]),

"methode": N("2 h, séance B",
  "Atelier final non noté, retour écrit. Proposer un extrait du domaine public (Alain-Fournier ou Marinetti).",
  qr=[("Que relire avant de rendre ?",
       "La langue (accords, conjugaisons), l'exactitude des citations (comparer avec le texte), les temps des verbes (présent de l'analyse), la cohérence entre problématique, plan et conclusion.")],
  piege="Rappeler la relecture finale : langue, citations exactes, temps des verbes."),

"nouvelle": N("30 min, séance C",
  "Les deux historiens, puis Maran.",
  essentiel="René Maran (1887-1960), né à la Martinique de parents guyanais, administrateur colonial en Oubangui-Chari (aujourd'hui Centrafrique), reçoit le prix Goncourt le 14 décembre 1921 pour Batouala, véritable roman nègre ; sa préface dénonce les abus de la colonisation, et une campagne de presse le pousse à quitter l'administration coloniale. Paul Morand publie Ouvert la nuit en 1922 : des nouvelles rapides et cosmopolites, symbole des Années folles.",
  qr=[("Juan : qu'est-ce qu'un chrononyme ?",
       "Un nom d'époque qui donne une image culturelle plus large que la réalité vécue."),
      ("Le Naour : pourquoi la fête vient-elle tard ?",
       "Parce que le deuil, la reconstruction et la crise financière occupent le début des années 1920 ; l'optimisme ne s'installe que vers 1924-1925."),
      ("Maran : pourquoi Batouala fait-il scandale ?",
       "Parce qu'un fonctionnaire colonial noir reçoit le prix le plus célèbre de France et critique, dans sa préface, la colonisation : le champ littéraire consacre un livre que l'empire colonial ne peut accepter."),
      ("Fil rouge : de René (1802) à Ouvert la nuit (1922), qu'est devenu le récit bref ?",
       "D'un récit enchâssé dans un essai religieux à une nouvelle autonome, née dans la presse, devenue au XIXe siècle un genre majeur (Mérimée, Maupassant), puis, chez Morand, une forme rapide et moderne.")],
  piege="Le Manifeste de Breton et Batouala ne sont pas dans le domaine public : citations courtes seulement.",
  plus="Maran ouvre vers les littératures francophones (Mabanckou, Sarr, Slimani) : occasion naturelle de présenter les recherches de l'enseignant en sociocritique postcoloniale."),

"labo": N("30 min",
  "Chaque étudiant fait préparer par l'IA une fiche sur son roman bref (paire 6), puis la vérifie et la corrige.",
  qr=[("Contrôler dates, noms et citations : combien d'erreurs ?",
       "En général deux à cinq par fiche : date de parution, nom du narrateur (Seurel), lieu (Sainte-Agathe), nom de la victime de Lafcadio (Fleurissoire), citations inventées."),
      ("Quelles hallucinations avons-nous repérées ce semestre ?",
       "Faire la liste au tableau et les classer : dates, attributions (Madame Bovary, c'est moi), citations inventées, confusions de personnages, scansion fausse, traduction qui explique au lieu de traduire. Conclusion : l'IA est utile pour proposer, jamais pour attester.")],
  piege="Faire compter les erreurs de l'IA et les classer : dates, attributions, citations inventées."),

"italia": N("15 min",
  "Le futurisme né à Paris, Ungaretti, Pirandello.",
  essentiel="Ungaretti, né à Alexandrie comme Marinetti, étudie à Paris, fréquente Apollinaire, combat dans les tranchées (Il porto sepolto, 1916) et écrit aussi des poèmes en français. Georges Pitoëff crée Six personnages en quête d'auteur de Pirandello à la Comédie des Champs-Élysées le 10 avril 1923 : un choc pour le théâtre français.",
  qr=[("Pourquoi dire que le futurisme italien naît à Paris ?",
       "Parce que le texte fondateur est écrit en français et que sa consécration vient de sa publication à la une du Figaro : la périphérie (l'Italie) passe par le centre (Paris) pour exister internationalement."),
      ("Qu'ont en commun Marinetti et Ungaretti ?",
       "Nés à Alexandrie, formés en français, passés par Paris : la Méditerranée et le français relient la littérature italienne moderne à Paris.")]),

"bilan": N("20 min",
  "Revenir à l'énigme de la semaine 1 et à la question du semestre. Faire répondre par groupes, puis synthèse au tableau. Laisser l'Atelier du siècle ouvert après le cours.",
  qr=[("Qui a le pouvoir de dire ce qu'est la bonne littérature ?",
       "Personne seul : un champ de forces qui change avec le temps. Les académies (avant 1793), le public et la presse (1836), l'État et les tribunaux (1857), les écoles et les petites revues (1886), les petites scènes (1896), les manifestes et les prix (1909, 1921), et finalement l'école et l'université, qui mettent au programme les condamnés d'hier. Le lecteur critique fait partie de ce champ."),
      ("Que faut-il faire après le cours ?",
       "Compléter l'anthologie A.2 (50 extraits) et la faire valider au moins 30 jours avant l'examen ; relire les six œuvres A.1 choisies et leurs fiches.")]),
}
