# Notes de l'enseignant, semaines 1 à 4 (version du 6 octobre 2026).
# Écrites pour un enseignant qui ne connaît pas la période : chaque question posée
# en classe a sa réponse (Q. / R.). Clé = identifiant de diapositive.
from notes_lib import N

STAL = "Y. Stalloni, Écoles et courants littéraires, Armand Colin, 3e éd., 2015, chap. « Le dix-neuvième siècle »"

NOTES = {}

# =====================================================================  S1
NOTES[1] = {
"cover": N("5 min, début de la séance A",
  "Accueillir les étudiants, écrire au tableau l'adresse du site et la question du semestre : Qui a le pouvoir de dire ce qu'est la bonne littérature ? Annoncer le contrat : huit semaines, trois séances de 2 heures par semaine ; chaque semaine un contexte, deux textes du programme, une nouvelle, une étape de méthode et un labo IA. Dire clairement : je ne fais pas passer l'examen (écrit de commentaire, propédeutique à l'oral, tous deux en français, selon la fiche du cours), mais tout le cours y prépare.",
  essentiel="Le cours couvre environ 150 ans : de Rousseau (années 1770-1780) aux Années folles (1920-1929). La fiche officielle du cours (Carminella Sipala) a trois listes : A.1 (six paires d'œuvres, l'étudiant en choisit une par paire et la lit en entier), B (la nouvelle au XIXe siècle, avec des titres précis) et A.2 (une anthologie personnelle de 50 extraits). Cette semaine pose le décor : la Révolution française a détruit l'ancien système qui faisait vivre et consacrait les écrivains (académies, pensions, protecteurs), et une nouvelle sensibilité, mélancolique et tournée vers le moi, s'installe en Europe.",
  qr=[("Qui a déjà lu en entier un texte français du XIXe siècle ? Lequel ?",
       "Pas de bonne ou de mauvaise réponse : noter les titres au tableau (souvent Le Petit Prince, qui est du XXe siècle, ou Madame Bovary, Les Misérables, Le Comte de Monte-Cristo). Si un étudiant cite un texte du XXe siècle, le dire gentiment : cela permet de fixer les bornes du cours.")],
  piege="Ne pas détailler les huit semaines maintenant : montrer la page d'accueil du site et la page Mode d'emploi, c'est suffisant."),

"site": N("10 min, séance A, après les présentations",
  "Projeter la diapositive puis ouvrir le site en direct. Montrer dans l'ordre : 1. la page d'accueil et la carte de la semaine 1 ; 2. la feuille de route (objectifs, fiche du cours, séances, devoirs, anthologie, labo IA, lecture critique) ; 3. le lecteur audio et la transcription ; 4. la présentation (flèches, plein écran) ; 5. la page Mode d'emploi ; 6. l'Atelier du siècle (ne pas encore se connecter, ce sera en séance C) ; 7. la Bibliographie. Demander aux étudiants d'ouvrir le site sur leur téléphone pendant la démonstration.",
  essentiel="Le site remplace un polycopié : tout y est (objectifs, textes, devoirs, audio, présentation). Studium reste la plateforme officielle de l'université pour déposer les productions et trouver les textes intégraux. Le site est public et mis à jour chaque semaine ; les notes de l'enseignant sont visibles si on coche la case, ce qui est voulu : les étudiants peuvent relire les réponses après la séance.",
  qr=[("Où trouve-t-on ce qu'il faut lire pour la semaine prochaine ?",
       "Sur la page de la semaine, carte Avant la semaine 2 (et sur la dernière diapositive, Bilan et suite)."),
      ("Où dépose-t-on la production de la semaine ?",
       "Sur Studium, pas sur le site. Le site dit seulement quoi produire (carte Ma production)."),
      ("Le site remplace-t-il la lecture des œuvres ?",
       "Non. Il donne des extraits, des repères et des méthodes. Les œuvres de la liste A.1 doivent être lues en entier dans une édition imprimée ou sur Wikisource."),
      ("Peut-on utiliser le site sur téléphone ?",
       "Oui : la présentation se fait défiler par balayage, l'audio se lit hors classe, la transcription aide à suivre.")],
  piege="Si la connexion de la salle est lente, ne pas insister : montrer les pages depuis le poste de l'enseignant et laisser les étudiants explorer chez eux avec la page Mode d'emploi."),

"objectifs": N("5 min",
  "Lire les quatre objectifs à voix haute. Montrer les cases : chacun coche en fin de semaine ce qu'il sait faire. Expliquer l'encadré Dans la fiche du cours en écrivant au tableau : A.1 = six paires d'œuvres ; on choisit une œuvre par paire et on la lit en entier. B = la nouvelle au XIXe siècle. A.2 = anthologie personnelle de 50 extraits, à faire valider au moins 30 jours avant l'examen, sans reprendre les œuvres de A.1 ni les nouvelles de B.",
  qr=[("Que veut dire préromantisme ?",
       "Le mot désigne, après coup, la période (environ 1760-1820) où apparaissent des thèmes que le romantisme rendra centraux : mélancolie, nature sauvage, confidence du moi, rêverie. Ce n'est pas une école : aucun écrivain de l'époque ne s'est dit préromantique."),
      ("Quelle différence entre une nouvelle, un conte et un roman ?",
       "Le roman est long, avec plusieurs intrigues et une évolution des personnages. La nouvelle est brève, centrée sur un seul événement, souvent avec une fin forte (la chute) et un monde vraisemblable. Le conte est bref aussi mais accepte le merveilleux ou un ton oral. Au XIXe siècle, les auteurs mélangent souvent les mots (Maupassant appelle contes beaucoup de nouvelles).")],
  piege="Les étudiants confondent souvent A.1 et A.2. Le dire deux fois et l'écrire au tableau."),

"seances": N("3 min",
  "Présenter le rythme fixe de chaque semaine : séance A, contexte (énigme, frise, auteurs, outil) ; séance B, atelier du texte (lecture à voix haute, analyse, traduction, étape de méthode) ; séance C, nouvelle et labo IA. Chaque semaine se termine par une petite production déposée sur Studium : une trace de travail qui prépare l'écrit.",
  qr=[("Pourquoi lire à voix haute à l'université ?",
       "Parce que l'oral de l'examen comporte une lecture expressive, et parce que la voix révèle le rythme, la ponctuation et la syntaxe : on comprend mieux un texte qu'on a dit.")]),

"enigme": N("15 min",
  "Lire la question, laisser 3 minutes de réponses spontanées (l'italien est accepté pour démarrer). Noter les mots au tableau et photographier le tableau : on y reviendra en fin de semaine avec Van Tieghem et Musset. Puis donner les trois exemples : Werther (Goethe, 1774), René (Chateaubriand, 1802), Jacopo Ortis (Foscolo, 1802).",
  essentiel="Le mal du siècle est une expression qu'on doit surtout à Musset (La Confession d'un enfant du siècle, 1836) pour désigner la tristesse sans objet d'une génération née pendant la Révolution et l'Empire. On l'emploie aussi, par extension, pour les héros mélancoliques d'avant 1820. Trois causes sont classiques : 1. l'effondrement des repères (Révolution, Terreur, guerres) ; 2. la fin des carrières glorieuses après 1815 (plus d'épopée napoléonienne pour la jeunesse) ; 3. une sensibilité nouvelle venue d'Angleterre et d'Allemagne (Young, Ossian, Werther), qui valorise la mélancolie.",
  qr=[("Pourquoi toute une jeunesse européenne souffre-t-elle du même mal vers 1800 ?",
       "Parce qu'elle a grandi dans un monde qui s'est effondré (Révolution, guerres, exil) et qu'elle ne trouve plus sa place dans la société qui suit ; parce que les livres à la mode (Werther, Ossian) lui donnent un modèle pour dire cette tristesse. C'est à la fois une expérience historique et une mode littéraire."),
      ("Qui sont ces jeunes héros tristes ?",
       "Werther, jeune bourgeois allemand amoureux de Charlotte, fiancée à un autre : il se suicide (Goethe, 1774). René, jeune noble français qui erre en Europe puis s'exile chez les Natchez en Amérique (Chateaubriand, 1802). Jacopo Ortis, jeune patriote vénitien trahi par le traité de Campoformio (1797) et amoureux d'une femme promise à un autre : il se suicide (Foscolo, 1802)."),
      ("Le mal du siècle, est-ce une dépression ?",
       "Non, au sens où la littérature l'entend : c'est une catégorie littéraire et sociale, pas un diagnostic. On évite l'anachronisme médical.")],
  citations=[("Toute la maladie du siècle présent vient de deux causes ; le peuple qui a passé par 93 et par 1814 porte au cœur deux blessures.","Musset, La Confession d'un enfant du siècle, 1836, chap. II"),
             ("Tout ce qui était n'est plus ; tout ce qui sera n'est pas encore.","Musset, même chapitre"),
             ("La mélancolie devient le mal du siècle.","Van Tieghem, Le Préromantisme, p. 10")],
  piege="93 renvoie à la Terreur (1793), 1814 à la chute de Napoléon et à l'invasion de la France. Le préciser, sinon la citation reste opaque."),

"frise": N("15 min",
  "Lire la frise de gauche à droite, en racontant. Idée clé à écrire au tableau : le préromantisme n'est pas une école, c'est une étiquette posée après coup. Montrer que la politique déplace la littérature : les académies supprimées, les écrivains émigrés ou exilés, la censure impériale.",
  essentiel="Les repères à connaître : Rêveries de Rousseau (écrites en 1776-1778, publiées en 1782, quatre ans après sa mort). Paul et Virginie (1788), à la veille de la Révolution. Le 8 août 1793, la Convention supprime toutes les académies, dont l'Académie française ; l'Institut les remplace en 1795. Chateaubriand émigre et vit à Londres de 1793 à 1800 ; il publie le Génie du christianisme en avril 1802, quelques jours avant la célébration du Concordat entre Bonaparte et l'Église. Napoléon devient empereur en 1804 et contrôle la presse et les livres. De l'Allemagne de Staël est saisi et pilonné par la police en 1810, puis publié à Londres en 1813.",
  qr=[("Pourquoi tant d'œuvres françaises sont-elles écrites hors de France ?",
       "Parce que leurs auteurs sont émigrés (nobles fuyant la Révolution, comme Chateaubriand) ou exilés par Napoléon (Staël, éloignée de Paris dès 1803, installée à Coppet, au bord du lac Léman). La géographie de la littérature suit la politique."),
      ("Que perd un écrivain quand les académies disparaissent ?",
       "Un lieu de consécration, des pensions et des protecteurs. Il doit désormais chercher un public et un éditeur : c'est le début de l'écrivain moderne qui vit de ses livres et de la presse."),
      ("Pourquoi la date d'avril 1802 du Génie du christianisme est-elle intéressante pour la sociocritique ?",
       "Le livre, qui défend la beauté de la religion chrétienne, paraît au moment où Bonaparte rétablit officiellement le culte catholique (Concordat). Le texte sert une politique, et la politique sert le succès du texte.")],
  citations=[("Je considère ici la poésie classique comme celle des anciens et la poésie romantique comme celle qui tient de quelque manière aux traditions chevaleresques.","Staël, De l'Allemagne, 1810, citée par Stalloni")],
  plus="Le mot préromantisme est discuté depuis le colloque de Clermont-Ferrand (1972) : Le Préromantisme, hypothèque ou hypothèse ?, dir. Paul Viallaneix (Klincksieck, 1975). Stalloni parle d'un entre-deux littéraire (1790-1820).",
  source=f"Viallaneix (dir.), 1975 ; Van Tieghem, chap. I ; {STAL}, « Prélude au Romantisme »."),

"auteurs": N("25 min",
  "Quatre groupes, un auteur par groupe : 5 minutes de lecture de la fiche (Studium), 1 minute de présentation par groupe. L'enseignant complète avec une idée par auteur, pas plus.",
  essentiel="Rousseau (1712-1778) : Genevois, auteur de La Nouvelle Héloïse (1761, immense succès sentimental), des Confessions et des Rêveries ; il fait de l'intimité un sujet littéraire. Bernardin de Saint-Pierre (1737-1814) : disciple de Rousseau, Paul et Virginie (1788) raconte l'amour de deux enfants élevés dans la nature à l'île de France (aujourd'hui Maurice), colonie où travaillent des esclaves. Chateaubriand (1768-1848) : petit noble breton, voyage en Amérique (1791), émigré, puis grand écrivain et homme politique (ministre sous la Restauration) ; René est son héros mélancolique. Germaine de Staël (1766-1817) : fille de Necker, ministre de Louis XVI ; elle tient un salon, s'oppose à Napoléon, voyage en Allemagne et en Italie (Corinne ou l'Italie, 1807) et fait connaître les littératures du Nord.",
  qr=[("Pour Paul et Virginie : qui travaille dans ce paradis ?",
       "Des esclaves noirs, en particulier Domingue et Marie, les serviteurs des deux familles. L'idylle repose sur une société esclavagiste que le roman montre sans la remettre en cause : c'est ce que la sociocritique appelle le non-dit du texte."),
      ("Qu'ont en commun ces quatre auteurs ?",
       "Ils déplacent la littérature vers le moi, la nature et le sentiment ; trois sur quatre écrivent en partie hors de Paris ou hors de France ; tous sont pris dans les bouleversements politiques de 1789-1815."),
      ("Pourquoi Staël compte-t-elle pour un public italien ?",
       "Elle écrit Corinne ou l'Italie (1807) et, en 1816, un article publié à Milan qui pousse les Italiens à traduire les littératures étrangères : il lance la querelle entre classiques et romantiques en Italie.")],
  citations=[("Elle avait lu Paul et Virginie et elle avait rêvé la maisonnette de bambous, le nègre Domingo, le chien Fidèle…","Flaubert, Madame Bovary, 1857, I, 6 (le mot nègre est celui de 1857 ; le dire et l'expliquer)")],
  piege="Ne pas transformer la séance en biographies : une idée par auteur suffit. La citation de Madame Bovary annonce la semaine 4 : Emma est une lectrice formée par les livres de cette semaine."),

"outil": N("15 min",
  "Présenter les trois questions comme un outil de lecture, pas comme une théorie : Dire (que dit le texte de sa société ?), Former (comment le dit-il : genre, langue, figures ?), Taire (que tait-il ?). Les appliquer tout de suite à Paul et Virginie : société de référence (une colonie), forme (une idylle pastorale), non-dit (le travail servile).",
  essentiel="La sociocritique est une méthode née autour de 1970 (Claude Duchet) : elle lit la société dans le texte lui-même, dans sa langue, ses formes et ses silences, et non dans la biographie de l'auteur. Pierre Zima y ajoute l'étude des langages sociaux (sociolectes, semaine 6) ; Pierre Bourdieu, sociologue, étudie le champ littéraire (semaine 2). Le modèle de lecture de l'enseignant comporte quatre niveaux : contextuel (le moment historique), socio-idéologique (les valeurs et les discours), socio-historique (les institutions, la presse, les tribunaux), socio-identitaire (qui parle, depuis quelle place, quelle identité) ; les trois questions de la diapositive en sont la version simple.",
  qr=[("Quelle différence entre la sociocritique et la biographie ?",
       "La biographie explique le texte par la vie de l'auteur. La sociocritique part du texte (sa langue, ses formes, ses silences) et y lit la société ; l'auteur n'est qu'un élément du contexte."),
      ("Que tait Paul et Virginie ?",
       "Le travail des esclaves et la violence coloniale qui rendent possible le bonheur des deux familles."),
      ("Peut-on appliquer ces trois questions à un poème ?",
       "Oui, c'est ce qu'on fera avec Le Lac (semaine 2) : la forme (alexandrins et vers courts) dit aussi quelque chose du rapport au temps d'une société.")],
  piege="Sociocritique ne veut pas dire sociologie de la littérature : on lit d'abord le texte.",
  source="Claude Duchet, « Pour une socio-critique ou variations sur un incipit », Littérature, n° 1, 1971 ; G. Dinar, thèse de doctorat, Université Pamukkale, 2025 (modèle à quatre niveaux)."),

"critique-vantieghem": N("20 min, séance A ou C",
  "Lire les deux citations à voix haute. Expliquer la thèse en trois temps : 1. le préromantisme est une transition (de 1750 environ au début de la Restauration, 1815) ; 2. il change d'abord la sensibilité, ensuite seulement le goût et les formes ; 3. Rousseau en est le type, Staël et Chateaubriand les maîtres immédiats du romantisme. Insister sur la page 7 : La Nouvelle Héloïse fait passer en littérature ce qui restait dans les journaux intimes et les lettres privées.",
  essentiel="Philippe Van Tieghem (1898-1990) est un historien de la littérature de l'après-guerre ; son Que sais-je ? est une synthèse claire et commode. Sa méthode est celle de l'histoire des idées et de la sensibilité : il explique la littérature par une évolution psychologique de la civilisation. La sociocritique ne rejette pas cette explication, elle la complète par les institutions (académies, presse, censure), le public et le marché du livre.",
  qr=[("Une histoire de la sensibilité suffit-elle à expliquer une littérature ?",
       "Non. Van Tieghem décrit bien les thèmes (mélancolie, nature, ruines), mais il ne dit presque rien de qui écrit, pour qui, où et dans quelles conditions. Il mentionne des causes économiques et politiques (p. 7) sans les étudier : c'est exactement là qu'intervient la sociocritique (exil, censure, fin des académies, naissance d'un public)."),
      ("Le mot préromantisme juge-t-il le XVIIIe siècle à partir de la suite ?",
       "Oui : il présente des œuvres comme des annonces du romantisme, comme si elles n'avaient de valeur que par ce qui vient après. C'est une illusion rétrospective, que Stalloni signale aussi."),
      ("Où sont le public, l'exil, la censure, le marché du livre ?",
       "Absents ou presque de l'article. Le public : les nombreuses lectrices et lecteurs qui écrivent à Rousseau après La Nouvelle Héloïse. L'exil : Chateaubriand à Londres, Staël à Coppet. La censure : De l'Allemagne pilonné en 1810. Le marché : la librairie qui remplace les pensions royales.")],
  citations=[("Le Préromantisme est donc une évolution de la sensibilité suivie d'une évolution du goût littéraire.","Van Tieghem, p. 6"),
             ("On habite avec un cœur plein un monde vide, et sans avoir usé de rien, on est désabusé de tout.","Chateaubriand, Génie du christianisme, 1802, « Du vague des passions »")],
  piege="Ne pas disqualifier l'article : c'est une synthèse claire et une très bonne carte des thèmes. On le discute, on ne le rejette pas.",
  plus="Faire relever les métaphores de Van Tieghem (germe, fleurs, climat classique) : le critique écrit lui-même en style préromantique, ce qui est un bon exercice de lecture critique.",
  source="Van Tieghem, Le Romantisme français, PUF, Que sais-je ?, chap. I, p. 5-14 (Cairn)."),

"critique-vantieghem-frise": N("10 min",
  "Montrer que la sensibilité nouvelle arrive par les traductions : Young traduit par Le Tourneur (1769), Werther traduit en français dès 1776. S'arrêter sur Ossian : ces poèmes, présentés comme des chants gaéliques anciens d'un barde du IIIe siècle, sont en grande partie composés par l'Écossais James Macpherson (1760-1763). Toute l'Europe les admire, Napoléon compris.",
  qr=[("Pourquoi la France importe-t-elle sa sensibilité ?",
       "Selon Van Tieghem (p. 12), parce que le classicisme pèse plus lourd en France qu'ailleurs : l'Angleterre et l'Allemagne ont moins de règles, plus de liberté pour le sentiment. Staël dit la même chose en opposant le Nord (sensibilité, liberté) et le Midi (règles, tradition)."),
      ("Quel rapport entre Ossian et nos labos IA ?",
       "Ossian est un faux ancien qui a convaincu tout un continent pendant des décennies. La vérification des sources n'est donc pas un problème né avec l'IA : un texte crédible n'est pas un texte vrai.")],
  source="Van Tieghem, p. 12-13."),

"texte1": N("30 min, séance B",
  "Lecture par trois étudiants, avec des intonations différentes. Puis relevé au tableau. Lire ensuite la phrase suivante du texte (Le plus sociable et le plus aimant des humains en a été proscrit par un accord unanime) : elle donne la clé.",
  essentiel="Les Rêveries du promeneur solitaire sont le dernier livre de Rousseau, écrit à la fin de sa vie (1776-1778) alors qu'il se croit victime d'un complot universel. Dix promenades, une méditation par promenade. La Première promenade commence par cette phrase. Le contexte : Rousseau a été condamné (l'Émile est brûlé en 1762), chassé de plusieurs villes, brouillé avec les philosophes.",
  qr=[("Énonciation : qui parle ? Comment le je est-il mis en valeur ?",
       "Rousseau lui-même, à la première personne. Le je est mis en valeur par la position finale de moi-même, à la fin de la phrase, après une longue liste de ce qu'il n'a plus : tout disparaît, il ne reste que lui."),
      ("Rythme : repérez l'énumération. Que produit-elle ?",
       "Frère, prochain, ami, société : quatre noms, des liens les plus proches aux plus larges. L'énumération vide progressivement le monde autour du je, et la phrase se referme sur moi-même. Le rythme mime l'isolement."),
      ("Société : que dit cette solitude de la société du temps ?",
       "Elle dit une société qui exclut : Rousseau se présente comme rejeté par tous (l'accord unanime de la phrase suivante). Elle dit aussi un renversement nouveau : l'exclu devient le héros, la solitude devient une valeur et une source d'écriture."),
      ("Que met en valeur la place de moi-même ? Qui est responsable de cette solitude selon le texte ?",
       "L'isolement total et la chute de la phrase sur le moi. La faute est rejetée sur la société : Rousseau se dit victime, jamais responsable.")],
  citations=[("Me voici donc seul sur la terre, n'ayant plus de frère, de prochain, d'ami, de société que moi-même.","Rousseau, Rêveries, Première promenade"),
             ("Le plus sociable et le plus aimant des humains en a été proscrit par un accord unanime.","phrase suivante")],
  piege="Le je de Rousseau n'est pas neutre : le texte construit sa propre innocence. C'est une très bonne réponse à la question Que tait-il ? (sa part dans les conflits).",
  plus="Comparer avec une traduction italienne publiée (Fantasticherie del passeggiatore solitario) et faire repérer ce qui se perd dans l'énumération."),

"texte2": N("30 min, séance B",
  "Trois lecteurs pour la phrase des orages, du plus calme au plus exalté. Puis analyse. Raconter l'histoire de René en deux minutes avant l'analyse.",
  essentiel="René (1802) est un récit bref inséré dans le Génie du christianisme pour illustrer le chapitre Du vague des passions. Le jeune René, réfugié chez les Indiens Natchez en Louisiane, raconte sa vie au vieux sage Chactas et au missionnaire, le père Souël : enfance en Bretagne, voyages, ennui, désir de mort, puis l'aveu de sa sœur Amélie, qui entre au couvent en révélant une passion coupable pour son frère. À la fin, le père Souël condamne sévèrement l'orgueil et la rêverie de René : le livre se présente comme une mise en garde, mais toute une génération s'identifiera au héros.",
  qr=[("René parle de lui à la troisième personne : pourquoi ?",
       "Il se regarde souffrir, comme un personnage de roman : c'est une mise en scène de soi (on parle d'énallage de personne). Il se voit déjà comme un héros emporté par le destin."),
      ("Apostrophe et impératif : à qui s'adresse-t-il ?",
       "Aux orages, personnifiés par l'apostrophe et commandés par l'impératif (Levez-vous). Il s'adresse à la nature comme à une puissance capable de le délivrer de sa vie présente."),
      ("Comment dire orages désirés en italien ?",
       "Plusieurs choix sont possibles : tempeste desiderate (fidèle), desiderate tempeste (l'adjectif placé avant donne un registre poétique), bramate tempeste (bramare est plus fort et plus littéraire que desiderare). Orage se traduit mieux par tempesta que par temporale, trop météorologique. Une bonne réponse : Levatevi presto, desiderate tempeste."),
      ("Que cherche René dans l'orage ?",
       "Une autre vie, un ailleurs, peut-être la mort : le paradoxe est de désirer ce qui détruit. C'est le cœur du vague des passions : un désir sans objet précis.")],
  citations=[("Levez-vous vite, orages désirés, qui devez emporter René dans les espaces d'une autre vie !","Chateaubriand, René, 1802"),
             ("Si René n'existait pas, je ne l'écrirais plus ; s'il m'était possible de le détruire, je le détruirais.","Chateaubriand, Mémoires d'outre-tombe")],
  piege="Ne pas confondre René et Chateaubriand : l'auteur a pris ses distances avec son héros, comme le montre la citation des Mémoires d'outre-tombe.",
  source="Chateaubriand, René, 1802 ; Van Tieghem, p. 10 (vagues passions, ardentes chez Chateaubriand)."),

"methode": N("20 min",
  "Chacun écrit son hypothèse sur une feuille selon le modèle Ce texte montre…, grâce à… Lire cinq hypothèses, les améliorer ensemble au tableau. Annoncer la progression du semestre : huit étapes jusqu'au commentaire complet de la semaine 8.",
  essentiel="Le commentaire littéraire à la française (épreuve écrite de l'examen) suit un ordre fixe : introduction (amorce, présentation du passage, problématique, annonce du plan), deux ou trois parties argumentées, conclusion (réponse et ouverture). Tout part d'une hypothèse de lecture : une phrase qui dit ce que fait le texte et par quels moyens.",
  qr=[("Une phrase pour René : Ce texte montre…, grâce à…",
       "Exemple de bonne réponse : Ce texte montre un héros qui désire sa propre perte et se met en scène comme un personnage, grâce à l'apostrophe aux orages, à l'impératif et à la troisième personne."),
      ("Pourquoi lire deux fois avant d'analyser ?",
       "La première lecture donne le sens général et l'émotion ; la seconde, à voix haute, fait apparaître les procédés (rythme, ponctuation, répétitions). On évite ainsi de plaquer des idées toutes faites.")],
  piege="Les hypothèses trop générales (Ce texte parle de la tristesse) : demander toujours grâce à quoi."),

"nouvelle": N("30 min, séance C",
  "Définir simplement la nouvelle : brièveté, une seule action, unité d'effet, chute. Rappeler que la fiche du cours consacre toute la partie B à la nouvelle du XIXe siècle. Préciser le statut de René et présenter le parcours des huit semaines (bas de la diapositive).",
  essentiel="La nouvelle moderne se fixe au XIXe siècle grâce à la presse : journaux et revues ont besoin de textes courts, qui se lisent en une fois. Stalloni note que l'invention de la nouvelle dans sa forme moderne date de l'époque romantique, liée au récit fantastique (Nodier, Mérimée, Gautier). Au XIXe siècle, beaucoup de nouvelles paraissent d'abord dans un journal, puis sont réunies en recueil (Mosaïque de Mérimée, 1833 ; Contes du lundi de Daudet, 1873). Le parcours du semestre : Mérimée (S2), Gautier (S3), Flaubert (S4), Maupassant, Daudet, Barbey (S5), Villiers (S6).",
  qr=[("Nouvelle, conte, récit : quelle différence ?",
       "Le récit est le terme le plus large (toute histoire racontée). Le conte accepte le merveilleux et garde souvent un ton oral (il était une fois). La nouvelle vise le vraisemblable, se concentre sur un événement et une fin forte."),
      ("René est-il une nouvelle ?",
       "Pas au sens strict : c'est un récit bref enchâssé dans un essai (le Génie du christianisme), publié à part en 1805 avec Atala. Il a la brièveté de la nouvelle, mais pas sa chute ni son unité d'action."),
      ("Pourquoi la nouvelle naît-elle dans les journaux ?",
       "Parce qu'un journal a besoin de textes complets dans un seul numéro, et que les écrivains sont payés à la ligne : la nouvelle est à la fois une forme artistique et un produit de presse.")],
  piege="Les frontières entre genres sont discutées : un genre est un nom donné après coup, comme préromantisme. Le dire, sans entrer dans la théorie.",
  source="Grojnowski, Lire la nouvelle, Dunod, 1993 ; Schaeffer, Qu'est-ce qu'un genre littéraire ?, Seuil, 1989 ; Stalloni, « Le Romantisme », Les formes et les œuvres."),

"labo": N("40 min, séance C",
  "Vérifier que chacun ouvre le lien de l'Atelier du siècle (claude.ai, connecté à son compte) ; sinon projeter depuis le poste de l'enseignant et travailler en grand groupe. Binômes. Prompt modèle : René, pourquoi appelles-tu les orages ? Puis chaque binôme remplit la première ligne du carnet de vérification IA : question posée, affirmation de l'IA, vérification (page de l'édition), verdict (vrai, faux, inventé).",
  essentiel="L'Atelier du siècle simule des écrivains : ce sont des hypothèses de lecture, pas des témoins. La charte du cours tient en quatre verbes : déclarer (dire ce que l'IA a fait), vérifier (dates, citations, attributions dans l'édition), écrire soi-même, rester critique. On suit les trois gestes du labo : demander, vérifier, améliorer.",
  qr=[("Quelle affirmation de l'IA avez-vous pu vérifier dans le texte ?",
       "Par exemple : René est le frère d'Amélie (vrai) ; René raconte son histoire à Chactas et au père Souël (vrai) ; René se suicide à la fin (faux : il meurt plus tard, massacré chez les Natchez, ce que le récit annonce seulement)."),
      ("Laquelle n'a pas de source ?",
       "Souvent une citation inventée qui ressemble au style de Chateaubriand, ou une date approximative. Toute citation sans page est suspecte."),
      ("Peut-on rendre un texte écrit par l'IA ?",
       "Non. On peut déclarer avoir utilisé l'IA pour chercher ou vérifier, mais le texte rendu est écrit par l'étudiant.")],
  piege="Erreurs fréquentes de l'IA : citations inventées, dates approximatives, René confondu avec Les Natchez (où il réapparaît), Amélie présentée comme amante et non comme sœur. Saluer chaque erreur trouvée : on forme des lecteurs vigilants.",
  plus="Rapprocher de la diapositive Ossian : un texte crédible n'est pas un texte vrai."),

"italia": N("15 min",
  "Demander qui a lu Foscolo au lycée (souvent tous) : c'est un levier de motivation. Lire René et Ortis côte à côte.",
  essentiel="Ugo Foscolo (1778-1827), né à Zante, publie l'édition de 1802 des Ultime lettere di Jacopo Ortis, roman par lettres inspiré de Werther : Jacopo, patriote vénitien, voit sa patrie livrée à l'Autriche par Bonaparte (traité de Campoformio, 1797) et aime Teresa, promise à un autre ; il se suicide. En janvier 1816, Staël publie à Milan, dans la Biblioteca italiana, Sulla maniera e la utilità delle traduzioni : elle conseille aux Italiens de traduire les littératures étrangères. L'article déclenche la querelle entre classiques et romantiques (Berchet, Lettera semiseria, 1816).",
  qr=[("Qu'est-ce qui rapproche Ortis de René ?",
       "Deux jeunes héros de 1802, mélancoliques, exilés, amoureux sans issue, qui écrivent leur souffrance à la première personne."),
      ("Qu'est-ce qui les sépare ?",
       "Ortis souffre d'une patrie blessée (la question politique est centrale) et se suicide ; René souffre d'un vague des passions sans objet politique et ne se suicide pas. Deux douleurs, deux patries : l'une politique, l'autre existentielle et religieuse.")]),

"bilan": N("10 min",
  "Revenir à la photo du tableau de l'énigme et lire la citation de Van Tieghem sur la mélancolie, puis celle de Musset sur les deux blessures. Rappeler la fiche de lecture sur René à déposer sur Studium et les deux extraits pour l'anthologie A.2. Annoncer la bataille d'Hernani et répartir les deux camps dès maintenant.",
  qr=[("Quelle est la réponse à l'énigme de la semaine ?",
       "Une jeunesse sans place après la Révolution et l'Empire (Musset), et une sensibilité importée du Nord qui donne une forme à cette souffrance (Van Tieghem). Les deux explications se complètent : l'histoire et la littérature."),
      ("Que faut-il lire pour la semaine 2 ?",
       "Le Lac de Lamartine (Studium) et Mateo Falcone de Mérimée (une dizaine de pages).")]),
}

# =====================================================================  S2
NOTES[2] = {
"cover": N("3 min",
  "Annoncer une semaine double : le champ littéraire (qui gagne la place en 1830 ?) et la technique du vers, base de l'écrit de commentaire. Vérifier que les fiches de René sont déposées.",
  essentiel="Entre 1820 et 1836, le romantisme devient une école et gagne la bataille contre les classiques. Les dates clés : Méditations poétiques de Lamartine (1820), Préface de Cromwell de Hugo (1827), première d'Hernani (25 février 1830), révolution de Juillet (27-29 juillet 1830), Chatterton de Vigny (1835), Confession d'un enfant du siècle de Musset (1836). La nouvelle de la semaine, Mateo Falcone (1829), montre un autre visage de l'époque : sécheresse, violence, exotisme corse.",
  qr=[("Pourquoi parler de bataille pour une école littéraire ?",
       "Parce que le romantisme s'impose par des conflits publics : préfaces polémiques, salles de théâtre où l'on se bat, journaux qui s'insultent. Stalloni écrit que l'histoire du romantisme s'est écrite sur le mode du conflit.")]),

"objectifs": N("5 min",
  "Insister sur la paire 1 de la liste A.1 : Lamartine (Méditations poétiques) ou René Vivien (Études et préludes, semaine 7). Ceux qui choisissent Lamartine commencent la lecture intégrale cette semaine.",
  qr=[("Faut-il lire tout le recueil des Méditations ?",
       "Oui, si on choisit Lamartine dans la paire 1 : c'est un recueil de 24 poèmes dans l'édition originale de 1820, lisible en quelques heures. Sinon on lira Vivien.")],
  piege="Le compte des syllabes est souvent nouveau pour des italianistes : rassurer, on avance pas à pas avec trois règles seulement."),

"seances": N("3 min",
  "A : le champ littéraire et Hernani, avec la lecture critique de Stalloni sur les cénacles. B : Le Lac, en entier, avec la scansion. C : Mateo Falcone, labo IA, jeu d'Hernani.",
  qr=[("Qu'est-ce qu'un cénacle ?",
       "Un petit groupe d'écrivains et d'artistes qui se réunit régulièrement chez l'un d'eux (le mot vient de la salle de la Cène). Pour le romantisme : l'Arsenal de Nodier, puis le salon de Hugo rue Notre-Dame-des-Champs.")]),

"enigme": N("10 min",
  "Raconter la première du 25 février 1830 comme une scène : les partisans de Hugo arrivent des heures avant le lever de rideau, cheveux longs, vêtements voyants ; Gautier, 18 ans, porte un vêtement rouge resté célèbre ; les classiques sifflent, rient, interrompent ; on se dispute à chaque vers pendant des semaines de représentations. Hugo a 27 ans (28 le lendemain).",
  essentiel="Hernani est un drame en vers : en Espagne, au XVIe siècle, le bandit Hernani, le roi Don Carlos (futur empereur Charles Quint) et le vieux Don Ruy Gomez aiment la même femme, doña Sol. Hernani et doña Sol meurent empoisonnés le soir de leurs noces. La pièce viole les règles classiques : mélange du sublime et du grotesque, unités de temps et de lieu abandonnées, vers disloqués, héros hors-la-loi.",
  qr=[("Comment une pièce de théâtre peut-elle déclencher une bagarre ?",
       "Parce qu'à la Comédie-Française, théâtre officiel, une pièce est un enjeu de pouvoir : qui définit le bon goût ? Les classiques défendent les règles héritées de Racine ; une nouvelle génération veut prendre leur place. Le public se divise en camps, comme dans un stade."),
      ("Qu'est-ce qui pouvait choquer dans Hernani ?",
       "Dès le premier vers, un enjambement (escalier / Dérobé) casse l'alexandrin classique ; un roi est ridiculisé et caché dans une armoire ; un bandit est le héros ; le vocabulaire familier entre dans la tragédie ; les unités de temps et de lieu ne sont pas respectées."),
      ("Qui a gagné la bataille ?",
       "Les romantiques : la pièce est jouée une quarantaine de fois avec succès, et le romantisme devient l'école dominante. La révolution de Juillet, cinq mois plus tard, confirme le changement d'époque.")],
  citations=[("Serait-ce déjà lui ? C'est bien à l'escalier / Dérobé.","Hugo, Hernani, I, 1, premiers vers")],
  piege="Le gilet rouge est la version de la légende ; dans son Histoire du romantisme (1874), Gautier parle d'un pourpoint de satin cerise ou rose. On peut dire : un vêtement rouge vif."),

"frise": N("10 min",
  "Lire la frise comme une conquête : de la préface (1827) à la victoire (1830), puis le malaise de la génération suivante (Musset, 1836). Ajouter oralement Stendhal, Racine et Shakespeare (1823-1825), premier texte théorique.",
  essentiel="Mérimée publie Mateo Falcone dans la Revue de Paris en mai 1829 : les revues sont le lieu où l'on lance les jeunes auteurs. La révolution de Juillet 1830 chasse Charles X et installe Louis-Philippe : une monarchie bourgeoise commence, dominée par l'argent (semaine 3).",
  qr=[("Pourquoi 1830 est-elle une date doublement révolutionnaire ?",
       "Hernani en février (révolution esthétique) et la révolution de Juillet, du 27 au 29 juillet (révolution politique), la même année."),
      ("Pourquoi la frise s'arrête-t-elle sur Musset en 1836 ?",
       "Parce que Musset, le plus jeune, nomme le malaise d'une génération arrivée après la victoire : le romantisme triomphe, mais la jeunesse reste sans place.")],
  plus="Paul Bénichou, Le Sacre de l'écrivain (1973) : comment l'écrivain devient, entre 1750 et 1830, une autorité spirituelle laïque, une sorte de prêtre moderne."),

"auteurs": N("20 min",
  "Une idée par auteur, et une position dans le champ. Dessiner au tableau quatre positions : le chef (Hugo), l'intime (Lamartine), le solitaire (Vigny), le rebelle désenchanté (Musset).",
  essentiel="Lamartine (1790-1869) : immense succès des Méditations poétiques (1820), puis carrière politique ; il proclame la République en février 1848 et devient brièvement ministre des Affaires étrangères. Hugo (1802-1885) : chef de file du romantisme dès 1827, poète, dramaturge, romancier (Notre-Dame de Paris, 1831), puis opposant à Napoléon III et exilé à Jersey et Guernesey de 1851 à 1870. Vigny (1797-1863) : officier, poète stoïque ; Chatterton (1835) montre un jeune poète poussé au suicide par une société d'argent. Musset (1810-1857) : le plus jeune, poète et dramaturge (Lorenzaccio, 1834) ; La Confession d'un enfant du siècle (1836).",
  qr=[("Quelle position chacun occupe-t-il : chef, solitaire, héritier, rebelle ?",
       "Hugo : le chef, qui écrit les préfaces et mène la bataille. Lamartine : l'aîné consacré, voix intime de l'élégie. Vigny : le solitaire, qui pense le poète comme un exclu (Chatterton). Musset : le jeune rebelle désenchanté, qui se moque même du romantisme (Lettres de Dupuis et Cotonet)."),
      ("Pourquoi Musset se moque-t-il du mot romantisme ?",
       "Parce qu'en 1836 le mot est partout et ne veut plus rien dire : c'est un signe de victoire de l'école, et de distance de la nouvelle génération.")],
  citations=[("Nous en vînmes à croire que ce mot de romantisme n'était qu'un mot : nous le trouvions beau, et il nous semblait que c'était dommage qu'il ne voulût rien dire.","Musset, Lettres de Dupuis et Cotonet, 1836, cité par Stalloni")]),

"outil": N("25 min",
  "Dessiner au tableau deux axes : installés contre nouveaux venus ; consécration institutionnelle (Académie, Comédie-Française) contre reconnaissance des pairs (cénacles). Placer l'Académie, les classiques, Hugo, Lamartine, Musset, Vigny. Expliquer qu'une prise de position (préface, pièce, manifeste) déplace un acteur sur la carte.",
  essentiel="Pierre Bourdieu (1930-2002), sociologue, décrit la littérature comme un champ : un espace social où des agents (écrivains, éditeurs, critiques, académies) luttent pour la reconnaissance et pour le pouvoir de définir ce qui est littéraire. Chacun occupe une position (installé ou nouveau venu, consacré ou marginal) et agit par des prises de position (œuvres, préfaces, manifestes). Les nouveaux venus ont intérêt à la rupture ; les installés, à la conservation. Les Règles de l'art (1992) étudient surtout Flaubert et Baudelaire (semaine 4).",
  qr=[("Hernani est-il seulement une pièce ?",
       "Non : c'est un coup dans un jeu. Une génération prend position contre une autre et conquiert la scène la plus prestigieuse de France."),
      ("Pourquoi les nouveaux venus choisissent-ils la rupture ?",
       "Parce qu'ils n'ont rien à perdre dans l'ordre établi : en changeant les règles, ils rendent caduque la position des installés et créent leur propre place."),
      ("Où placer l'Académie française en 1830 ?",
       "Du côté des installés et de la conservation : elle défend les règles classiques. Hugo n'y entrera qu'en 1841, après plusieurs échecs : la consécration institutionnelle vient après la victoire dans le champ.")],
  piege="Le champ n'est pas un simple milieu ou décor : c'est un espace de luttes pour la définition de la bonne littérature.",
  source="P. Bourdieu, Les Règles de l'art, Seuil, 1992 ; « Le champ littéraire », Actes de la recherche en sciences sociales, n° 89, 1991."),

"critique-stalloni-romantisme": N("20 min, séance A",
  "Présenter Stalloni comme un manuel universitaire récent, clair, qui sert de carte. Lire les deux citations. Puis les quatre idées : deux sens du mot, l'histoire du mot, les cénacles, les manifestes. Faire le lien avec l'outil de Bourdieu : une école existe d'abord par des lieux, des revues et des amitiés.",
  essentiel="Yves Stalloni, professeur de classes préparatoires, a écrit Écoles et courants littéraires (Armand Colin, coll. Cursus), un manuel qui présente chaque mouvement par son nom, ses dates, ses groupes, ses textes et son esthétique. Pour le romantisme, il distingue le romantisme éternel (une sensibilité qui existe à toutes les époques, selon Henri Peyre) et le romantisme historique, l'école de 1820 (Méditations) à 1843 (échec des Burgraves de Hugo). Il rappelle l'origine du mot : romantique vient du roman (italien romanzesco), passe par l'anglais et l'allemand, et Staël l'oppose à classique en 1810. Il décrit cinq foyers : l'Abbaye-aux-Bois (salon de Mme Récamier et Chateaubriand), l'Arsenal (Nodier, à partir de 1824), la rue Notre-Dame-des-Champs (Hugo, 1827), le petit Cénacle (1829, Petrus Borel, Nerval, Gautier), le Doyenné (bohème de Nerval et Gautier).",
  qr=[("Une école se définit-elle par une doctrine, ou par des lieux, des revues et des amitiés ?",
       "Par les deux, mais Stalloni montre que les lieux viennent d'abord : les cénacles se font et se défont selon les affinités littéraires et les convictions politiques. La doctrine (Préface de Cromwell) arrive pour légitimer un groupe déjà formé. C'est la thèse de Bourdieu : une école est un groupe qui lutte pour une position."),
      ("Pourquoi les romantiques sont-ils d'abord royalistes, puis libéraux ?",
       "Dans les années 1820, les jeunes Hugo et Lamartine sont royalistes et catholiques ; les libéraux défendent alors le goût classique (Stendhal est une exception). Vers 1827-1830, le romantisme rejoint le libéralisme : Hugo écrit dans la préface d'Hernani que le romantisme est le libéralisme en littérature. Balzac s'en amuse dans Illusions perdues."),
      ("Que veut dire romantique à l'origine ?",
       "Ce qui ressemble aux romans de chevalerie : merveilleux, pittoresque, éloigné des règles.")],
  citations=[("Le romantisme, tant de fois mal défini, n'est, à tout prendre, et c'est là sa définition réelle, […] que le libéralisme en littérature.","Hugo, préface d'Hernani, 1830, cité par Stalloni"),
             ("Les Royalistes sont romantiques, les libéraux sont classiques.","Balzac, Illusions perdues, cité par Stalloni"),
             ("Ces divers groupements ou cénacles sont composés, et parfois recomposés, à partir d'affinités littéraires autant que de convictions politiques.","Stalloni")],
  piege="Stalloni date la fin du romantisme historique de 1843 (échec des Burgraves) : c'est une convention de manuel. Bien dire aux étudiants que les dates d'école sont des repères, pas des frontières.",
  source=f"{STAL}, « Le Romantisme ». Henri Peyre, Qu'est-ce que le romantisme ?, PUF, 1979 ; Max Milner, Le Romantisme I, Arthaud, 1973."),

"critique-stalloni-romantisme-frise": N("10 min",
  "Lire la frise des cénacles et des revues : on voit l'école se construire en dix ans. Chaque date est un lieu ou un journal. Demander aux étudiants de repérer les deux dates en bleu.",
  qr=[("Que montrent les deux dates en bleu (1824, 1829) ?",
       "Des institutions de groupe : un salon (l'Arsenal de Nodier) et un journal (Le Globe, libéral) en 1824 ; une bande de jeunes artistes (le petit Cénacle) en 1829. Sans ces lieux, pas de bataille d'Hernani."),
      ("Pourquoi Le Globe compte-t-il ?",
       "C'est un journal libéral fondé en 1824 où écrit le jeune Sainte-Beuve ; il fait le lien entre romantisme et libéralisme. Plus tard il devient saint-simonien (socialisme utopique).")]),

"texte1": N("60 min, séance B",
  "1. Lecture expressive par trois lecteurs (15 min). 2. Scansion au tableau de la strophe (20 min). 3. Analyse : mètre, figures, thème (15 min). 4. Traduction italienne de la strophe en gardant l'alternance long / court (10 min).",
  essentiel="Le Lac est le poème le plus célèbre des Méditations (1820). Lamartine l'écrit en 1817 : il revient seul au lac du Bourget (Savoie), où il a aimé l'année précédente Julie Charles, gravement malade, qui n'a pas pu venir et meurt en décembre 1817. Dans le poème, elle s'appelle Elvire. La strophe Ô temps est la voix de la femme aimée, rapportée par le poète : le mètre change à ce moment, on passe de strophes de trois alexandrins et un vers de six syllabes à une alternance régulière 12 / 6 / 12 / 6.",
  qr=[("Mètre : comptez. Que produit l'alternance 12 / 6 ?",
       "Ô / temps / sus / pends / ton / vol // et / vous / heu / res / pro / pi(ces) = 12 ; Sus / pen / dez / vo / tre / cours = 6 ; Lais / sez / nous / sa / vou / rer // les / ra / pi / des / dé / li(ces) = 12 ; Des / plus / beaux / de / nos / jours = 6. Le vers court arrête le mouvement du vers long : la forme mime la suspension demandée au temps."),
      ("Figures : apostrophe et personnification. À qui parle le poète ?",
       "C'est la femme aimée qui parle, et elle s'adresse au temps et aux heures, personnifiés : on leur parle comme à des personnes capables d'entendre, avec l'impératif (suspends, suspendez, laissez-nous)."),
      ("Thème : que demande-t-il au temps ? Peut-il l'obtenir ?",
       "D'arrêter son cours pour prolonger le bonheur des amants. Non : le poème montre que le temps ne s'arrête pas, et confie à la nature (le lac, les rochers) la mémoire de l'amour."),
      ("Qui parle dans cette strophe ?",
       "La voix de la femme aimée (Elvire), que le poète cite de mémoire : c'est un souvenir dans le souvenir.")],
  citations=[("Ainsi, toujours poussés vers de nouveaux rivages, / Dans la nuit éternelle emportés sans retour…","Lamartine, Le Lac, premiers vers"),
             ("Je suis le premier qui ai fait descendre la poésie du Parnasse…","Lamartine, première préface des Méditations, 1849, citée par Stalloni")],
  piege="Erreur fréquente : compter le e final des rimes féminines (propices, délices) ; il ne compte jamais en fin de vers. Le e de heures, lui, compte, car il est suivi d'une consonne (propices).",
  plus="Les rimes sont croisées : propices / délices (féminines, terminées par un e muet) alternent avec cours / jours (masculines)."),

"texte2": N("20 min, séance A",
  "Lire la phrase de Hugo, puis expliquer la Préface de Cromwell en quatre points : contre les règles et les unités ; pour le drame qui mêle le grotesque et le sublime ; liberté totale de l'art ; le théâtre comme miroir de la nature. Lire aussi la phrase suivante de la préface (abattre le vieux plâtre qui masque la façade de l'art).",
  essentiel="Cromwell (1827) est une pièce immense, injouable (plus de 6 000 vers) ; sa préface compte davantage que la pièce. Hugo y propose une histoire de la poésie en trois âges (lyrique, épique, dramatique) et réclame un théâtre qui mêle le grotesque et le sublime, comme Shakespeare. C'est le manifeste du romantisme.",
  qr=[("Image : quel outil ? Que veut-il briser ?",
       "Le marteau, outil de démolition. Il veut briser les théories, les poétiques et les systèmes, c'est-à-dire les règles classiques (unités, séparation des genres, bienséances)."),
      ("Champ : qui sont les anciens, qui sont les modernes ?",
       "Les anciens : les défenseurs des règles classiques, l'Académie, les critiques des journaux conservateurs, les héritiers de Boileau. Les modernes : Hugo et le cénacle romantique, les jeunes."),
      ("Acte : une préface peut-elle être une prise de position ?",
       "Oui : elle n'explique pas seulement une pièce, elle déclare la guerre et désigne un chef. Au sens de Bourdieu, c'est un coup dans le champ."),
      ("Qui est visé par le marteau ?",
       "Les règles classiques, Boileau, les théoriciens et l'Académie.")],
  citations=[("Mettons le marteau dans les théories, les poétiques et les systèmes.","Hugo, Préface de Cromwell, 1827"),
             ("Le drame est un miroir où se réfléchit la nature.","Hugo, même préface, cité par Stalloni")],
  plus="Comparer avec un manifeste italien connu des étudiants : Giovanni Berchet, Lettera semiseria di Grisostomo al suo figliuolo (1816)."),

"methode": N("30 min",
  "Scansion collective du premier vers du Lac, au tableau, syllabe par syllabe. Puis distribuer la fiche de versification (Studium) et faire scander deux vers en binômes.",
  essentiel="Trois règles suffisent. 1. Le e muet compte devant une consonne, ne compte pas devant une voyelle (élision) ni en fin de vers. 2. Diérèse et synérèse : deux voyelles qui se suivent forment deux syllabes (li-on, diérèse) ou une seule (pied, synérèse) ; l'usage dépend souvent de l'étymologie. 3. L'alexandrin classique se coupe en deux moitiés de six syllabes (hémistiches) à la césure.",
  qr=[("Scander le premier vers du Lac.",
       "Ain / si / tou / jours / pous / sés // vers / de / nou / veaux / ri / va(ges) = 12. Le e final de rivages ne compte pas (fin de vers). Césure après poussés."),
      ("Pourquoi le e de vers de compte-t-il ?",
       "De est suivi d'une consonne (nouveaux) : le e se prononce et compte."),
      ("Combien de syllabes dans nuit éternelle ?",
       "Nuit / é / ter / nel(le) en fin de vers, ou nuit / é / ter / nel / le si un mot commençant par une consonne suit. Dans le vers 2 (Dans la nuit éternelle emportés), le e de éternelle est élidé devant emportés : nuit / é / ter / nel / lem / por / tés.")],
  piege="Diérèse et synérèse dépendent souvent de l'étymologie (li-on, mais pied). Donner trois exemples seulement, ne pas faire de cours de phonétique."),

"nouvelle": N("30 min, séance C",
  "Mateo Falcone se lit en entier (une dizaine de pages) : soit avant le cours, soit en lecture à voix haute partagée. Raconter, puis analyser la fin.",
  essentiel="Mérimée (1803-1870), haut fonctionnaire, inspecteur des Monuments historiques à partir de 1834, publie Mateo Falcone dans la Revue de Paris en mai 1829, puis dans le recueil Mosaïque (1833). En Corse, près de Porto-Vecchio, le petit Fortunato, dix ans, fils de Mateo Falcone, cache un bandit blessé, Gianetto, puis le livre aux soldats (voltigeurs) en échange d'une montre en argent. Mateo, qui respecte le code de l'honneur, emmène son fils dans le maquis, le fait prier et le tue. Le narrateur raconte tout sans commentaire.",
  qr=[("Concision : comment le style produit-il l'effet ?",
       "Phrases courtes, narrateur impassible, aucun jugement moral : le lecteur reçoit la violence sans protection, et doit juger seul."),
      ("Chute : pourquoi la fin est-elle si forte ?",
       "Parce qu'un père tue son fils pour une faute d'enfant (la trahison d'un hôte pour une montre) : l'honneur corse est montré dans toute sa logique, et la dernière phrase (Fortunato tomba raide mort) tombe comme le coup de feu."),
      ("Regard : quelle Corse ?",
       "Une Corse vue de Paris : honneur, maquis, loi du sang, exotisme intérieur pour le lecteur parisien de 1829."),
      ("Mérimée connaissait-il la Corse quand il a écrit ce récit ?",
       "Non : il n'y va qu'en 1839, en mission comme inspecteur des Monuments historiques, avant d'écrire Colomba (1840). Sa Corse de 1829 est imaginée depuis Paris, à partir de livres : excellent point sociocritique.")],
  citations=[("Fortunato tomba raide mort.","Mérimée, Mateo Falcone, 1829, dernière page")],
  piege="Ne pas lire le récit comme un document ethnographique sur la Corse."),

"labo": N("30 min",
  "Faire scander par l'IA une strophe du Lac (ou la strophe Ô temps), puis recompter syllabe par syllabe. Chaque groupe note la règle que l'IA a oubliée et la dépose sur Studium.",
  qr=[("Quelles erreurs l'IA fait-elle le plus souvent ?",
       "Elle compte le e muet final des rimes féminines, oublie les élisions (éternelle emportés), applique le compte italien ou anglais, place mal la césure, ou affirme que le vers fait douze syllabes sans le montrer."),
      ("Comment savoir si l'IA a raison ?",
       "En recomptant soi-même avec les trois règles : la vérification est l'exercice. Si l'IA et l'étudiant ne sont pas d'accord, on demande à l'enseignant.")],
  piege="C'est le meilleur exercice pour vérifier ses propres connaissances : l'IA se trompe souvent avec assurance."),

"italia": N("15 min",
  "Raconter Ernani de Verdi (la musique transforme le drame en opéra populaire), puis comparer le compte des syllabes en italien et en français.",
  essentiel="Manzoni écrit en français la Lettre à M. Chauvet (rédigée en 1820, publiée en 1823), contre les unités de temps et de lieu : le débat de Paris est aussi un débat milanais. Verdi crée Ernani à La Fenice de Venise le 9 mars 1844, sur un livret de Piave d'après Hugo.",
  qr=[("Endecasillabo et alexandrin : comment compte-t-on en italien et en français ?",
       "En italien, l'endecasillabo se définit par son dernier accent, placé sur la dixième syllabe (le compte va jusqu'à cet accent, plus une syllabe). En français, l'alexandrin compte douze syllabes, et le e final des rimes féminines n'est jamais compté. Les deux systèmes ont des élisions (synalèphe en italien)."),
      ("Pourquoi Manzoni écrit-il en français ?",
       "Parce que le français est alors la langue européenne du débat littéraire, et qu'il répond à un critique français (Chauvet) qui avait attaqué sa tragédie Il conte di Carmagnola.")]),

"bilan": N("10 min",
  "Jeu d'Hernani si le temps le permet (sinon en début de semaine 3). Rappeler la scansion corrigée à déposer et la lecture de la dernière page du Père Goriot et de La Morte amoureuse.",
  qr=[("Comment fonctionne le jeu d'Hernani ?",
       "Deux camps (classiques et romantiques) ; chaque camp prépare trois slogans et une lecture des premiers vers de la pièce, l'un pour les défendre, l'autre pour les siffler. On termine en comparant avec le vrai déroulement de la première.")]),
}

# =====================================================================  S3
NOTES[3] = {
"cover": N("3 min",
  "Fil de la semaine : le roman devient une marchandise de presse et veut pourtant dire la vérité de la société.",
  essentiel="Sous la monarchie de Juillet (1830-1848), le roi Louis-Philippe gouverne avec la bourgeoisie d'argent ; le ministre Guizot aurait lancé Enrichissez-vous. La presse change : en 1836, les journaux à 40 francs par an, financés par la publicité, publient des romans en épisodes (feuilletons). Stendhal et Balzac inventent le roman moderne de la société ; Stalloni les présente comme les deux précurseurs du réalisme. Gautier, lui, écrit des nouvelles fantastiques.",
  qr=[("Que veut dire feuilleton ?",
       "À l'origine, le bas de la première page du journal, séparé par un trait. En 1836, on y publie des romans par épisodes : le roman-feuilleton.")]),

"objectifs": N("5 min",
  "L'objectif clé est la problématique : sans elle, pas de commentaire écrit. Le fantastique sera repris en semaine 6 avec Villiers.",
  qr=[("Qu'est-ce qu'une problématique ?",
       "La question à laquelle le commentaire répond. Elle porte sur le fonctionnement du texte (comment, en quoi, pourquoi) et sa réponse n'est pas évidente.")]),

"seances": N("3 min",
  "A : presse, capitaux, Stendhal. B : Balzac et la problématique. C : Gautier, labo IA, carte de Paris.",
  qr=[("Pourquoi une carte de Paris ?",
       "Parce que Le Père Goriot est un roman de la géographie sociale : chaque quartier correspond à une classe. Voir les lieux aide à comprendre la trajectoire de Rastignac.")]),

"enigme": N("15 min",
  "Faire calculer : un abonnement à 40 francs au lieu de 80, financé par les annonces. D'où le besoin de feuilletons qui retiennent les abonnés. Puis raconter le 1er juillet 1836.",
  essentiel="Le 1er juillet 1836, Émile de Girardin lance La Presse, et Armand Dutacq Le Siècle le même jour : abonnement à 40 francs par an au lieu de 80, la différence est payée par la publicité. Pour garder les abonnés, il faut un rendez-vous quotidien : le roman en épisodes. Premier grand essai dans La Presse : La Vieille Fille de Balzac (octobre-novembre 1836). Les grands succès suivront : Les Mystères de Paris d'Eugène Sue (1842-1843), Le Comte de Monte-Cristo de Dumas (1844-1846). Les historiens Marie-Ève Thérenty et Alain Vaillant appellent 1836 l'an I de l'ère médiatique.",
  qr=[("Un roman peut-il être à la fois une œuvre d'art et une marchandise ?",
       "Oui : c'est la situation de Balzac, qui écrit pour payer ses dettes et construit en même temps La Comédie humaine. La marchandise impose des contraintes (épisodes, suspense, longueur), mais ces contraintes peuvent aussi produire des formes nouvelles. Sainte-Beuve, en 1839, craint au contraire que le marché tue l'art."),
      ("Si le journal est payé par la publicité, que doit faire le roman ?",
       "Retenir le lecteur d'un jour à l'autre : suspense, épisodes, fin de chapitre ouverte (la suite au prochain numéro), personnages forts et reconnaissables."),
      ("Que gagne-t-on en baissant le prix ?",
       "Beaucoup plus d'abonnés que les journaux à 80 francs, donc plus d'annonceurs : le roman touche un public nouveau, bourgeois et petit-bourgeois, qui n'achetait pas de livres.")],
  source="M.-È. Thérenty et A. Vaillant, 1836. L'An I de l'ère médiatique, Nouveau Monde, 2001."),

"frise": N("10 min",
  "Montrer la date double de 1836 : La Presse et La Morte amoureuse la même année. Sainte-Beuve dénonce une littérature industrielle en 1839. Les Mystères de Paris paraissent dans le Journal des débats de juin 1842 à octobre 1843.",
  qr=[("Pourquoi Sainte-Beuve s'inquiète-t-il ?",
       "Il craint que la logique du marché (écrire vite, beaucoup, pour vendre) remplace celle de l'art : il parle de littérature industrielle, comme on parle d'industrie."),
      ("Que change l'Avant-propos de 1842 ?",
       "Balzac donne un titre et un plan à toute son œuvre, La Comédie humaine : il se présente comme l'historien des mœurs de son temps, presque comme un savant (il se compare aux zoologistes).")],
  citations=[("La Société française allait être l'historien, je ne devais être que le secrétaire.","Balzac, Avant-propos de La Comédie humaine, 1842")]),

"auteurs": N("20 min",
  "Une idée et une question par auteur : qui vit de sa plume ?",
  essentiel="Stendhal (Henri Beyle, 1783-1842) : ancien soldat et fonctionnaire de Napoléon, vit à Milan de 1814 à 1821, puis devient consul à Civitavecchia (1831) ; il écrit pour les happy few et vend peu de son vivant. Balzac (1799-1850) : ruiné par une imprimerie en 1828, il écrit énormément pour payer ses dettes ; plus de 90 romans et nouvelles réunis dans La Comédie humaine (titre de 1842). Gautier (1811-1872) : le gilet rouge d'Hernani, poète, conteur fantastique et journaliste (critique dramatique à La Presse). Eugène Sue (1804-1857) : le plus grand succès commercial du feuilleton avec Les Mystères de Paris.",
  qr=[("Lequel de ces écrivains vit de sa plume ?",
       "Balzac, Gautier et Sue vivent de la presse et de la librairie (avec des difficultés pour Balzac, toujours endetté). Stendhal vit de son salaire de fonctionnaire : il peut écrire sans se soucier du succès."),
      ("Pourquoi Stendhal écrit-il pour les happy few ?",
       "Parce qu'il ne dépend pas du marché : il peut viser un petit nombre de lecteurs choisis, et compte sur la postérité (il pensait être lu vers 1880 ou 1935).")]),

"outil": N("20 min",
  "Faire classer Rastignac, Goriot et Vautrin selon les trois capitaux, en 10 minutes, par groupes. Mise en commun au tableau.",
  essentiel="Pour Bourdieu, chaque individu possède des ressources de plusieurs types : le capital économique (argent, biens), le capital culturel (savoirs, diplômes, goût, manières), le capital social (réseau de relations utiles). L'important est la conversion : transformer un capital en un autre (des relations en argent, un diplôme en poste). La trajectoire est le chemin social d'un individu dans le temps.",
  qr=[("Classer Rastignac, Goriot et Vautrin selon les trois capitaux.",
       "Rastignac : faible capital économique (famille noble ruinée d'Angoulême), un peu de capital culturel (étudiant en droit), un capital social potentiel (sa cousine, Mme de Beauséant, lui ouvre les salons). Goriot : ancien vermicellier enrichi, il a eu un gros capital économique mais l'a donné à ses filles ; pas de capital culturel ni social : il meurt seul. Vautrin : capital économique caché, savoir du crime, réseau du bagne : il propose à Rastignac un raccourci criminel vers la fortune."),
      ("Quelle conversion Rastignac apprend-il ?",
       "Convertir le capital social (Mme de Beauséant, puis Delphine de Nucingen) en position et en argent : il entre dans le monde par les femmes et les salons.")],
  piege="Ne pas transformer Bourdieu en grille mécanique : l'intérêt est la conversion d'un capital en un autre."),

"texte1": N("30 min, séance A",
  "Lire la phrase, puis le passage complet du livre II, chapitre 19 (Studium) : le romancier se défend contre l'accusation d'immoralité. La suite oppose l'azur des cieux et la fange des bourbiers de la route.",
  essentiel="Le Rouge et le Noir (1830), sous-titré Chronique de 1830, raconte l'ascension et la chute de Julien Sorel, fils de charpentier, précepteur chez M. de Rênal, séminariste, puis secrétaire du marquis de La Mole à Paris ; il finit guillotiné après avoir tiré sur Mme de Rênal. Stendhal s'inspire d'un fait divers réel (l'affaire Berthet, 1827-1828). Le rouge et le noir : l'armée et l'Église, les deux voies d'ascension pour un jeune homme pauvre après Napoléon.",
  qr=[("Image : que reflète le miroir ? Qui le porte ?",
       "Il reflète la route, c'est-à-dire la société avec sa beauté (l'azur) et sa saleté (la boue). Le romancier le porte, comme un voyageur."),
      ("Défense : pourquoi Stendhal se défend-il ainsi ?",
       "On l'accuse d'immoralité parce qu'il montre des ambitieux, des hypocrites, une femme mariée amoureuse. Il répond : ce n'est pas le miroir qui est coupable, c'est la route qui est boueuse, et l'inspecteur des routes qui la laisse ainsi."),
      ("Débat : un miroir est-il neutre ?",
       "Non : celui qui le porte choisit l'angle, le moment, ce qu'il montre. Stendhal lui-même commente, ironise, choisit. C'est la limite de l'image du miroir, que le réalisme discutera (Maupassant parlera d'illusionnistes, semaine 5)."),
      ("Si le miroir montre la boue, qui est coupable ?",
       "La route (la société) et ceux qui l'entretiennent, pas le miroir (le roman).")],
  citations=[("Un roman est un miroir qui se promène sur une grande route.","Stendhal, Le Rouge et le Noir, II, 19"),
             ("La vérité, l'âpre vérité.","épigraphe du livre I, attribuée à Danton")],
  plus="Stendhal avait déjà placé au chapitre 13 du livre I une épigraphe sur le miroir attribuée à Saint-Réal, très probablement inventée : une fausse attribution au XIXe siècle, bon lien avec la vérification des sources en labo IA."),

"texte2": N("30 min, séance B",
  "Lire la dernière page entière (Studium). Montrer une carte de Paris : pension Vauquer (rue Neuve-Sainte-Geneviève, quartier pauvre du Quartier latin), faubourg Saint-Germain (vieille noblesse, Mme de Beauséant), Chaussée-d'Antin (banquiers, les Nucingen), Père-Lachaise.",
  essentiel="Le Père Goriot (1835) : à la pension Vauquer vivent le père Goriot, ancien commerçant qui s'est ruiné pour ses deux filles mariées dans le grand monde, l'étudiant Eugène de Rastignac et le mystérieux Vautrin (un forçat évadé). Goriot meurt abandonné par ses filles ; seul Rastignac l'enterre au Père-Lachaise. Le roman commence par une formule anglaise, All is true, pour affirmer sa vérité.",
  qr=[("Lieu : que voit Rastignac depuis la colline ?",
       "Paris, et précisément le quartier entre la colonne de la place Vendôme et le dôme des Invalides : le beau monde, là où vit la haute société qu'il veut conquérir."),
      ("Défi : à qui parle-t-il ? Que veut-il conquérir ?",
       "À Paris personnifié, c'est-à-dire à la société. Il veut conquérir une place, l'argent et la reconnaissance."),
      ("Trajectoire : de la pension Vauquer aux salons, quel chemin ?",
       "De la misère du Quartier latin aux salons du faubourg Saint-Germain et de la Chaussée-d'Antin, par les relations (sa cousine) et les femmes (Delphine), au prix de ses illusions morales."),
      ("Quel est le premier acte de Rastignac après son défi ?",
       "Il va dîner chez Mme de Nucingen, la fille de Goriot qui n'est pas venue à l'enterrement : il entre dans le jeu social qu'il vient de juger.")],
  citations=[("À nous deux maintenant !","Balzac, Le Père Goriot, 1835, dernière page"),
             ("Il n'y a pas de principes, il n'y a que des événements ; il n'y a pas de lois, il n'y a que des circonstances.","Vautrin à Rastignac, Le Père Goriot"),
             ("All is true.","Le Père Goriot, première page")],
  piege="Ne pas lire la fin comme une simple victoire : c'est un défi et une capitulation morale en même temps."),

"methode": N("40 min",
  "Trois problématiques par groupe, puis classement au tableau : trop large, trop étroite, juste.",
  essentiel="Une bonne problématique : 1. part des observations (relevés des étapes 1 et 2) ; 2. est une vraie question (comment, en quoi, pourquoi) ; 3. concerne tout le texte ; 4. n'a pas de réponse évidente. Elle annonce déjà le plan.",
  qr=[("Donner un exemple de problématique juste pour la fin du Père Goriot.",
       "En quoi cette dernière page transforme-t-elle un deuil en déclaration de guerre sociale ?"),
      ("Un exemple trop large ?",
       "Comment Balzac représente-t-il la société ? (vaut pour toute La Comédie humaine)."),
      ("Un exemple trop étroit ?",
       "Pourquoi Rastignac va-t-il dîner chez Delphine ? (ne concerne qu'une phrase).")]),

"nouvelle": N("30 min, séance C",
  "Présenter le fantastique avec simplicité : hésitation entre une explication naturelle et une explication surnaturelle. Raconter l'histoire en trois minutes.",
  essentiel="La Morte amoureuse paraît dans la Chronique de Paris, la revue de Balzac, les 23 et 26 juin 1836. Le vieux prêtre Romuald raconte à un jeune confrère qu'au jour de son ordination il a vu la courtisane Clarimonde ; devenu curé de campagne, il vit pendant trois ans une double vie, prêtre le jour et amant de Clarimonde (morte, devenue vampire) la nuit, à Venise. L'abbé Sérapion ouvre la tombe et la réduit en poussière. Romuald finit par mettre en garde son interlocuteur contre le regard d'une femme.",
  qr=[("Peut-on choisir entre rêve et réalité à la fin ?",
       "Non : le texte donne des indices dans les deux sens (le sommeil, les rêves, mais aussi le corps intact de Clarimonde dans la tombe). Cette hésitation définit le fantastique selon Todorov."),
      ("Récit : qui raconte et à qui ?",
       "Romuald, devenu vieux, raconte à un frère (un autre religieux) qui lui a demandé s'il avait aimé : c'est un récit encadré, une confession."),
      ("Presse : où la nouvelle a-t-elle paru ?",
       "Dans la Chronique de Paris, revue dirigée par Balzac, en juin 1836 : la même année que La Presse.")],
  citations=[("Vous me demandez, frère, si j'ai aimé ; oui.","Gautier, La Morte amoureuse, première phrase")],
  piege="Stalloni date La Morte amoureuse de 1844 : c'est une erreur du manuel, la nouvelle paraît en 1836. Montrer l'erreur aux étudiants : même un manuel imprimé se vérifie.",
  source="T. Todorov, Introduction à la littérature fantastique, Seuil, 1970."),

"labo": N("30 min",
  "Faire produire cinq problématiques par l'IA sur la fin du Père Goriot, puis les trier avec les critères de la méthode.",
  qr=[("Lesquelles sont de vraies questions ?",
       "Celles qui portent sur le fonctionnement du texte et dont la réponse n'est pas évidente. Les questions qui demandent un résumé (Que fait Rastignac ?) ne sont pas des problématiques."),
      ("Lesquelles inventent des détails ?",
       "Souvent l'IA fait parler Goriot à l'enterrement (il est mort), place Vautrin au cimetière (il a été arrêté) ou fait pleurer Delphine sur la tombe (elle n'est pas venue). Vérifier chaque détail dans la page.")],
  piege="L'IA propose souvent des problématiques générales : bon exercice pour apprendre à resserrer."),

"italia": N("15 min",
  "Lire l'épitaphe de Stendhal et demander pourquoi un Français se veut milanais.",
  essentiel="L'épitaphe de Stendhal, au cimetière de Montmartre, est en italien : Arrigo Beyle / Milanese / scrisse / amò / visse. Manzoni révise I promessi sposi pour l'édition de 1840-1842 en toscan de Florence (il dit avoir rincé ses vêtements dans l'Arno). La Chartreuse de Parme (1839) commence par l'entrée de Bonaparte à Milan en 1796.",
  qr=[("Pourquoi un Français se veut-il milanais ?",
       "Milan est pour Stendhal la ville de la passion, de la musique et de la liberté, à l'opposé de la vanité parisienne ; il y a vécu ses années les plus heureuses (1814-1821)."),
      ("Qu'ont en commun Balzac et Manzoni ?",
       "Deux grands romans de la société, mais Manzoni situe le sien au XVIIe siècle (roman historique) alors que Balzac peint son présent.")]),

"bilan": N("10 min",
  "Annoncer la semaine 4 et le premier texte A.1 en prose : Le Spleen de Paris. Distribuer les rôles du tribunal de 1857 (procureur Pinard, avocat Senard, Flaubert, Baudelaire, juges).",
  qr=[("Que faut-il lire ?",
       "L'Étranger et Enivrez-vous de Baudelaire (Studium), et le chapitre I d'Un cœur simple de Flaubert.")]),
}

# =====================================================================  S4
NOTES[4] = {
"cover": N("3 min",
  "Premier texte A.1 en prose. La paire 3 oppose Baudelaire (Le Spleen de Paris) et Gide (Les Nourritures terrestres, semaine 7).",
  essentiel="Sous le Second Empire (1852-1870), Napoléon III contrôle la presse et la morale publique. En 1857, deux chefs-d'œuvre passent au tribunal : Madame Bovary (acquitté) et Les Fleurs du mal (condamné). Au même moment, une partie des écrivains défend l'art pour l'art (Gautier, le Parnasse) : la beauté n'a pas à être utile ni morale. Bourdieu voit dans ce moment la naissance de l'autonomie du champ littéraire.",
  qr=[("Qu'est-ce que le Second Empire ?",
       "Le régime de Napoléon III, neveu de Napoléon Ier : élu président en 1848, il fait un coup d'État le 2 décembre 1851 et devient empereur en 1852, jusqu'à la défaite de 1870.")]),

"objectifs": N("5 min",
  "Le plan est l'objectif central pour l'écrit ; le style indirect libre reviendra en semaine 5.",
  qr=[("Qu'est-ce que le style indirect libre ?",
       "Une manière de rapporter les pensées d'un personnage dans la voix du narrateur, sans verbe introducteur ni guillemets : on entend le personnage sans qu'il parle. Exemple de type : Elle pensait à Loulou. Il reviendrait peut-être.")]),

"seances": N("3 min",
  "A : procès et autonomie, lecture critique de Stalloni (art pour l'art, Parnasse, réalisme). B : Baudelaire et le plan. C : Flaubert, labo, tribunal.",
  qr=[("Comment se déroule le jeu du tribunal ?",
       "Environ 40 minutes. Rôles distribués en semaine 3 : le procureur Pinard, l'avocat Senard, Flaubert, Baudelaire, trois juges. Le procureur lit deux passages incriminés, l'avocat répond, les juges délibèrent devant la classe ; on compare ensuite avec les verdicts réels.")]),

"enigme": N("10 min",
  "Raconter les deux procès comme une enquête. Puis poser la question.",
  essentiel="Madame Bovary paraît en feuilleton dans la Revue de Paris (octobre-décembre 1856) ; Flaubert, l'éditeur et l'imprimeur sont poursuivis pour outrage à la morale publique et religieuse. Le procès a lieu le 29 janvier 1857 devant le tribunal correctionnel ; le procureur impérial Ernest Pinard accuse le livre de glorifier l'adultère ; l'avocat Jules Senard défend un livre moral qui montre le châtiment de la faute. Acquittement le 7 février 1857. Les Fleurs du mal paraissent en juin 1857 ; le même Pinard poursuit Baudelaire ; le 20 août 1857, condamnation à une amende et suppression de six poèmes. La condamnation n'est annulée qu'en 1949.",
  qr=[("Pourquoi juge-t-on des livres au tribunal ?",
       "Parce que le Second Empire considère la littérature comme une affaire de morale publique : un livre qui montre l'adultère ou la sensualité sans les condamner est un danger pour l'ordre social. On juge en réalité une conception de l'art qui refuse de moraliser."),
      ("Qu'est-ce que l'État reproche à un roman ?",
       "L'outrage à la morale publique et religieuse : peindre l'adultère avec des couleurs séduisantes, mêler religion et sensualité (scène de l'extrême-onction)."),
      ("Pourquoi Flaubert est-il acquitté et Baudelaire condamné ?",
       "Flaubert, fils d'un célèbre chirurgien de Rouen, a un bon avocat et un roman qui punit l'héroïne ; le jugement le blâme pourtant. Baudelaire est moins protégé, et la poésie, concentrée, semble plus provocante ; six poèmes jugés obscènes sont retirés.")],
  piege="En 1857, pas de jury : un tribunal correctionnel. Les jurés du jeu sont fictifs."),

"frise": N("10 min",
  "Montrer que la doctrine (Gautier, 1835) précède le conflit avec le régime (1852-1857). Le Spleen de Paris paraît deux ans après la mort de Baudelaire (1867).",
  qr=[("Pourquoi la date de 1835 en rouge ?",
       "C'est une œuvre (la préface de Mademoiselle de Maupin, de Gautier), qui pose la doctrine : le beau n'est pas utile. Les dates en bleu sont les interventions de l'État."),
      ("Pourquoi Trois Contes (1877) arrive-t-il si tard ?",
       "Flaubert écrit Un cœur simple en 1876, à la fin de sa vie, pendant une période de difficultés financières : c'est un retour à la forme courte, très travaillée.")]),

"auteurs": N("20 min",
  "Une idée par auteur, puis la question de la dédicace.",
  essentiel="Baudelaire (1821-1867) : poète, critique d'art, traducteur d'Edgar Poe ; Les Fleurs du mal (1857, éd. augmentée 1861) ; il invente la modernité poétique (la ville, la foule, l'ennui) et le poème en prose. Flaubert (1821-1880) : fils de chirurgien, vit de ses rentes à Croisset près de Rouen ; il passe des années sur chaque livre (Madame Bovary, Salammbô, L'Éducation sentimentale). Gautier (1811-1872) : devenu le maître de l'art pour l'art. Leconte de Lisle (1818-1894) : né à La Réunion, chef du Parnasse, Poèmes antiques (1852), Poèmes barbares (1862).",
  qr=[("Que montre la dédicace des Fleurs du mal à Gautier ?",
       "Une filiation choisie : Baudelaire se place sous l'autorité du poète impeccable, défenseur de l'art pour l'art, contre la morale bourgeoise. Le gilet rouge de 1830 est devenu un maître."),
      ("Qu'est-ce que le Parnasse ?",
       "Un groupe de poètes réunis dans l'anthologie Le Parnasse contemporain (1866, 1871, 1876), chez l'éditeur Lemerre : culte de la forme parfaite, refus des épanchements lyriques, sujets antiques ou exotiques.")],
  citations=[("Au poète impeccable, au parfait magicien ès lettres françaises…","dédicace des Fleurs du mal à Théophile Gautier")]),

"outil": N("20 min",
  "Expliquer simplement l'économie à l'envers : dans un champ autonome, l'échec commercial ou judiciaire peut devenir un signe de valeur. Exemple : Baudelaire condamné, aujourd'hui au programme.",
  essentiel="Pour Bourdieu (Les Règles de l'art), le champ littéraire devient autonome au milieu du XIXe siècle : il fixe ses propres règles de valeur, contre l'État (la morale) et contre le marché (le succès). Dans ce monde à l'envers, perdre de l'argent ou être condamné peut faire gagner du prestige auprès des pairs. Flaubert et Baudelaire sont ses deux héros.",
  qr=[("Autonomie : contre qui l'art veut-il ses propres règles ?",
       "Contre la morale (l'État, l'Église, les tribunaux) et contre le marché (le succès, le feuilleton, l'argent)."),
      ("Baudelaire condamné en 1857 est aujourd'hui au programme : qui a gagné ?",
       "Baudelaire, à long terme : la consécration est venue des pairs (Verlaine, Rimbaud, Mallarmé), puis de l'école. Le tribunal a gagné en 1857, la littérature a gagné dans le temps long."),
      ("L'autonomie est-elle accessible à tous ?",
       "Non : il faut pouvoir attendre. Flaubert vit de rentes ; Baudelaire, sous tutelle judiciaire, vit dans la gêne. Le refus du marché suppose souvent un capital économique.")],
  piege="Ne pas idéaliser : l'autonomie se conquiert aussi grâce à des revenus (Flaubert vit de rentes).",
  source="P. Bourdieu, Les Règles de l'art, 1992, première partie."),

"critique-stalloni-parnasse": N("20 min, séance A",
  "Lire la citation de Gautier à voix haute, avec provocation : c'est un manifeste. Puis les quatre idées. Terminer par la question des étiquettes.",
  essentiel="Stalloni présente trois réponses au romantisme vers 1835-1870. 1. L'art pour l'art de Gautier : la beauté ne sert à rien, et c'est sa valeur. 2. Le Parnasse : mouvement daté et organisé (Le Parnasse contemporain, mars 1866, chez Lemerre, 37 poètes ; deux autres volumes en 1871 et 1876) ; culte du travail (le poète comme sculpteur), religion du beau, impassibilité (refus du lyrisme) ; le comité de 1876 refuse Verlaine, Charles Cros et Mallarmé. 3. Le réalisme : mot lancé autour de Courbet (exposition Du Réalisme, 1855), défendu par Champfleury (Le Réalisme, 1857) et Duranty (revue Réalisme, 1856-1857) ; il veut le vrai, le présent, les classes populaires. Flaubert et les Goncourt y sont rattachés malgré eux.",
  qr=[("Flaubert et Baudelaire sont rangés dans des écoles qu'ils refusent : qui pose les étiquettes ?",
       "Surtout les critiques et, plus tard, les manuels. Les écrivains s'en défendent : Flaubert écrit à Maupassant que naturalisme et réalisme sont la même ineptie ; Courbet dit que le titre de réaliste lui a été imposé comme celui de romantique aux hommes de 1830. L'étiquette est une arme dans le champ, et un outil de classement scolaire."),
      ("Pourquoi Flaubert est-il rangé parmi les réalistes ?",
       "Pour Madame Bovary, L'Éducation sentimentale et Un cœur simple : sujets contemporains, documentation, ironie, effacement de l'auteur. Mais il est aussi l'auteur de Salammbô et de La Tentation de saint Antoine, très loin du réalisme."),
      ("Que veut dire impassibilité chez les Parnassiens ?",
       "Le refus d'exposer ses émotions personnelles dans le poème ; Stalloni préfère parler de poésie impersonnelle ou objective.")],
  citations=[("Comment peut-on donner dans des mots vides de sens comme celui de Naturalisme ? Pourquoi a-t-on délaissé ce bon Champfleury avec le Réalisme qui est une ineptie du même calibre ou plutôt la même ineptie ?","Flaubert à Maupassant, 25 décembre 1876, cité par Stalloni"),
             ("Le titre de réaliste m'a été imposé comme on a imposé aux hommes de 1830 le titre de romantique.","Courbet, cité par Champfleury puis par Stalloni")],
  piege="Le manuel rapproche Baudelaire du Parnasse (il donne seize poèmes au premier Parnasse contemporain en 1866) : c'est exact, mais Baudelaire ne se réduit pas à l'impassibilité. Ne pas l'enfermer dans l'école.",
  source=f"{STAL}, sections « Le Parnasse » et « Le Réalisme »."),

"texte1": N("45 min, séance B",
  "L'Étranger ouvre Le Spleen de Paris. Le lire à deux voix (celui qui interroge, l'étranger). Puis analyse de la gradation des refus.",
  essentiel="Le Spleen de Paris (ou Petits poèmes en prose) réunit 50 poèmes publiés après la mort de Baudelaire, en 1869. Dans la dédicace à Arsène Houssaye, Baudelaire rêve d'une prose poétique, musicale sans rythme et sans rime, et cite comme modèle Gaspard de la nuit d'Aloysius Bertrand (1842). Dans L'Étranger, un homme énigmatique est interrogé : il refuse successivement la famille, les amis, la patrie, la beauté, l'or ; il n'aime que les nuages.",
  qr=[("Forme : pas de vers, pas de rime, où est la poésie ?",
       "Dans le rythme des répliques, les répétitions, la gradation, la musique finale (les nuages… là-bas… là-bas…), la densité des images et la brièveté : un poème est une intensité, pas seulement des vers."),
      ("Dialogue : qui interroge ? Qui refuse ?",
       "Une voix sociale anonyme (celle du bon sens bourgeois) interroge ; l'étranger refuse chaque valeur qu'on lui propose."),
      ("Société : famille, patrie, argent, que refuse l'étranger ?",
       "Les piliers de la société bourgeoise du Second Empire : la famille, l'amitié, la patrie, la beauté conventionnelle, l'or. Il ne garde qu'un idéal mobile, insaisissable : les nuages."),
      ("Que reste-t-il à l'étranger ? Quel mot clôt le poème ?",
       "Les nuages, les merveilleux nuages : le dernier mot du poème.")],
  citations=[("Qui aimes-tu le mieux, homme énigmatique, dis ? ton père, ta mère, ta sœur ou ton frère ?","Baudelaire, L'Étranger"),
             ("J'aime les nuages… les nuages qui passent… là-bas… là-bas… les merveilleux nuages !","L'Étranger, dernière réplique")],
  piege="Ne pas paraphraser le dialogue : analyser la gradation des refus (famille, amis, patrie, beauté, or)."),

"texte2": N("30 min, séance B",
  "Lecture à voix haute, ton d'injonction. Faire relever les trois ivresses (de vin, de poésie ou de vertu). Puis construire un plan en deux axes ensemble.",
  qr=[("Ton : Il faut, quel ton, quelle voix ?",
       "Une injonction, presque un sermon : le poète parle comme un prédicateur ou un moraliste, mais pour prêcher l'ivresse. C'est une parodie de discours moral."),
      ("Ivresse : de vin, de poésie ou de vertu, de quoi parle-t-il ?",
       "Des trois à la fois : peu importe l'objet, ce qui compte est l'intensité qui permet d'échapper au Temps, ce fardeau qui écrase. Le poème refuse de choisir entre morale (vertu) et plaisir (vin)."),
      ("Plan : proposez deux axes pour un commentaire.",
       "I. Une injonction universelle qui parodie le discours moral (Il faut, tout est là, l'unique question). II. Une ivresse qui échappe à la morale et lutte contre le Temps (vin, poésie, vertu ; le vent, la vague, l'étoile qui répondent).")],
  citations=[("Il faut être toujours ivre. Tout est là : c'est l'unique question.","Baudelaire, Enivrez-vous"),
             ("De vin, de poésie ou de vertu, à votre guise. Mais enivrez-vous.","même poème")]),

"methode": N("45 min",
  "Comparer les plans au tableau : axe thématique ou axe formel ? Les deux sont possibles si la problématique les relie. Chaque axe annonce une idée, pas un procédé.",
  essentiel="Un plan de commentaire a deux ou trois parties. Chaque partie est une idée qui répond à la problématique ; à l'intérieur, deux ou trois sous-parties avec citations et analyses. On va du plus visible au plus profond. À éviter : le plan qui suit le texte ligne à ligne (paraphrase) et le plan qui sépare le fond et la forme.",
  qr=[("Un plan pour L'Étranger ?",
       "Problématique : comment ce dialogue fait-il d'un refus généralisé un idéal poétique ? I. Un interrogatoire social et une série de refus (gradation famille, amis, patrie, beauté, or). II. Un idéal insaisissable : les nuages, la musique finale, la poésie comme ailleurs."),
      ("Axe formel ou thématique ?",
       "Les deux sont acceptables si chaque axe est une idée liée à la problématique. Un axe intitulé Les procédés stylistiques n'est pas une idée.")]),

"nouvelle": N("30 min, séance C",
  "Faire entendre le style indirect libre sur une page du chapitre IV. Lire la dernière phrase et demander qui voit le perroquet.",
  essentiel="Un cœur simple (écrit en 1876, publié dans Trois Contes en 1877) raconte la vie de Félicité, servante pendant un demi-siècle chez Mme Aubain à Pont-l'Évêque, en Normandie. Elle aime successivement un fiancé qui l'abandonne, les enfants de sa maîtresse, son neveu Victor (mort aux Amériques), puis un perroquet, Loulou, qu'elle fait empailler et qu'elle finit par confondre avec le Saint-Esprit. Pour écrire, Flaubert emprunte un perroquet empaillé au Muséum de Rouen. George Sand lui reprochait sa froideur : il voulait écrire un récit qui émeuve.",
  qr=[("Personnage : pourquoi une servante au centre du récit est-elle un choix nouveau ?",
       "Parce que la littérature réservait le premier rôle aux classes supérieures ; les domestiques étaient des figures comiques ou secondaires. Flaubert donne à une vie humble la dignité d'un sujet (c'est aussi ce que réclameront les Goncourt en 1865)."),
      ("Style : comment entend-on Félicité sans qu'elle parle ?",
       "Par le style indirect libre : ses pensées et ses confusions passent dans la voix du narrateur, sans guillemets."),
      ("Pourquoi Félicité confond-elle Loulou et le Saint-Esprit ?",
       "Parce que sa foi est concrète et affective : elle ne comprend pas les dogmes, elle aime ce qu'elle voit. Une image d'Épinal du baptême du Christ, avec la colombe, lui rappelle son perroquet. Le texte la montre sans la ridiculiser."),
      ("Ironie ou tendresse ?",
       "Les deux lectures sont possibles et argumentables : la dernière phrase (le perroquet gigantesque dans les cieux) peut sembler grotesque ou sublime. C'est l'ambiguïté voulue par Flaubert.")],
  citations=[("Pendant un demi-siècle, les bourgeoises de Pont-l'Évêque envièrent à Mme Aubain sa servante Félicité.","Flaubert, Un cœur simple, première phrase"),
             ("A l'église, elle contemplait toujours le Saint-Esprit, et observa qu'il avait quelque chose du perroquet.","chapitre IV"),
             ("…elle crut voir, dans les cieux entr'ouverts, un perroquet gigantesque, planant au-dessus de sa tête.","dernière phrase")],
  piege="Le débat ironie ou tendresse n'a pas de réponse unique : accepter les deux lectures si elles sont argumentées."),

"labo": N("25 min",
  "Demander à Flaubert, dans l'Atelier du siècle, s'il a dit Madame Bovary, c'est moi. Puis chercher la source.",
  essentiel="La phrase n'apparaît dans aucun écrit de Flaubert (ni œuvres ni lettres). Elle est rapportée tardivement : René Descharmes la publie en 1909, d'après le témoignage d'Amélie Bosquet, amie de Flaubert, qui l'aurait entendue. C'est donc un témoignage indirect et tardif. Dans ses lettres, Flaubert dit au contraire vouloir être absent de son livre.",
  qr=[("L'IA donne-t-elle une source ? Laquelle ?",
       "Souvent elle attribue la phrase à une lettre à Louise Colet ou au procès de 1857 : c'est faux. La seule source est indirecte (Amélie Bosquet, par Descharmes, 1909)."),
      ("Écrire la réponse juste en deux phrases, avec la source.",
       "Flaubert n'a jamais écrit Madame Bovary, c'est moi. La phrase est rapportée en 1909 par René Descharmes d'après le témoignage d'Amélie Bosquet.")],
  piege="Valoriser l'étudiant qui trouve la vraie source, et celui qui montre que l'IA invente une lettre ou une date."),

"italia": N("15 min",
  "La Scapigliatura et Verga. Puis le jeu du tribunal (40 min) si on ne l'a pas fait en séance A.",
  essentiel="À Milan, dans les années 1860, la Scapigliatura (Emilio Praga, Arrigo Boito) lit Baudelaire et se veut maudite ; Praga écrit dans Preludio (1864) : Noi siamo i figli dei padri ammalati. Verga, sicilien de Catania, retient de Flaubert l'impersonnalité : dans la préface de L'amante di Gramigna (1880), il veut que l'œuvre semble s'être faite toute seule.",
  qr=[("Le jeu : notre verdict correspond-il au verdict réel ?",
       "Verdicts réels : Flaubert acquitté le 7 février 1857 ; Baudelaire condamné le 20 août 1857 à une amende et à la suppression de six poèmes, condamnation annulée en 1949."),
      ("Qu'est-ce que Verga prend à Flaubert ?",
       "L'idée d'un auteur invisible : la main de l'artiste doit rester absolument invisible, l'œuvre doit sembler s'être faite d'elle-même.")]),

"bilan": N("10 min",
  "Prévenir : la séance B de la semaine 5 est un atelier de commentaire de 2 heures, sans note, avec retour écrit. Rappeler les lectures : Boule de suif (début) ou Le Horla, et La Dernière Classe.",
  qr=[("Que faut-il apporter à l'atelier ?",
       "Le texte imprimé (Boule de suif ou Le Horla), ses notes de méthode des étapes 1 à 4 et un dictionnaire.")]),
}
