# Notes de l'enseignant, version développée (semaines 5 à 8).
from notes_a import N

NOTES = {}

NOTES[5] = {
"cover": N("3 min", "Semaine centrale pour la partie B de la fiche : quatre auteurs de la liste et les deux recueils à lire en entier. Premier atelier de commentaire en séance B."),
"objectifs": N("5 min", "Nouveau savoir-faire : lire un recueil comme un ensemble. La fiche demande Les Diaboliques et Les Soirées de Médan en édition intégrale.",
  piege="Les étudiants lisent souvent une seule nouvelle par recueil : montrer pourquoi le cadre et l'ordre comptent."),
"seances": N("3 min", "A : Médan et le recueil. B : atelier de 2 h. C : Barbey, Le Horla, Daudet, labo IA."),
"enigme": N("10 min",
  "Médan est la maison de campagne de Zola (achetée en 1878). Six écrivains, six nouvelles sur la guerre de 1870, publiées chez Charpentier en avril 1880.",
  questions="Pourquoi raconter une défaite plutôt qu'une victoire ?",
  attendus="Refus de l'héroïsme officiel ; la défaite révèle la société (lâcheté bourgeoise, hypocrisie morale)."),
"frise": N("10 min",
  "La Dernière Classe paraît dans L'Événement en 1872, puis dans les Contes du lundi (1873). Les Diaboliques (Dentu, fin 1874) sont saisies quelques semaines après leur parution. Germinal paraît d'abord en feuilleton dans le Gil Blas (1884-1885).",
  questions="Quel lien entre ces saisies et la semaine 4 ?",
  attendus="La justice continue de juger la littérature au nom des mœurs."),
"auteurs": N("20 min",
  "Zola : chef d'école, puis J'accuse… ! dans L'Aurore le 13 janvier 1898. Maupassant : environ trois cents nouvelles en dix ans, publiées d'abord dans Gil Blas et Le Gaulois. Daudet : Lettres de mon moulin (1869). Barbey : dandy, auteur d'un essai sur le dandysme et George Brummell (1845), surnommé le connétable des lettres.",
  questions="Qui appartient à l'école naturaliste, qui reste en dehors ?",
  attendus="Zola et Maupassant dedans (Médan) ; Daudet proche mais indépendant ; Barbey franchement hostile."),
"outil": N("25 min",
  "Faire remplir un tableau à trois colonnes pour chaque recueil : cadre, échos, position. Médan : six auteurs, un sujet, une école. Les Diaboliques : six histoires de femmes criminelles ou passionnées, racontées par des narrateurs de salon.",
  piege="Un recueil n'est pas une simple addition : l'ordre des textes construit un sens."),
"texte1": N("30 min, séance A",
  "Boule de suif : Rouen occupée, une diligence, une prostituée sacrifiée par des notables qui la méprisent ensuite. Flaubert salue la nouvelle comme un chef-d'œuvre.",
  questions="Pourquoi le plus-que-parfait dans la première phrase ?",
  attendus="Le récit commence après la débâcle : la guerre est déjà perdue, il reste la société.",
  plus="Sociocritique : la diligence est un modèle réduit de la société (noblesse, bourgeoisie, religieuses, démocrate, prostituée)."),
"texte2": N("30 min, séance C",
  "Récit dans le récit : le vicomte de Brassard raconte, de nuit, dans une diligence arrêtée devant une fenêtre au rideau cramoisi, son aventure de jeunesse avec Alberte.",
  questions="Pourquoi Barbey multiplie-t-il les narrateurs ?",
  attendus="Le mystère se transmet oralement ; personne ne sait tout ; l'horreur reste voilée."),
"methode": N("2 h, séance B",
  "Atelier non noté : introduction sur Boule de suif ou Le Horla (au choix), puis une partie si le temps le permet. Corriger avec la grille à cinq critères du cours. Retour écrit pour la semaine 6.",
  piege="Les amorces trop générales (Depuis toujours…) : exiger auteur, œuvre, date, mouvement dès la première phrase."),
"nouvelle": N("30 min, séance C",
  "Le Horla existe en deux versions : 1886 (récit fait à des médecins) et 1887 (journal intime). On lit la seconde. La Dernière Classe se lit en dix minutes à voix haute : M. Hamel, dernière leçon de français avant l'annexion de l'Alsace, Vive la France ! écrit au tableau.",
  questions="Que tait La Dernière Classe ?",
  attendus="Les élèves alsaciens parlaient surtout un dialecte germanique : le récit construit une Alsace francophone qui sert la mémoire nationale. Bel exercice sociocritique.",
  piege="Ne pas moquer le patriotisme du texte : l'analyser comme une prise de position de 1872."),
"labo": N("30 min", "Comparer le retour de l'IA et le retour de l'enseignant sur la même introduction.",
  piege="L'IA est souvent trop générale ou trop indulgente. Faire repérer un conseil juste et un conseil vide."),
"italia": N("15 min",
  "Verga, né à Catania, publie Vita dei campi (1880 : Rosso Malpelo, Cavalleria rusticana), puis I Malavoglia (1881). Capuana, né à Mineo, théorise le verismo. La Casa Verga est via Sant'Anna à Catania : visite possible hors cours.",
  questions="Quelle différence entre le narrateur de Zola et celui de Verga ?",
  attendus="Zola garde un narrateur savant ; Verga laisse parler le chœur du village."),
"bilan": N("10 min", "Semaine lourde en correction : annoncer la date du retour écrit. Rappeler la lecture du Bateau ivre (strophes 1 à 5)."),
}

NOTES[6] = {
"cover": N("3 min", "Deux textes A.1 : Le Bateau ivre (paire 2, face à Cendrars en semaine 8) et Le Symbolisme de Moréas (paire 4, face à Marinetti en semaine 8)."),
"objectifs": N("5 min", "Annoncer que les manifestes seront comparés en semaine 8 : garder ses notes.",
  piege="Mallarmé peut décourager : un vers ou deux, jamais un poème entier."),
"seances": N("3 min", "A : voyants, symbolistes, Zima. B : Rimbaud et le paragraphe d'analyse. C : Véra, traductions, manifeste express."),
"enigme": N("10 min",
  "Petites revues (La Vogue, Le Décadent), tirages minuscules, lectures entre poètes.",
  questions="Pourquoi choisir d'être difficile ?",
  attendus="Refuser le public bourgeois et la langue des journaux ; choisir ses lecteurs ; se distinguer."),
"frise": N("10 min",
  "Je est un autre apparaît dans la lettre à Izambard (13 mai 1871) et dans la lettre à Paul Demeny (15 mai 1871). Le Bateau ivre est écrit à l'été 1871 et publié en 1883 dans Les Poètes maudits de Verlaine. Les Illuminations paraissent dans La Vogue en 1886.",
  questions="Combien de temps entre l'écriture et la publication du Bateau ivre ?",
  attendus="Douze ans : la gloire arrive par d'autres poètes, pas par le public."),
"auteurs": N("20 min",
  "Rimbaud abandonne la poésie vers 21 ans et finit commerçant entre Aden et Harar. Verlaine. Mallarmé reçoit le mardi rue de Rome. Moréas, né à Athènes (Ioannis Papadiamantopoulos), donne son nom au symbolisme ; Maeterlinck (Gand) le porte au théâtre.",
  plus="Le symbolisme est largement fait par des étrangers et des francophones : le champ parisien attire et consacre."),
"outil": N("20 min",
  "Une définition, un exemple. Le sociolecte est la langue d'un groupe social, avec ses valeurs. Le refus de la langue commune est une prise de position.",
  source="P. V. Zima, Manuel de sociocritique, Picard, 1985 (rééd. L'Harmattan, 2000)."),
"texte1": N("40 min, séance B",
  "Le poème compte vingt-cinq quatrains d'alexandrins. Le je est le bateau : métaphore filée sur tout le poème. Les haleurs sont tués par des Peaux-Rouges dès la première strophe : le bateau perd ses guides.",
  questions="Qui dit je ? Que représente le bateau ?",
  attendus="Le bateau, le poète, la poésie libérée des règles : les trois lectures sont possibles si on les justifie.",
  piege="Ne pas réduire le poème à une biographie de Rimbaud (16 ans, fugue)."),
"texte2": N("30 min, séance A",
  "Le manifeste paraît dans le supplément littéraire du Figaro, le 18 septembre 1886. Faire relever les marques du genre : ennemis désignés, ton affirmatif, programme, nom d'école.",
  questions="Pourquoi publier un manifeste dans un grand journal ?",
  attendus="Pour faire date et nommer le groupe devant le public : on retrouvera le même geste chez Marinetti en 1909."),
"methode": N("40 min", "Distribuer un paragraphe qui paraphrase le Bateau ivre et le faire réécrire en groupes : idée, citation courte intégrée, analyse de l'effet.",
  piege="La citation n'est pas une preuve en soi : elle doit être commentée."),
"nouvelle": N("25 min, séance C",
  "Véra : le comte d'Athol refuse la mort de sa femme et continue de vivre comme si elle était là ; à la fin, la clé du tombeau tombe dans la chambre. Lien avec La Morte amoureuse (semaine 3) : deux amours plus forts que la mort.",
  questions="La fin confirme-t-elle le surnaturel ?",
  attendus="Elle le suggère sans le prouver : l'hésitation fantastique demeure."),
"labo": N("35 min", "Une strophe, trois versions italiennes : publiée, IA, étudiante. Critères : sens, rythme, images.",
  piege="Faire aussi vérifier les dates biographiques de Rimbaud données par l'IA : âge, dates de publication."),
"italia": N("15 min", "Pascoli publie Il fanciullino en 1897 ; D'Annunzio, Il piacere en 1889. Jeu : manifeste express d'un isme inventé, en cinq phrases, avec les marques du manifeste."),
"bilan": N("10 min", "Distribuer les rôles d'Ubu et de Salomé pour la lecture jouée de la semaine 7. Les textes sont sur Studium."),
}

NOTES[7] = {
"cover": N("3 min", "Trois paires A.1 cette semaine : théâtre (paire 5), poèmes en prose (paire 3, Gide), recueil de poèmes (paire 1, Vivien)."),
"objectifs": N("5 min",
  "Présenter René Vivien simplement : poétesse de la Belle Époque, née Pauline Tarn à Londres en 1877, morte en 1909, traductrice de Sappho, amours féminines assumées.",
  piege="La fiche indique 1902 pour Études et préludes ; l'édition originale chez Lemerre est généralement datée de 1901. Vérifier dans l'édition et le dire aux étudiants."),
"seances": N("3 min", "A : le Théâtre de l'Œuvre et Vivien. B : Gide et la conclusion. C : lecture jouée et labo."),
"enigme": N("10 min",
  "Le Théâtre de l'Œuvre de Lugné-Poe crée Salomé le 11 février 1896, pendant que Wilde est en prison à Reading, puis Ubu Roi le 10 décembre 1896 (Firmin Gémier joue Ubu). Le poète W. B. Yeats assiste à la création d'Ubu.",
  questions="Qu'ont en commun ces deux pièces que tout oppose ?",
  attendus="Un public choisi, une scène d'avant-garde, le scandale comme mode d'existence."),
"frise": N("10 min",
  "Salomé, écrite en français en 1891, est interdite à Londres en juin 1892 pendant les répétitions avec Sarah Bernhardt : la censure interdit de représenter des personnages bibliques. Elle paraît à Paris en 1893. Un coup de dés de Mallarmé paraît dans Cosmopolis en 1897."),
"auteurs": N("20 min",
  "Ubu naît d'une farce de lycéens à Rennes contre un professeur. Les Nourritures terrestres se vendent très peu à leur sortie avant de devenir le livre d'une génération après 1918.",
  questions="Pourquoi Wilde et Vivien écrivent-ils en français ?",
  attendus="Le français comme langue de l'art et de la liberté à Paris vers 1900."),
"outil": N("15 min", "Comparer trois scandales : Hernani (1830), les procès (1857), le Théâtre de l'Œuvre (1896). Revenir à la question du semestre.",
  attendus="Le pouvoir de consacrer passe des institutions (Académie, tribunaux) aux groupes et aux petites scènes."),
"texte1": N("30 min",
  "Lire les deux premières répliques très différemment : Salomé, lente, répétitive, lunaire ; Ubu, forte, grossière, comique. L'orthographe estes imite l'ancien français.",
  questions="Que promet chaque première réplique ?",
  attendus="Salomé : un désir et une fascination ; Ubu : une agression du public et du langage."),
"texte2": N("40 min, séance B",
  "Nathanaël est un disciple imaginaire. Faire repérer l'impératif, le futur, le tutoiement : une prose qui enseigne. Lire ensuite un sonnet de Vivien (Studium) et comparer deux libertés de 1900.",
  piege="Ne pas réduire Gide à l'autobiographie : la voix des Nourritures est construite."),
"methode": N("40 min", "Trois ouvertures possibles pour un même commentaire ; écarter les généralités du type De tout temps. Une bonne ouverture nomme une œuvre précise."),
"nouvelle": N("40 min, séance C", "Lecture jouée en petits groupes. Ne pas chercher la perfection : l'excès d'Ubu doit s'entendre. Terminer par cinq minutes sur les recueils de la partie B : comment les présenter à l'oral."),
"labo": N("30 min", "L'IA installe Ubu à Catania.",
  piege="L'IA tend à rendre Ubu gentil ou moralisateur : excellent départ pour parler de la violence comique de Jarry."),
"italia": N("15 min", "D'Annunzio écrit en français Le Martyre de saint Sébastien (1911), musique de Debussy. La Salomé de Richard Strauss (1905) suit la pièce de Wilde."),
"bilan": N("10 min", "Chacun annonce son roman bref (paire 6) pour la semaine 8 et relit les étapes de méthode avant l'atelier final."),
}

NOTES[8] = {
"cover": N("3 min", "Dernière semaine : trois paires A.1 (manifeste, poème long, roman bref), l'atelier final et le bilan. Rester au niveau des extraits : la lecture intégrale reste personnelle."),
"objectifs": N("5 min", "Garder 20 minutes en fin de séance C pour le bilan IA du semestre."),
"seances": N("3 min", "A : avant-gardes, guerre, romans brefs. B : atelier final. C : Années folles et bilan."),
"enigme": N("10 min",
  "Environ 1,4 million de soldats français sont morts entre 1914 et 1918.",
  questions="Fête pour oublier, fête de quelques-uns, ou deuil partout ?",
  attendus="Les trois : la fête est urbaine et minoritaire, le deuil est national."),
"frise": N("10 min",
  "Le manifeste de Marinetti paraît d'abord en italien dans des journaux de la péninsule début février 1909, mais c'est la une du Figaro du 20 février qui fait date. 1913 est une année extraordinaire ; Le Grand Meaulnes manque le Goncourt. Alain-Fournier est tué en septembre 1914. Valéry publie La Crise de l'esprit en 1919.",
  questions="Pourquoi Marinetti publie-t-il à Paris ?",
  attendus="Paris est alors la capitale qui consacre les avant-gardes."),
"auteurs": N("15 min", "Cendrars et Sonia Delaunay conçoivent la Prose du Transsibérien comme un livre dépliant de deux mètres. Gide : Lafcadio pousse Amédée Fleurissoire hors d'un train entre Rome et Naples.",
  questions="Quel roman bref choisissez-vous pour la paire 6, et pourquoi ?"),
"outil": N("15 min",
  "Chrononyme : un nom d'époque qui produit une image. Juan montre que les Années folles sont une histoire surtout parisienne et élitaire. Le Naour rappelle le deuil, la reconstruction et le refus du vote des femmes : la Chambre vote le suffrage féminin en 1919, le Sénat le refuse le 21 novembre 1922.",
  source="M. Juan, Les Années folles, PUF, Que sais-je ? ; J.-Y. Le Naour, 1922-1929. Les années folles ?, Perrin, 2022."),
"texte1": N("30 min, séance A",
  "Comparer les marques du manifeste avec Moréas (semaine 6). Cendrars n'est pas dans le domaine public : courtes citations seulement.",
  questions="Comment un poème peut-il aller vite ?",
  attendus="Vers libres, énumérations, absence de ponctuation, ruptures, noms de lieux."),
"texte2": N("30 min, séance A",
  "Le narrateur du Grand Meaulnes est François Seurel. Pour Gide, raconter simplement la scène du train.",
  questions="189… : pourquoi une date incomplète ?",
  attendus="Un temps de souvenir et de légende, déjà un peu effacé."),
"methode": N("2 h, séance B", "Atelier final non noté, retour écrit. Proposer un extrait du domaine public (Alain-Fournier ou Marinetti).",
  piege="Rappeler la relecture finale : langue, citations exactes, temps des verbes."),
"nouvelle": N("30 min, séance C",
  "René Maran, fonctionnaire colonial en Oubangui-Chari, reçoit le Goncourt le 14 décembre 1921 pour Batouala ; sa préface critique la colonisation et il doit quitter l'administration coloniale. Le Manifeste de Breton et Batouala ne sont pas dans le domaine public : citations courtes.",
  plus="Maran ouvre vers les littératures francophones (Mabanckou, Sarr, Slimani) : occasion naturelle de présenter vos recherches."),
"labo": N("30 min", "Chaque étudiant repart avec une fiche A.1 corrigée : utile pour l'oral.",
  piege="Faire compter les erreurs de l'IA et les classer : dates, attributions, citations inventées."),
"italia": N("15 min", "Pitoëff crée Six personnages en quête d'auteur à la Comédie des Champs-Élysées le 10 avril 1923. Ungaretti écrit aussi en français et fréquente Apollinaire."),
"bilan": N("20 min", "Revenir à l'énigme de la semaine 1 et à la question du semestre : qui a le pouvoir de dire ce qu'est la bonne littérature ? Laisser l'Atelier du siècle ouvert après le cours."),
}
