# Plan de lecture : les œuvres à lire en entier (liste A.1 et partie B de la fiche),
# leur volume approximatif, les clés de lecture pour l'étudiant et la fiche de l'enseignant.
# Volumes indicatifs (éditions de poche courantes) ; durées calculées pour un lecteur B1-B2
# (environ 25 pages de prose ou 25 à 30 pages de poésie par heure, relecture comprise).

OEUVRES = [
 # ---------------------------------------------------------------- A.1
 dict(id="meditations", fiche="A.1 · paire 1", genre="Recueil de poèmes", auteur="Lamartine", titre="Méditations poétiques", date="1820",
  semaine=2, pages="env. 120 p. (24 poèmes dans l'édition de 1820)", heures=4, leger=False, passages=["lac"],
  acces="Domaine public : Wikisource (édition originale 1820) ; Gallica.",
  cles=["Lire d'abord L'Isolement (poème d'ouverture), Le Vallon, Le Lac et L'Automne : le recueil y tient tout entier.",
        "Suivre la figure d'Elvire, femme aimée absente puis morte : le recueil est un deuil qui se cherche une foi.",
        "Observer la nature : elle n'est jamais décrite pour elle-même, elle répond à l'âme du poète."],
  verif=[("Quel poème ouvre le recueil, et quelle est sa célèbre formule sur l'absence ?", "L'Isolement : Un seul être vous manque, et tout est dépeuplé."),
         ("Où se passe Le Lac et qui est la femme absente ?", "Au lac du Bourget, près d'Aix-les-Bains ; la femme est Elvire, inspirée de Julie Charles."),
         ("Quel rôle joue la religion dans le recueil ?", "Le poète passe du désespoir à une consolation chrétienne : Dieu et la nature répondent à la perte.")],
  prof=dict(
   resume="Recueil de 24 poèmes en 1820 (augmenté dans les éditions suivantes). Le fil est autobiographique sans être narratif : l'amour pour Julie Charles, rencontrée à Aix-les-Bains en 1816, morte en décembre 1817, devient la figure d'Elvire. Les poèmes alternent méditations sur la perte (L'Isolement, Le Vallon, L'Automne), sur le temps (Le Lac), et méditations philosophiques ou religieuses (L'Homme, adressé à Byron ; La Prière ; L'Immortalité ; Dieu).",
   structure="Pas d'architecture narrative stricte : ouverture par L'Isolement, puis alternance de poèmes intimes et de poèmes de réflexion. Formes classiques (alexandrins, quatrains, strophes lyriques), langue noble, périphrases héritées du XVIIIe siècle.",
   savoir=["Succès immédiat en 1820 : le recueil est vu comme l'acte de naissance du lyrisme romantique en France.",
           "Lamartine dira avoir fait descendre la poésie du Parnasse (préface de 1849) : il remplace les cordes de la lyre par les fibres du cœur.",
           "Restauration : poésie catholique et monarchiste à ses débuts, avant le Lamartine républicain de 1848."],
   angle="Sociocritique : un aristocrate de province, encore inconnu, entre d'un coup au centre du champ poétique ; la sincérité du moi devient une valeur de marché. Le recueil répond à l'attente d'un public de la Restauration en quête de foi et d'émotion après la Révolution et l'Empire.",
   passages=["L'Isolement (ouverture du recueil)", "Le Lac (dossier S2)", "L'Automne (strophe finale sur la mort)"],
   piege="Ne pas présenter Lamartine comme un poète de la nature au sens moderne : la nature est un miroir de l'âme et un signe de Dieu.")),
 dict(id="vivien", fiche="A.1 · paire 1", genre="Recueil de poèmes", auteur="René Vivien", titre="Études et préludes", date="1901",
  semaine=7, pages="env. 90 p.", heures=3, leger=True, passages=["vivien"],
  acces="Domaine public : Wikisource (Études et Préludes, 1901, texte entier).",
  cles=["Lire les poèmes par séries : la mort, la femme aimée, la nature (soir, mer, violettes).",
        "Repérer les formes : sonnets et strophes régulières, rimes riches, héritage de Baudelaire et du Parnasse.",
        "Se demander qui parle : une voix qui aime une femme, publiée sous un nom masculin par une femme."],
  verif=[("Qui est René Vivien ?", "Pauline Mary Tarn (1877-1909), poétesse d'origine britannique écrivant en français à Paris."),
         ("Sous quel nom paraît le premier recueil, et pourquoi est-ce important ?", "Sous le nom de R. Vivien : le public croit d'abord lire un homme."),
         ("Quels sont les deux grands thèmes du recueil ?", "L'amour pour une femme et la mort, souvent liés (Sonnet à la Mort).")],
  prof=dict(
   resume="Premier recueil de René Vivien (1901). Des poèmes brefs, souvent des sonnets, qui célèbrent la femme aimée (inspirée notamment par Natalie Clifford Barney et par l'amie d'enfance Violet Shillito, morte en 1901), le soir, la mer, et la mort désirée comme une épouse. Langue précieuse, symboles floraux (le lys, la violette), couleurs pâles.",
   structure="Recueil de pièces courtes sans intrigue ; on peut le lire en trois séries thématiques (amour, mort, nature). Formes fixes, alexandrin dominant.",
   savoir=["Vivien appartient au milieu saphique de la Belle Époque à Paris (salon de Natalie Barney) ; on l'appelait la Muse aux violettes.",
           "Œuvre longtemps marginalisée, redécouverte par la critique féministe à la fin du XXe siècle.",
           "Forme classique, contenu transgressif : la subversion passe par le sujet, non par la versification."],
   angle="Bourdieu : une femme étrangère et riche entre dans le champ poétique parisien avec un pseudonyme masculin, des formes consacrées (sonnet, alexandrin) et un éditeur légitime (Lemerre, l'éditeur du Parnasse). Le capital formel classique protège un contenu qui ne l'est pas.",
   passages=["Dédicace (poème d'ouverture : l'apparition de la femme aimée)", "Sonnet à la Mort (dossier S7)", "Lucidité (portrait d'une femme fatale, retournement du regard masculin)"],
   piege="Ne pas lire seulement la biographie : analyser aussi la métrique et l'intertexte baudelairien.")),
 dict(id="bateau", fiche="A.1 · paire 2", genre="Poème long", auteur="Rimbaud", titre="Le Bateau ivre", date="1871",
  semaine=6, pages="100 vers (4 pages)", heures=1, leger=True, passages=["bateau"],
  acces="Domaine public : texte intégral dans le dossier de la semaine 6.",
  cles=["Le lire trois fois : à voix haute d'abord (pour le rythme), puis avec un dictionnaire, puis strophe par strophe.",
        "Repérer les quatre mouvements : libération, immersion, visions, retour à l'enfance.",
        "Le relier à la lettre du Voyant (mai 1871) : se faire voyant par un long dérèglement de tous les sens."],
  verif=[("Qui dit je dans le poème ?", "Un bateau, qui est aussi une figure du poète."),
         ("Que deviennent les haleurs au début ?", "Ils sont tués par des Peaux-Rouges ; le bateau est libre."),
         ("Quelle image ferme le poème ?", "Un enfant qui lâche un bateau frêle sur une flache (flaque) d'Europe ; le bateau ne peut plus naviguer.")],
  prof=dict(
   resume="Un bateau fluvial, libéré de ses haleurs, descend les fleuves jusqu'à la mer, s'y abandonne, connaît des visions extraordinaires, puis, épuisé, regrette l'Europe et souhaite le naufrage. La fin ramène à une flaque d'enfance où flotte un bateau de papier.",
   structure="25 quatrains d'alexandrins (100 vers). 1-4 : libération ; 5-7 : baptême et immersion ; 8-17 : visions (j'ai vu, je sais, j'ai rêvé) ; 18-25 : épuisement, regret, désir de mort, image de l'enfant.",
   savoir=["Écrit à Charleville en 1871 par un adolescent de 16-17 ans qui n'a jamais vu la mer ; Rimbaud l'apporte à Paris en septembre 1871 pour se présenter à Verlaine.",
           "Publié en 1883 par Verlaine dans la série Les Poètes maudits.",
           "Vocabulaire rare et technique (marine, géographie, mots inventés) : ne pas tout traduire en classe, faire sentir le rythme."],
   angle="Sociocritique : un jeune provincial sans capital (ni argent, ni relations) fabrique sa carte d'entrée dans le champ parisien ; le poème est aussi un adieu aux formes reçues tout en restant en alexandrins réguliers. Le regret de l'Europe aux anciens parapets peut se lire comme le prix de la rupture.",
   passages=["Strophes 1-2 (libération)", "Strophe 8 : Et j'ai vu quelquefois ce que l'homme a cru voir", "Strophes 23-25 (retour à la flache)"],
   piege="Ne pas réduire le poème à une allégorie biographique : garder le double niveau, navire et poète.")),
 dict(id="transsiberien", fiche="A.1 · paire 2", genre="Poème long", auteur="Cendrars", titre="Prose du Transsibérien et de la petite Jehanne de France", date="1913",
  semaine=8, pages="env. 450 vers (15 pages)", heures=1.5, leger=True, passages=[],
  acces="Œuvre protégée (Cendrars meurt en 1961) : édition personnelle ou bibliothèque (Du monde entier, Poésie/Gallimard).",
  cles=["Lire d'une traite, comme un voyage en train : le rythme compte plus que chaque image.",
        "Suivre le refrain de Jehanne : Dis, Blaise, sommes-nous bien loin de Montmartre ?",
        "Regarder une reproduction du livre de 1913 (dépliant de deux mètres, couleurs de Sonia Delaunay) : le poème est aussi un objet."],
  verif=[("Qui voyage avec le narrateur ?", "La petite Jehanne de France, une jeune prostituée de Montmartre."),
         ("Quel âge se donne le narrateur au début ?", "Seize ans (En ce temps-là j'étais en mon adolescence)."),
         ("Qu'a de particulier l'édition de 1913 ?", "Un livre dépliant d'environ deux mètres, illustré en couleurs par Sonia Delaunay : le premier livre simultané.")],
  prof=dict(
   resume="Le narrateur, adolescent, raconte un voyage en Transsibérien de Moscou vers la Mandchourie, pendant la guerre russo-japonaise (1904-1905), avec Jehanne, jeune prostituée parisienne. Les images de la Russie, de la guerre et du train se mêlent aux souvenirs et à la nostalgie de Paris ; le poème finit à Paris.",
   structure="Vers libres de longueurs très variables, sans strophes régulières ; refrains (Dis, Blaise…), énumérations de gares et de noms, accélérations et ralentissements comme le train.",
   savoir=["Publié en 1913 aux Éditions des Hommes nouveaux, sous la forme d'un dépliant peint par Sonia Delaunay ; tirage prévu de 150 exemplaires dont la hauteur cumulée devait égaler la tour Eiffel.",
           "Le voyage est en partie imaginaire : Cendrars a vécu en Russie, mais la biographie est réinventée.",
           "Modernité : vitesse, simultanéité, collage, voisinage avec Apollinaire (Zone, 1913) et le futurisme."],
   angle="Bourdieu : une avant-garde qui joue sur l'objet-livre rare (tirage limité, peinture) pour conquérir un capital symbolique ; le poète se fabrique une légende de bourlingueur. Comparer avec Rimbaud : le voyage réel en train contre le voyage imaginaire en bateau.",
   passages=["Premier vers : En ce temps-là j'étais en mon adolescence", "Le refrain de Jehanne (Dis, Blaise…)", "La fin parisienne"],
   piege="Ne pas distribuer le texte intégral en classe : il est protégé ; citer brièvement et renvoyer à l'édition.")),
 dict(id="spleen", fiche="A.1 · paire 3", genre="Poèmes en prose", auteur="Baudelaire", titre="Le Spleen de Paris (Petits poèmes en prose)", date="1869",
  semaine=4, pages="env. 130 p. (50 poèmes)", heures=5, leger=False, passages=["etranger", "enivrez"],
  acces="Domaine public : Wikisource (Petits Poèmes en prose).",
  cles=["Commencer par la dédicace À Arsène Houssaye : Baudelaire y définit le projet d'une prose poétique.",
        "Lire par familles : poèmes de la foule et de la ville (Les Foules, Les Veuves, Les Yeux des pauvres), poèmes de l'idéal (L'Étranger, Enivrez-vous, Any where out of the world), poèmes cruels (Assommons les pauvres !).",
        "Comparer avec Les Fleurs du mal : mêmes thèmes (spleen, idéal, ville), mais sans vers ni rime."],
  verif=[("À qui est dédié le recueil, et quel projet y est annoncé ?", "À Arsène Houssaye ; le miracle d'une prose poétique, musicale sans rythme et sans rime."),
         ("Quel est le premier poème du recueil ?", "L'Étranger."),
         ("Citez un poème qui se passe dans la foule ou dans la rue.", "Par exemple Les Foules, Les Veuves, Les Yeux des pauvres, Le Vieux Saltimbanque, Perte d'auréole.")],
  prof=dict(
   resume="Cinquante poèmes en prose publiés après la mort de Baudelaire (1869), dans le volume IV des Œuvres complètes. Ils mettent en scène le poète dans le Paris transformé par Haussmann : foules, pauvres, veuves, saltimbanques, cafés, mais aussi rêves d'évasion (L'Invitation au voyage en prose, Any where out of the world) et moralités ironiques.",
   structure="Pas de récit d'ensemble ; Baudelaire disait que l'on pouvait couper le recueil où l'on voulait, comme un serpent dont chaque tronçon vit séparément (dédicace). Formes variées : anecdote, dialogue, allégorie, fable.",
   savoir=["Modèle revendiqué : Aloysius Bertrand, Gaspard de la nuit (1842).",
           "Le poème en prose devient un genre majeur après Baudelaire (Rimbaud, Mallarmé, puis Gide, paire 3).",
           "1857 : procès des Fleurs du mal ; le poème en prose est aussi une issue après la condamnation."],
   angle="Sociocritique : le poète dans la ville moderne, déclassé, flâneur, qui regarde les pauvres et se regarde les regarder (Les Yeux des pauvres). Bourdieu : Baudelaire est un fondateur de l'autonomie du champ littéraire, contre le marché (l'or, dans L'Étranger) et contre la morale bourgeoise.",
   passages=["L'Étranger (dossier S4)", "Enivrez-vous (dossier S4)", "Les Yeux des pauvres (le couple au café et la famille pauvre)", "Perte d'auréole (le poète perd son auréole dans la boue du boulevard)"],
   piege="Ne pas confondre avec Les Fleurs du mal : les poèmes Au lecteur et L'Albatros (A.2) sont en vers et appartiennent aux Fleurs du mal.")),
 dict(id="nourritures", fiche="A.1 · paire 3", genre="Poèmes en prose", auteur="Gide", titre="Les Nourritures terrestres", date="1897",
  semaine=7, pages="env. 150 p.", heures=5, leger=False, passages=["nourritures"],
  acces="Domaine public en Italie et en France : Wikisource (Nourritures terrestres, livres I à VIII) ; édition de poche Folio.",
  cles=["Repérer qui parle (un narrateur, disciple de Ménalque) et à qui (Nathanaël, un jeune lecteur imaginaire).",
        "Suivre les mots clés : ferveur, désir, disponibilité, désinstruction.",
        "Lire la fin : le narrateur demande à Nathanaël de jeter le livre. Que veut dire un livre qui se rejette lui-même ?"],
  verif=[("Qui est Nathanaël ?", "Le jeune destinataire imaginaire à qui le narrateur enseigne la ferveur."),
         ("Qui est Ménalque ?", "Le maître du narrateur, figure de la vie libre et du désir."),
         ("Que demande la dernière page ?", "De jeter le livre et de chercher sa propre vie.")],
  prof=dict(
   resume="Livre de versets, de récits brefs, de rondes et de chants, adressé à Nathanaël. Le narrateur, guéri d'une maladie et revenu de voyages (Afrique du Nord, Italie), enseigne une morale du désir, de la sensation et de la disponibilité, contre la morale apprise. Huit livres, un hymne et un envoi.",
   structure="Livres I à VIII de longueurs inégales, mélange de prose poétique, de dialogues (Ménalque raconte sa vie au livre IV), de chansons et de listes (les fruits, les villes, les sources). Un Hymne en guise de conclusion et un Envoi.",
   savoir=["Le livre suit les séjours de Gide en Afrique du Nord (1893-1895), vécus comme une libération du corps et de la morale protestante.",
           "Échec commercial à sa parution (quelques centaines d'exemplaires en dix ans), puis bréviaire de la jeunesse après 1918.",
           "Gide reçoit le prix Nobel en 1947 ; il meurt en 1951 (œuvre entrée dans le domaine public en 2022 dans l'Union européenne)."],
   angle="Bourdieu : un héritier de la bourgeoisie protestante, qui ne dépend pas de ses ventes, peut se permettre un livre sans public immédiat ; le capital économique rend possible l'autonomie esthétique. Comparer avec Baudelaire (paire 3) : la prose poétique naît ici du voyage et des sens, non de la ville.",
   passages=["Livre I : Nathanaël, je t'enseignerai la ferveur (dossier S7)", "Livre IV : le récit de Ménalque", "Envoi : Nathanaël, à présent, jette mon livre"],
   piege="Ne pas lire le livre comme un simple hédonisme : le désir y est aussi une discipline et une ascèse inversée.")),
 dict(id="moreas", fiche="A.1 · paire 4", genre="Manifeste littéraire", auteur="Moréas", titre="Le Symbolisme", date="1886",
  semaine=6, pages="env. 4 p.", heures=0.5, leger=True, passages=["moreas"],
  acces="Domaine public : Wikisource (Les Premières Armes du symbolisme) ; Gallica (Le Figaro du 18 septembre 1886).",
  cles=["Repérer les ennemis nommés : enseignement, déclamation, fausse sensibilité, description objective.",
        "Reformuler la définition : vêtir l'Idée d'une forme sensible.",
        "Relever la généalogie que Moréas se donne (Baudelaire, Mallarmé, Verlaine, Banville)."],
  verif=[("Où et quand paraît le manifeste ?", "Dans le supplément littéraire du Figaro, le 18 septembre 1886."),
         ("Quel nom Moréas veut-il imposer à la place de décadents ?", "Symbolistes."),
         ("Quelle est la mission de la poésie symboliste selon lui ?", "Vêtir l'Idée d'une forme sensible, sans jamais dire l'Idée en soi.")],
  prof=dict(
   resume="Article-manifeste de Jean Moréas (poète d'origine grecque, Ioannis Papadiamantopoulos). Il soutient que la littérature évolue par cycles, que le romantisme et le naturalisme sont épuisés, et définit une poésie qui suggère l'Idée par des symboles. Il évoque aussi la prose symboliste et le rythme nouveau du vers.",
   structure="Trois mouvements : une théorie de l'évolution littéraire ; la généalogie (Baudelaire précurseur, Mallarmé, Verlaine, Banville) ; la définition de l'art symboliste, puis du style et du vers.",
   savoir=["Le texte répond à des articles qui moquaient les poètes décadents ; il veut donner un nom positif à une génération.",
           "Moréas quittera le symbolisme dès 1891 pour fonder l'École romane.",
           "Le manifeste paraît dans un grand quotidien : la presse est le lieu où se jouent les batailles d'écoles."],
   angle="Bourdieu : le manifeste est une prise de position typique des nouveaux entrants dans le champ, qui se distinguent des positions établies (Parnasse, naturalisme) et se dotent d'ancêtres prestigieux pour accumuler du capital symbolique.",
   passages=["La définition : Ennemie de l'enseignement… (dossier S6)", "La liste des grands noms accusés d'obscurité (Pindare, Shakespeare, Dante, Goethe, Flaubert)"],
   piege="Ne pas confondre le symbolisme comme mouvement (1886-1900) et l'usage de symboles en général.")),
 dict(id="futurisme", fiche="A.1 · paire 4", genre="Manifeste littéraire", auteur="Marinetti", titre="Manifeste du futurisme", date="1909",
  semaine=8, pages="env. 5 p.", heures=0.5, leger=True, passages=[],
  acces="Domaine public : Gallica (Le Figaro du 20 février 1909, première page).",
  cles=["Lire d'abord le récit d'ouverture (la course en automobile, l'accident dans le fossé) : le manifeste commence comme une nouvelle.",
        "Numéroter les onze points du programme : vitesse, danger, guerre, destruction des musées.",
        "Comparer avec Moréas : même journal, mais table rase au lieu de généalogie."],
  verif=[("Où paraît le manifeste ?", "À la une du Figaro, à Paris, le 20 février 1909, en français."),
         ("À quoi Marinetti compare-t-il l'automobile de course ?", "Il la déclare plus belle que la Victoire de Samothrace."),
         ("Que veut-il faire des musées et des bibliothèques ?", "Les détruire : ce sont des cimetières du passé.")],
  prof=dict(
   resume="Filippo Tommaso Marinetti, poète italien de langue française né à Alexandrie, publie à Paris le manifeste fondateur du futurisme. Un prologue narratif (nuit d'insomnie, course en automobile, chute dans un fossé d'usine, renaissance) précède onze articles : amour du danger, beauté de la vitesse, glorification de la guerre, mépris de la femme, destruction des musées et des académies.",
   structure="Prologue narratif ; programme en onze points ; conclusion lyrique sur la jeunesse des futuristes (les plus âgés ont trente ans).",
   savoir=["Choisir Paris et Le Figaro, c'est viser la capitale symbolique de la littérature européenne.",
           "Certaines formules (la guerre seule hygiène du monde, le mépris de la femme) annoncent l'engagement de Marinetti auprès du fascisme ; il faut les commenter, non les taire.",
           "Pour des étudiants italiens : lien direct avec l'histoire de l'Italie et de ses avant-gardes."],
   angle="Bourdieu : stratégie de l'avant-garde par la rupture absolue et le scandale médiatique ; un entrant étranger utilise le centre parisien pour se consacrer. Comparer avec Moréas : la légitimation par les ancêtres contre la légitimation par la table rase.",
   passages=["Le récit de l'accident (prologue)", "Article 4 : la beauté de la vitesse et la Victoire de Samothrace", "Article 10 : détruire les musées, les bibliothèques"],
   piege="Ne pas citer de mémoire : vérifier chaque formule sur le texte du Figaro, les traductions circulent avec des variantes.")),
 dict(id="salome", fiche="A.1 · paire 5", genre="Théâtre", auteur="Wilde", titre="Salomé", date="1891-1893",
  semaine=7, pages="env. 60 p. (un acte)", heures=2, leger=True, passages=["salome"],
  acces="Domaine public : Wikisource (texte français original).",
  cles=["Suivre les répétitions (la lune, regarder, belle ce soir) : la pièce fonctionne comme une incantation.",
        "Repérer les trois désirs : le Syrien désire Salomé, Salomé désire Iokanaan, Hérode désire Salomé.",
        "Lire la fin à voix haute : la danse, la tête sur le plateau d'argent, le baiser, l'ordre d'Hérode."],
  verif=[("En quelle langue Wilde écrit-il Salomé ?", "En français, à Paris, en 1891."),
         ("Que demande Salomé après sa danse ?", "La tête de Iokanaan (Jean-Baptiste) sur un bassin d'argent."),
         ("Comment finit la pièce ?", "Hérode ordonne : Tuez cette femme ! Les soldats écrasent Salomé sous leurs boucliers.")],
  prof=dict(
   resume="Drame en un acte. Sur la terrasse du palais d'Hérode, Salomé, fille d'Hérodias, est fascinée par le prophète Iokanaan, prisonnier dans une citerne, qui la repousse. Hérode, qui la désire, lui demande de danser et promet ce qu'elle voudra. Elle danse la danse des sept voiles et réclame la tête du prophète, puis embrasse la bouche de la tête coupée. Horrifié, Hérode la fait tuer.",
   structure="Un seul acte continu, sans changement de décor. Progression : présages (la lune), rencontre de Salomé et de Iokanaan, suicide du Syrien, entrée d'Hérode et d'Hérodias, danse, demande de la tête, monologue de Salomé, mort.",
   savoir=["Répétitions à Londres en 1892 avec Sarah Bernhardt, arrêtées par la censure (interdiction de représenter des personnages bibliques).",
           "Publication en français (1893), traduction anglaise (1894) illustrée par Aubrey Beardsley.",
           "Création à Paris par Lugné-Poe au Théâtre de l'Œuvre en 1896, pendant que Wilde est en prison ; opéra de Richard Strauss en 1905."],
   angle="Sociocritique : la figure de Salomé, femme fatale fin de siècle (après Flaubert, Hérodias, et Gustave Moreau), dit les peurs masculines d'une époque. Bourdieu : un écrivain irlandais choisit la langue de Paris pour accéder au capital symbolique du symbolisme français.",
   passages=["La scène d'ouverture (dossier S7)", "La rencontre de Salomé et de Iokanaan", "Le monologue final de Salomé devant la tête"],
   piege="La pièce peut choquer ; préparer les étudiants à lire la violence et l'érotisme comme des motifs symbolistes.")),
 dict(id="ubu", fiche="A.1 · paire 5", genre="Théâtre", auteur="Jarry", titre="Ubu Roi", date="1896",
  semaine=7, pages="env. 80 p. (cinq actes)", heures=2.5, leger=True, passages=["ubu"],
  acces="Domaine public : Wikisource (Ubu roi, 1896).",
  cles=["Lire vite et à voix haute : c'est une farce, le plaisir est dans le rythme et les mots inventés.",
        "Suivre l'intrigue de Macbeth en parodie : complot, meurtre du roi, tyrannie, guerre, fuite.",
        "Faire la liste des mots inventés (merdre, phynance, cornegidouille, de par ma chandelle verte)."],
  verif=[("Qui pousse Père Ubu à tuer le roi Venceslas ?", "Mère Ubu."),
         ("Quel est le premier mot de la pièce ?", "Merdre."),
         ("Où se passe l'action ?", "En Pologne, c'est-à-dire, dit Jarry, nulle part.")],
  prof=dict(
   resume="Père Ubu, poussé par Mère Ubu, tue le roi de Pologne Venceslas et s'empare du trône. Tyran grotesque, il massacre les nobles, les magistrats et les financiers pour prendre leurs biens (la phynance). Le fils survivant du roi, Bougrelas, et l'armée russe le chassent ; après une guerre burlesque, Ubu et Mère Ubu s'enfuient en bateau vers la France.",
   structure="Cinq actes courts, nombreux changements de lieu, scènes brèves ; parodie des structures de Shakespeare (Macbeth, Hamlet, Richard III).",
   savoir=["Création le 10 décembre 1896 au Théâtre de l'Œuvre (Lugné-Poe), Firmin Gémier dans le rôle d'Ubu ; tumulte dès le premier mot.",
           "Origine : farce de lycéens à Rennes contre un professeur de physique, M. Hébert.",
           "Ancêtre revendiqué du surréalisme et du théâtre de l'absurde."],
   angle="Bourdieu : l'avant-garde de l'Œuvre provoque le public bourgeois pour se distinguer ; le scandale est un capital. Sociocritique : Ubu caricature le pouvoir absolu, la cupidité et la bêtise ; on peut le lire comme une satire du bourgeois et de la politique.",
   passages=["Acte I, scène 1 (dossier S7)", "Acte III : la réforme des finances (Ubu fait passer les nobles à la trappe)", "Acte V : la fuite en bateau"],
   piege="Ne pas chercher de psychologie : Jarry voulait un jeu de marionnettes, masques et voix artificielles.")),
 dict(id="meaulnes", fiche="A.1 · paire 6", genre="Roman bref", auteur="Alain-Fournier", titre="Le Grand Meaulnes", date="1913",
  semaine=8, pages="env. 260 p. (trois parties)", heures=11, leger=False, passages=["meaulnes"],
  acces="Domaine public : Wikisource (Le Grand Meaulnes, parties I à III et épilogue) ; nombreuses éditions de poche.",
  cles=["Lire la première partie d'un bloc (17 chapitres) : arrivée de Meaulnes, fugue, fête étrange, rencontre d'Yvonne.",
        "Tenir une liste des personnages : François Seurel (narrateur), Augustin Meaulnes, Yvonne et Frantz de Galais, Valentine.",
        "Suivre le thème de la quête : retrouver le domaine perdu, ou retrouver l'enfance ?"],
  verif=[("Qui raconte l'histoire ?", "François Seurel, fils des instituteurs de Sainte-Agathe, ami de Meaulnes."),
         ("Que découvre Meaulnes lors de sa fugue ?", "Un domaine mystérieux où se prépare une fête étrange ; il y rencontre Yvonne de Galais."),
         ("Pourquoi Meaulnes quitte-t-il Yvonne après leur mariage ?", "Pour tenir une promesse faite à Frantz : retrouver Valentine, la fiancée de Frantz.")],
  prof=dict(
   resume="Partie I : à Sainte-Agathe, Augustin Meaulnes, 17 ans, arrive chez les Seurel ; parti chercher des grands-parents à la gare, il se perd et arrive dans un domaine où se prépare une fête pour le mariage de Frantz de Galais ; il y rencontre Yvonne, sœur de Frantz ; la fiancée de Frantz ne vient pas et la fête se défait. Partie II : Meaulnes ne retrouve pas le chemin ; Frantz, devenu bohémien, passe à l'école ; Meaulnes part pour Paris. Partie III : François retrouve Yvonne ; Meaulnes l'épouse mais part le lendemain pour tenir sa promesse à Frantz (retrouver Valentine, qu'il a lui-même connue à Paris) ; Yvonne meurt après la naissance de sa fille ; Meaulnes revient avec Frantz et Valentine, prend sa fille et s'en va.",
   structure="Trois parties (17, 12 et 16 chapitres environ) et un épilogue ; narration rétrospective de François, qui reconstitue aussi ce qu'il n'a pas vu (le journal de Meaulnes dans la partie III).",
   savoir=["Le roman manque le prix Goncourt 1913 ; Alain-Fournier (Henri Alban Fournier) est tué au front le 22 septembre 1914.",
           "Monde rural du Cher et de la Sologne, école de la Troisième République : le père du narrateur est instituteur, comme les parents de l'auteur.",
           "Roman entre réalisme et merveilleux : la fête étrange est un épisode de conte."],
   angle="Sociocritique : le monde des instituteurs républicains et des châteaux ruinés (les Galais) ; la quête d'un domaine perdu peut se lire comme la nostalgie d'une France rurale à la veille de 1914.",
   passages=["L'incipit (dossier S8)", "Partie I, chapitre 13-15 : la fête étrange", "Épilogue : Meaulnes emporte sa fille"],
   piege="Ne pas résumer le roman comme une simple histoire d'amour : la quête, l'amitié et le récit de souvenir comptent autant.")),
 dict(id="caves", fiche="A.1 · paire 6", genre="Roman bref", auteur="Gide", titre="Les Caves du Vatican", date="1914",
  semaine=8, pages="env. 250 p. (cinq livres)", heures=10, leger=False, passages=[],
  acces="Domaine public en Italie et en France, absent de Wikisource : édition de poche (Folio) ou bibliothèque.",
  cles=["Lire le livre V (Lafcadio) en priorité si le temps manque : la scène du train entre Rome et Naples est le centre du roman.",
        "Tenir la liste de la famille : Anthime Armand-Dubois, Julius de Baraglioul, Amédée Fleurissoire, Lafcadio Wluiki, l'escroc Protos.",
        "Se demander ce qu'est un acte gratuit : agir sans motif est-il possible ?"],
  verif=[("Qu'est-ce que l'escroquerie au centre du roman ?", "Faire croire que le pape a été enfermé dans les caves du Vatican et remplacé par un faux pape, pour soutirer de l'argent aux catholiques."),
         ("Que fait Lafcadio dans le train ?", "Il pousse sans raison Amédée Fleurissoire hors du wagon : l'acte gratuit."),
         ("Comment Gide appelle-t-il ce livre ?", "Une sotie, et non un roman.")],
  prof=dict(
   resume="Cinq livres, chacun centré sur un personnage. Anthime Armand-Dubois, savant franc-maçon, se convertit après un miracle. Julius de Baraglioul, romancier académique, cherche un personnage qui agirait sans motif. Lafcadio Wluiki, demi-frère illégitime de Julius, jeune homme libre et séduisant. Amédée Fleurissoire, naïf provincial, part pour Rome délivrer le pape qu'une bande d'escrocs (Protos) prétend séquestré. Dans le train de Rome à Naples, Lafcadio pousse Fleurissoire par la portière, sans raison.",
   structure="Cinq livres (Anthime Armand-Dubois, Julius de Baraglioul, Amédée Fleurissoire, Le Mille-Pattes, Lafcadio) ; narrateur ironique qui intervient souvent ; intrigues croisées, coïncidences de vaudeville.",
   savoir=["Gide appelle le livre une sotie (genre satirique médiéval), pour le distinguer du roman sérieux.",
           "Une partie de l'action se passe en Italie (Rome, Naples) : utile pour des étudiants de Catane.",
           "L'acte gratuit de Lafcadio sera repris par les surréalistes et discuté par les existentialistes."],
   angle="Sociocritique : satire de la bourgeoisie catholique, de la franc-maçonnerie scientiste et du roman académique (Julius). Bourdieu : Gide écrit contre la position du romancier consacré, dans une forme ironique qui montre ses propres conventions.",
   passages=["Livre I : la conversion d'Anthime", "Livre V : la scène du train (l'acte gratuit)", "La fin : Lafcadio face à Geneviève"],
   piege="Ne pas présenter l'acte gratuit comme une morale de Gide : le roman le met à distance par l'ironie.")),
 # ---------------------------------------------------------------- B
 dict(id="mateo", fiche="Partie B", genre="Nouvelle", auteur="Mérimée", titre="Mateo Falcone", date="1829",
  semaine=2, pages="env. 15 p.", heures=1, leger=True, passages=["mateo"],
  acces="Domaine public : Wikisource.", cles=["Une nouvelle en une seule journée : suivre l'heure et les lieux.", "Repérer la montre : objet de la tentation et de la trahison.", "Lire le dénouement à voix haute (dossier S2)."],
  verif=[("Pourquoi Fortunato livre-t-il le bandit ?", "Pour une montre en argent offerte par l'adjudant."), ("Que fait Mateo à son fils ?", "Il le tue, pour trahison.")],
  prof=dict(resume="En Corse, Fortunato, dix ans, seul à la maison, cache le bandit Gianetto poursuivi par les voltigeurs, puis le livre à l'adjudant contre une montre. Son père Mateo, qui tient l'hospitalité pour sacrée, l'emmène dans un ravin et le tue.", structure="Récit linéaire en une journée, narrateur sobre, dialogue sec, chute.", savoir=["Publiée dans la Revue de Paris en 1829, reprise dans Mosaïque (1833)."], angle="Deux lois s'affrontent : l'État et le code de l'honneur ; la Corse vue de Paris.", passages=["Le dénouement (dossier S2)"], piege="Ne pas psychologiser Mateo.")),
 dict(id="morte", fiche="Partie B", genre="Nouvelle", auteur="Gautier", titre="La Morte amoureuse", date="1836",
  semaine=3, pages="env. 35 p.", heures=1.5, leger=True, passages=["morte"],
  acces="Domaine public : Wikisource.", cles=["Repérer le récit cadre : un vieux prêtre se confesse.", "Suivre la double vie, jour et nuit.", "Noter les signes du vampire (le sang, la pâleur)."],
  verif=[("Qui est Clarimonde ?", "Une courtisane morte qui revient la nuit ; elle boit le sang de Romuald."), ("Comment finit l'histoire ?", "L'abbé Sérapion ouvre son tombeau et l'asperge d'eau bénite ; elle tombe en poussière.")],
  prof=dict(resume="Le prêtre Romuald, le jour de son ordination, croise le regard de Clarimonde. Nommé dans une cure de campagne, il est appelé à son chevet : elle meurt, puis revient chaque nuit ; il vit en rêve une vie de seigneur à Venise avec elle, qui boit un peu de son sang. L'abbé Sérapion ouvre le tombeau de Clarimonde et la détruit avec de l'eau bénite.", structure="Récit enchâssé à la première personne ; hésitation entre rêve et réalité.", savoir=["Publiée dans la Chronique de Paris (1836), la revue de Balzac."], angle="Le corps contre l'Église ; l'art pour l'art et le goût du beau mort.", passages=["L'ouverture (dossier S3)"], piege="Le fantastique tient au doute, pas aux effets d'horreur.")),
 dict(id="coeur", fiche="Partie B", genre="Nouvelle", auteur="Flaubert", titre="Un cœur simple", date="1877",
  semaine=4, pages="env. 45 p.", heures=2, leger=True, passages=["coeur"],
  acces="Domaine public : Wikisource (Trois Contes).", cles=["Cinq chapitres : repérer les êtres aimés successivement par Félicité.", "Suivre le perroquet Loulou jusqu'à la dernière page.", "Noter les dates : un demi-siècle d'histoire de France en arrière-plan."],
  verif=[("Qui Félicité aime-t-elle successivement ?", "Théodore, Paul et Virginie (les enfants de Mme Aubain), son neveu Victor, le père Colmiche, le perroquet Loulou."), ("Que voit Félicité en mourant ?", "Un perroquet gigantesque dans les cieux entrouverts, qu'elle confond avec le Saint-Esprit.")],
  prof=dict(resume="Vie de Félicité, servante de Mme Aubain à Pont-l'Évêque pendant cinquante ans : amour déçu (Théodore), attachement aux enfants de sa maîtresse, à son neveu Victor mort aux Amériques, à la petite Virginie morte au couvent, puis au perroquet Loulou, qui, empaillé, se confond pour elle avec le Saint-Esprit.", structure="Cinq chapitres ; ellipses temporelles ; style indirect libre.", savoir=["Premier des Trois Contes (1877), avec La Légende de saint Julien l'Hospitalier et Hérodias."], angle="Une servante au centre du récit ; ironie et compassion.", passages=["L'ouverture (dossier S4)", "La mort de Félicité (chapitre V)"], piege="Ne pas lire l'ironie comme du mépris.")),
 dict(id="medan", fiche="Partie B (recueil intégral)", genre="Recueil de nouvelles", auteur="Zola, Maupassant, Huysmans, Céard, Hennique, Alexis", titre="Les Soirées de Médan", date="1880",
  semaine=5, pages="env. 280 p. (six nouvelles)", heures=9, leger=False, passages=["boule"],
  acces="Domaine public : Wikisource (Les Soirées de Médan).",
  cles=["Lire dans l'ordre : L'Attaque du moulin (Zola), Boule de suif (Maupassant), Sac au dos (Huysmans), La Saignée (Céard), L'Affaire du Grand 7 (Hennique), Après la bataille (Alexis).",
        "Chercher le point commun : la guerre de 1870 sans héroïsme.", "Comparer les tons : tragique (Zola), satirique (Maupassant), ironique et corporel (Huysmans)."],
  verif=[("Qui sont les six auteurs ?", "Zola, Maupassant, Huysmans, Céard, Hennique, Alexis."), ("Quel est le thème commun ?", "La guerre franco-prussienne de 1870-1871.")],
  prof=dict(resume="Recueil collectif publié en 1880 par Zola et cinq jeunes écrivains qui se réunissaient dans sa maison de Médan. Six nouvelles sur la guerre de 1870, contre le récit patriotique. Boule de suif, la plus célèbre, met en scène une prostituée sacrifiée par les bourgeois d'une diligence.", structure="Six nouvelles indépendantes ; ordre voulu, ouverture par Zola.", savoir=["Le recueil est souvent vu comme le manifeste collectif du naturalisme en récit court.", "Boule de suif lance la carrière de Maupassant."], angle="Bourdieu : un groupe se constitue en école autour d'un chef ; le recueil collectif est une prise de position dans le champ.", passages=["Boule de suif, ouverture (dossier S5)"], piege="Les six nouvelles n'ont pas la même qualité ; lire au moins Zola, Maupassant et Huysmans de près.")),
 dict(id="diaboliques", fiche="Partie B (recueil intégral)", genre="Recueil de nouvelles", auteur="Barbey d'Aurevilly", titre="Les Diaboliques", date="1874",
  semaine=5, pages="env. 330 p. (six nouvelles)", heures=13, leger=False, passages=["rideau"],
  acces="Domaine public : Wikisource (Les Diaboliques).",
  cles=["Lire dans l'ordre : Le Rideau cramoisi, Le Plus Bel Amour de Don Juan, Le Bonheur dans le crime, Le Dessous de cartes d'une partie de whist, À un dîner d'athées, La Vengeance d'une femme.",
        "Repérer chaque fois le récit cadre : qui raconte, à qui, dans quel lieu.", "Suivre les héroïnes : six femmes diaboliques, chacune à sa manière."],
  verif=[("Combien de nouvelles, et quel est leur point commun ?", "Six nouvelles, chacune centrée sur une femme qui transgresse."), ("Qu'arrive-t-il au livre en 1874 ?", "Il est saisi pour outrage à la morale publique.")],
  prof=dict(resume="Six récits racontés par des narrateurs de salon, d'officiers ou de dandys, où des femmes commettent ou inspirent des crimes, des passions ou des vengeances : Alberte qui meurt dans les bras de son amant (Le Rideau cramoisi), Hauteclaire et le comte de Savigny qui empoisonnent l'épouse (Le Bonheur dans le crime), la duchesse qui se prostitue pour déshonorer son mari (La Vengeance d'une femme).", structure="Récits encadrés, oralité, suspense, narrateurs aristocrates.", savoir=["Saisie en 1874 ; Barbey, catholique et monarchiste, affirme peindre le mal pour en inspirer l'horreur.", "Barbey, figure du dandysme littéraire."], angle="Une aristocratie déclassée raconte sa propre décadence ; le diabolique comme critique du siècle bourgeois.", passages=["Le Rideau cramoisi, ouverture (dossier S5)"], piege="Recueil long et à la langue difficile : le répartir sur plusieurs semaines.")),
 dict(id="horla", fiche="Partie B", genre="Nouvelle", auteur="Maupassant", titre="Le Horla", date="1887",
  semaine=5, pages="env. 35 p.", heures=1.5, leger=True, passages=["horla"],
  acces="Domaine public : Wikisource.", cles=["Un journal daté : noter les dates et l'aggravation.", "Repérer les épreuves : la carafe d'eau vide, la rose cueillie, le miroir.", "Lire la fin : l'incendie de la maison."],
  verif=[("Sous quelle forme le récit est-il écrit ?", "Un journal intime daté."), ("Que fait le narrateur à la fin ?", "Il met le feu à sa maison pour tuer le Horla, puis envisage de se tuer.")],
  prof=dict(resume="Un homme heureux près de Rouen sent peu à peu une présence invisible qui boit son eau, cueille une rose, l'empêche de se voir dans un miroir. Il nomme cet être le Horla, croit qu'il est arrivé avec un trois-mâts brésilien, incendie sa maison pour le tuer et conclut qu'il devra se tuer lui-même.", structure="Journal daté (8 mai à 10 septembre).", savoir=["Deux versions : 1886 (récit devant des médecins) et 1887 (journal)."], angle="La science (hypnose, magnétisme) et ses angoisses ; la peur d'une espèce qui succède à l'homme.", passages=["8 mai (dossier S5)"], piege="Ne pas réduire à la biographie de l'auteur.")),
 dict(id="classe", fiche="Partie B", genre="Nouvelle", auteur="Daudet", titre="La Dernière Classe", date="1872",
  semaine=5, pages="env. 6 p.", heures=0.5, leger=True, passages=["classe"],
  acces="Domaine public : Wikisource (Contes du lundi).", cles=["Lire en entier à voix haute (dix minutes).", "Suivre la transformation du narrateur, écolier paresseux.", "Discuter le mythe de la langue nationale."],
  verif=[("Pourquoi est-ce la dernière classe ?", "L'Alsace devient allemande : l'enseignement se fera désormais en allemand."), ("Qu'écrit M. Hamel au tableau ?", "Vive la France !")],
  prof=dict(resume="En Alsace, après la défaite de 1870, le petit Frantz arrive en retard à l'école et découvre que c'est la dernière classe de français ; le maître, M. Hamel, fait sa leçon devant les anciens du village et finit par écrire Vive la France ! au tableau.", structure="Conte bref, narrateur enfant, unité de temps.", savoir=["Contes du lundi (1873) ; conte longtemps présent dans les manuels scolaires."], angle="La langue comme patrie : construction d'un mythe national.", passages=["La fin (dossier S5)"], piege="Rappeler que l'alsacien était la langue parlée de la plupart des élèves.")),
 dict(id="vera", fiche="Partie B", genre="Nouvelle", auteur="Villiers de l'Isle-Adam", titre="Véra", date="1874",
  semaine=6, pages="env. 12 p.", heures=0.5, leger=True, passages=["vera"],
  acces="Domaine public : Wikisource (Contes cruels).", cles=["Repérer la volonté du comte : vivre comme si Véra était vivante.", "Noter les signes de son retour.", "Lire la dernière phrase et la clé du tombeau."],
  verif=[("Que décide le comte d'Athol après la mort de Véra ?", "De vivre comme si elle était encore là, avec son serviteur Raymond."), ("Que se passe-t-il quand il dit qu'elle est morte ?", "L'illusion s'efface ; la clé du tombeau tombe sur le lit.")],
  prof=dict(resume="Le comte d'Athol, après avoir enterré sa jeune femme Véra, s'enferme un an dans leur hôtel et vit comme si elle était vivante ; la volonté finit par la faire presque revenir, jusqu'au moment où il se souvient qu'elle est morte : tout s'évanouit, et la clé du tombeau tombe près de lui.", structure="Conte bref en crescendo.", savoir=["Publié en 1874, recueilli dans Contes cruels (1883)."], angle="Idéalisme contre positivisme ; une aristocratie hors du temps.", passages=["L'ouverture (dossier S6)"], piege="Comparer avec La Morte amoureuse plutôt que de raconter seulement.")),
]

# Calendrier de lecture sur 16 semaines : du début des cours à la fin janvier.
CALENDRIER = [
 ("S1", "12–18 oct.", "Choisir ses six œuvres A.1 (une par paire). Lire Mateo Falcone.", 1),
 ("S2", "19–25 oct.", "Lamartine ou Vivien : la première moitié du recueil. Lire La Morte amoureuse.", 3.5),
 ("S3", "26 oct.–1er nov.", "Lamartine ou Vivien : la fin du recueil. Lire Un cœur simple.", 4),
 ("S4", "2–8 nov.", "Baudelaire ou Gide : la première moitié.", 2.5),
 ("S5", "9–15 nov.", "Baudelaire ou Gide : la fin. Lire Le Horla et La Dernière Classe.", 4.5),
 ("S6", "16–22 nov.", "Le Bateau ivre ou la Prose du Transsibérien ; Moréas ou Marinetti ; Véra. Les Soirées de Médan : L'Attaque du moulin.", 4),
 ("S7", "23–29 nov.", "Salomé ou Ubu Roi. Les Soirées de Médan : Boule de suif.", 4.5),
 ("S8", "30 nov.–6 déc.", "Les Soirées de Médan : Sac au dos, La Saignée.", 3),
 ("S9", "7–13 déc.", "Les Soirées de Médan : L'Affaire du Grand 7, Après la bataille. Commencer le roman (Le Grand Meaulnes ou Les Caves du Vatican).", 4),
 ("S10", "14–20 déc.", "Le roman, suite.", 3.5),
 ("S11", "21–27 déc.", "Le roman, suite.", 3.5),
 ("S12", "28 déc.–3 janv.", "Le roman, fin.", 2.5),
 ("S13", "4–10 janv.", "Les Diaboliques : Le Rideau cramoisi, Le Plus Bel Amour de Don Juan.", 4.5),
 ("S14", "11–17 janv.", "Les Diaboliques : Le Bonheur dans le crime, Le Dessous de cartes d'une partie de whist.", 4.5),
 ("S15", "18–24 janv.", "Les Diaboliques : À un dîner d'athées, La Vengeance d'une femme. Envoyer la liste A.2 (au moins 30 jours avant l'examen).", 4),
 ("S16", "25–31 janv.", "Relire les passages clés des six œuvres A.1 et les fiches d'œuvres de la classe. Simulation d'oral à deux.", 2),
]

# Répartition des fiches d'œuvre entre les 8 groupes (5 étudiants par groupe).
GROUPES = [
 ("G1", "Méditations poétiques", "Les Diaboliques : Le Rideau cramoisi", "S2"),
 ("G2", "Études et préludes", "Les Diaboliques : Le Plus Bel Amour de Don Juan", "S7"),
 ("G3", "Le Spleen de Paris", "Les Diaboliques : Le Bonheur dans le crime", "S4"),
 ("G4", "Les Nourritures terrestres", "Les Diaboliques : Le Dessous de cartes d'une partie de whist", "S7"),
 ("G5", "Salomé et Ubu Roi", "Les Diaboliques : À un dîner d'athées", "S7"),
 ("G6", "Le Grand Meaulnes", "Les Diaboliques : La Vengeance d'une femme", "S8"),
 ("G7", "Les Caves du Vatican", "Les Soirées de Médan : L'Attaque du moulin, Sac au dos, La Saignée", "S8"),
 ("G8", "Le Bateau ivre, Prose du Transsibérien, Moréas, Marinetti", "Les Soirées de Médan : L'Affaire du Grand 7, Après la bataille", "S6"),
]

FICHE_OEUVRE = [
 ("Identité", "Auteur, date, genre, lieu et support de publication (revue, journal, éditeur)."),
 ("Structure", "Parties, chapitres ou mouvements, en cinq lignes au plus."),
 ("Personnages ou voix", "Qui parle, à qui, et qui sont les personnages principaux."),
 ("Trois passages clés", "Pour chacun : la page ou le chapitre, une citation courte, pourquoi ce passage compte."),
 ("Un thème, un procédé", "Un thème central et un procédé d'écriture, avec un exemple précis."),
 ("Pour l'oral", "À quel public l'auteur s'adresse-t-il ? Qu'apporte l'œuvre de nouveau par rapport à la tradition ? Une différence avec l'autre œuvre de la paire."),
 ("Une question de commentaire", "Une problématique possible sur l'un des trois passages."),
]

JOURNAL = [
 ("Nom et prénom", "réponse courte"),
 ("Semaine", "liste : S1 à S16"),
 ("Œuvre lue cette semaine", "liste : les œuvres de la fiche"),
 ("Pages ou chapitres lus", "réponse courte, par exemple : chapitres 1 à 6, p. 7-58"),
 ("Une phrase qui m'a arrêté(e), avec la page", "paragraphe"),
 ("En une phrase : ce qui se passe, ou ce que fait le texte", "paragraphe"),
 ("Ma difficulté principale", "cases : lexique, syntaxe, contexte historique, longueur, aucune"),
 ("Temps de lecture (en minutes)", "nombre"),
]
