# Guide de l'enseignant : l'essentiel de chaque semaine, glossaire, prononciation des noms,
# questions fréquentes des étudiants. Affiché sur les pages prof-sN.html.

PROF = {
1: dict(
 essentiel=[
  "La Révolution détruit le système qui faisait vivre et consacrait les écrivains : les académies sont supprimées le 8 août 1793, les pensions royales disparaissent. L'écrivain doit trouver un public.",
  "Beaucoup d'œuvres de 1790-1815 sont écrites hors de France : Chateaubriand émigré à Londres (1793-1800), Staël exilée par Napoléon à Coppet (Suisse). La censure impériale pilonne De l'Allemagne en 1810.",
  "Une sensibilité nouvelle vient d'Angleterre et d'Allemagne (Young, Ossian, Werther) : mélancolie, nature sauvage, ruines, confidence du moi. On l'appelle après coup préromantisme.",
  "Le mal du siècle (Musset, 1836) : la tristesse d'une jeunesse sans place après la Révolution et l'Empire. René (1802) en est le modèle français, Werther (1774) et Jacopo Ortis (1802) les modèles allemand et italien.",
  "La sociocritique lit la société dans le texte : ce qu'il dit, comment il le dit, ce qu'il tait (Paul et Virginie tait le travail des esclaves).",
  "La nouvelle moderne naît avec la presse au XIXe siècle : brève, une seule action, une fin forte. Elle est le fil rouge de la partie B de la fiche.",
  "La charte IA du cours : déclarer, vérifier, écrire soi-même, rester critique. L'IA propose, le lecteur vérifie.",
 ],
 glossaire=[("Préromantisme","Étiquette posée après coup sur la période 1760-1820 environ, où apparaissent des thèmes romantiques dans des formes encore classiques."),
  ("Mal du siècle","Tristesse sans objet d'une génération, décrite par Musset (1836) et incarnée par René."),
  ("Vague des passions","Expression de Chateaubriand : un désir sans objet précis, qui épuise l'âme avant d'avoir vécu."),
  ("Émigration","Départ des nobles et des prêtres hors de France pendant la Révolution (Chateaubriand à Londres)."),
  ("Sociocritique","Méthode de lecture (Claude Duchet, 1971) qui étudie la société dans la langue, les formes et les silences du texte."),
  ("Énallage de personne","Emploi d'une personne grammaticale à la place d'une autre (René parle de lui à la troisième personne)."),
  ("Nouvelle","Récit bref, une seule action, peu de personnages, une fin forte (la chute)."),
  ("Anthologie A.2","Liste personnelle de 50 extraits que l'étudiant constitue et fait valider avant l'examen.")],
 noms=[("Staël","Stal (le ë ne se prononce pas)"),("Chateaubriand","Cha-to-bri-an"),("Rousseau","Rou-sô"),("Bernardin de Saint-Pierre","Bèr-nar-din de Sin-Pierre"),
  ("Coppet","Co-pè"),("Ossian","O-si-an"),("Werther","Vèr-tèr"),("Goethe","Gueu-te (eu fermé)"),("Van Tieghem","Van Ti-gam ou Vann Ti-ghèm"),("Foscolo","comme en italien")],
 faq=[("Faut-il lire René en entier ?","Oui, c'est court (une quarantaine de pages) et c'est l'extrait A.2 le plus utile de la semaine."),
  ("Peut-on écrire la fiche de lecture en italien ?","Non : les productions sont en français, comme l'examen. L'italien sert pour comprendre et traduire."),
  ("Le préromantisme est-il au programme de l'examen ?","Le contexte socio-culturel du début du XIXe siècle fait partie de la partie A de la fiche : il faut savoir situer les œuvres."),
  ("Doit-on payer pour utiliser l'Atelier du siècle ?","Il fonctionne avec un compte claude.ai. En cas de difficulté, travailler en binôme ou sur le poste de l'enseignant.")]),

2: dict(
 essentiel=[
  "Le romantisme devient une école entre 1820 et 1830 : Méditations de Lamartine (1820), Préface de Cromwell de Hugo (1827), bataille d'Hernani (25 février 1830).",
  "Une école se fait par des lieux et des groupes (cénacles, salons, revues : l'Arsenal de Nodier, Le Globe, le salon de Hugo) avant d'avoir une doctrine (Stalloni).",
  "Bourdieu : le champ littéraire est un espace de luttes ; les nouveaux venus (Hugo, 25 ans en 1827) attaquent les installés (classiques, Académie) par des prises de position (préfaces, pièces).",
  "Le Lac (1820) : souvenir de Julie Charles (Elvire) au lac du Bourget ; le temps qui fuit, la nature gardienne de la mémoire ; alternance 12 / 6 dans la strophe Ô temps.",
  "Versification : trois règles (e muet, diérèse et synérèse, césure). Le e final des rimes féminines ne compte jamais.",
  "Mateo Falcone (1829) : un père tue son fils pour une trahison ; style sec, narrateur impassible ; une Corse imaginée depuis Paris.",
  "Pont italien : Manzoni contre les unités (1823), Verdi transforme Hernani en Ernani (1844).",
 ],
 glossaire=[("Cénacle","Petit groupe d'écrivains réunis régulièrement autour d'un maître."),
  ("Champ littéraire","Espace social de luttes pour la reconnaissance (Bourdieu)."),
  ("Prise de position","Œuvre, préface ou manifeste par lesquels un écrivain prend place dans le champ."),
  ("Alexandrin","Vers de douze syllabes, coupé en deux hémistiches de six à la césure."),
  ("E muet","E non accentué : compté devant consonne, élidé devant voyelle et en fin de vers."),
  ("Diérèse","Prononciation en deux syllabes de deux voyelles voisines (li-on)."),
  ("Enjambement","Phrase qui déborde d'un vers sur le suivant (escalier / Dérobé)."),
  ("Unités","Règles classiques : une seule action, un seul lieu, une seule journée.")],
 noms=[("Hernani","Èr-na-ni (h muet)"),("Lamartine","La-mar-tine"),("Vigny","Vi-gni"),("Musset","Mu-sè"),("Mérimée","Mé-ri-mé"),
  ("Mateo Falcone","Ma-té-o Fal-co-né"),("Fortunato","comme en italien"),("Cromwell","Crom-wèl"),("Chatterton","Cha-tèr-tone"),("Nodier","No-dié"),("Stalloni","Sta-lo-ni")],
 faq=[("Doit-on savoir scander pour l'examen ?","Oui pour le commentaire d'un poème : compter un vers, repérer la césure et les rimes fait partie de l'analyse."),
  ("Hernani est-il au programme ?","Pas dans la liste A.1, mais une scène peut entrer dans l'anthologie A.2."),
  ("Pourquoi Mateo tue-t-il son fils ?","Parce que Fortunato a trahi l'hospitalité en livrant un bandit pour une montre : pour Mateo, l'honneur de la famille passe avant tout.")]),

3: dict(
 essentiel=[
  "Monarchie de Juillet (1830-1848) : la bourgeoisie d'argent gouverne ; le roman devient le grand genre.",
  "1er juillet 1836 : La Presse de Girardin, journal à 40 francs payé par la publicité, publie des romans en épisodes : le roman-feuilleton naît.",
  "Stendhal (le miroir, Le Rouge et le Noir, 1830) et Balzac (La Comédie humaine) inventent le roman de la société ; ce sont les précurseurs du réalisme.",
  "Le Père Goriot (1835) : la trajectoire de Rastignac, de la pension Vauquer aux salons ; À nous deux maintenant !",
  "Bourdieu : capital économique, culturel, social ; ce qui compte, c'est la conversion d'un capital en un autre.",
  "La Morte amoureuse (1836) : le fantastique est l'hésitation entre explication naturelle et surnaturelle (Todorov).",
  "Méthode : la problématique est une vraie question sur le fonctionnement du texte, dont la réponse n'est pas évidente.",
 ],
 glossaire=[("Feuilleton","Bas de page du journal où paraît un roman par épisodes."),
  ("Capital culturel","Savoirs, diplômes, manières, goût (Bourdieu)."),
  ("Trajectoire","Chemin social d'un personnage ou d'un écrivain dans le temps."),
  ("Fantastique","Hésitation du lecteur entre une explication naturelle et une explication surnaturelle."),
  ("Problématique","Question à laquelle répond tout le commentaire."),
  ("Récit encadré","Histoire racontée par un personnage à un autre, à l'intérieur d'un premier récit.")],
 noms=[("Stendhal","Stin-dal ou Stan-dal"),("Rastignac","Ras-ti-gnac"),("Vautrin","Vô-trin"),("Goriot","Go-ri-o"),("Girardin","Ji-rar-din"),
  ("Sainte-Beuve","Sint-Beuv"),("Clarimonde","Cla-ri-monde"),("Romuald","Ro-mu-ald"),("Sérapion","Sé-ra-pi-on"),("Vauquer","Vô-ké")],
 faq=[("Faut-il lire tout Le Père Goriot ?","Non, il est en liste A.2 possible : la dernière page suffit pour l'anthologie, mais la lecture complète aide beaucoup."),
  ("Le fantastique existe-t-il dans d'autres semaines ?","Oui : Le Horla (semaine 5) et Véra (semaine 6).")]),

4: dict(
 essentiel=[
  "Second Empire (1852-1870) : l'État surveille la presse et la morale. En 1857, Madame Bovary est acquitté (7 février), Les Fleurs du mal condamnées (20 août, six poèmes supprimés).",
  "L'art pour l'art (Gautier, préface de Mademoiselle de Maupin, 1835) : le beau ne doit servir à rien. Le Parnasse (1866) en fait une école du travail et de la forme.",
  "Bourdieu : le champ devient autonome ; dans ce monde à l'envers, l'échec commercial ou judiciaire peut devenir un signe de valeur.",
  "Le Spleen de Paris (1869, posthume) : des poèmes en prose. L'Étranger refuse famille, patrie, beauté, or ; il aime les nuages.",
  "Un cœur simple (1877) : une servante héroïne, le style indirect libre, le perroquet Loulou confondu avec le Saint-Esprit.",
  "Madame Bovary, c'est moi : phrase jamais écrite par Flaubert, rapportée en 1909 par Descharmes d'après Amélie Bosquet.",
  "Méthode : le plan en deux ou trois axes, chaque axe est une idée.",
 ],
 glossaire=[("Art pour l'art","Doctrine selon laquelle l'art n'a d'autre but que la beauté."),
  ("Parnasse","Groupe de poètes (1866-1876) attachés à la perfection formelle et à l'impersonnalité."),
  ("Autonomie du champ","Capacité de la littérature à fixer ses propres règles de valeur, contre l'État et le marché."),
  ("Poème en prose","Poème sans vers ni rime, bref et intense (Bertrand, Baudelaire)."),
  ("Style indirect libre","Pensées d'un personnage rapportées dans la voix du narrateur, sans verbe introducteur."),
  ("Outrage à la morale publique","Délit pour lequel Flaubert et Baudelaire sont poursuivis en 1857.")],
 noms=[("Baudelaire","Bô-de-lèr"),("Flaubert","Flô-bèr"),("Pont-l'Évêque","Pon-lé-vèque"),("Félicité","Fé-li-ci-té"),("Loulou","Lou-lou"),
  ("Pinard","Pi-nar"),("Senard","Se-nar"),("Leconte de Lisle","Le-conte de Lil"),("Arsène Houssaye","Ar-sène Ou-sè"),("Enivrez-vous","An-ni-vré-vou (en se prononce an)")],
 faq=[("Les six poèmes condamnés sont-ils au programme ?","Non. On peut les lire, mais l'anthologie propose Au lecteur et L'Albatros."),
  ("Flaubert est-il réaliste ?","Il refuse l'étiquette ; les manuels le rangent dans le réalisme pour Madame Bovary et Un cœur simple. Le dire et l'expliquer.")]),

5: dict(
 essentiel=[
  "Après 1870 : Troisième République, école gratuite et obligatoire, liberté de la presse (1881) ; des centaines de journaux publient chaque jour des nouvelles.",
  "Le naturalisme (Zola) applique au roman la méthode des sciences : enquête, document, hérédité, milieu. Trois phases selon Stalloni : formation (1865-1876), âge d'or (1876-1884), éclatement (1884-1893).",
  "Les Soirées de Médan (1880) : six nouvelles sur 1870, un manifeste collectif ; Boule de suif révèle Maupassant.",
  "Barbey d'Aurevilly (Les Diaboliques, 1874) et Daudet (La Dernière Classe, 1872) écrivent des nouvelles hors de l'école.",
  "Bainville (1902) juge l'école en adversaire politique : mépris de classe et racisme contre Zola. On lit ce texte comme un document de combat.",
  "Le Horla (1887) : un journal intime, folie ou présence, l'hésitation fantastique.",
  "Verga, né à Catania, publie Vita dei campi en 1880 : le verismo dialogue avec le naturalisme.",
 ],
 glossaire=[("Naturalisme","École de Zola (vers 1865-1891) qui veut un roman scientifique, documenté, attentif au milieu et à l'hérédité."),
  ("Recueil","Ensemble de textes réunis avec un cadre, un ordre, des échos."),
  ("Dîner Trapp","Dîner du 16 avril 1877, naissance officielle de l'école naturaliste."),
  ("Antidreyfusard","Partisan de la culpabilité de Dreyfus, souvent nationaliste et antisémite (Bainville, l'Action française)."),
  ("Félibrige","Mouvement fondé en 1854 par Mistral pour la langue provençale."),
  ("Verismo","Courant italien proche du naturalisme (Verga, Capuana).")],
 noms=[("Zola","Zo-la"),("Maupassant","Mô-pa-san"),("Médan","Mé-dan"),("Barbey d'Aurevilly","Bar-bè dôr-vi-yi"),("Daudet","Dô-dè"),
  ("Huysmans","U-is-mans"),("Le Horla","Le Or-la (h non prononcé, sans élision : le Horla)"),("Bainville","Bin-vil"),("Mistral","Mis-tral"),("Médan, Tôtes","Mé-dan, Tôte")],
 faq=[("Faut-il lire tout le recueil de Médan ?","Oui, la fiche demande les deux recueils en intégralité ; c'est un livre court (six nouvelles)."),
  ("Pourquoi lire Bainville s'il est raciste ?","Pour comprendre comment la valeur d'un écrivain se joue aussi dans les combats politiques, et apprendre à reconnaître ces procédés."),
  ("Le Horla est-il une histoire vraie ?","Non, mais Maupassant, malade, s'intéressait à la folie et aux expériences de Charcot sur l'hypnose.")]),

6: dict(
 essentiel=[
  "1871-1886 : la poésie rompt avec la langue commune. Rimbaud veut se faire voyant (lettres de mai 1871), Verlaine cherche la musique, Mallarmé la suggestion.",
  "La Décadence (Zutistes, Hydropathes, Chat noir, Le Décadent) prépare le symbolisme ; Huysmans, À rebours (1884).",
  "Moréas publie Le Symbolisme dans Le Figaro le 18 septembre 1886 (le manuel de Stalloni écrit 1866 par erreur).",
  "Le Bateau ivre (1871) : vingt-cinq quatrains ; le je est le bateau, image du poète libéré.",
  "Zima : le sociolecte, la langue d'un groupe ; refuser la langue commune est une prise de position.",
  "Véra (1883) : un amour plus fort que la mort, une clef qui tombe, l'hésitation fantastique.",
  "Les grands poètes (Rimbaud, Verlaine, Mallarmé) restent en marge de l'école symboliste.",
 ],
 glossaire=[("Voyant","Pour Rimbaud, le poète qui accède à l'inconnu par le dérèglement de tous les sens."),
  ("Poète maudit","Poète rejeté par la société et reconnu par ses pairs (Verlaine, 1884)."),
  ("Décadence","Mouvement de jeunes poètes pessimistes et provocateurs des années 1880."),
  ("Symbolisme","École de poésie (1886) qui veut suggérer l'Idée par des formes sensibles."),
  ("Vers libre","Vers sans nombre fixe de syllabes, rythmé par le souffle."),
  ("Sociolecte","Langue d'un groupe social, avec ses mots et ses valeurs (Zima).")],
 noms=[("Rimbaud","Rin-bô"),("Verlaine","Vèr-lène"),("Mallarmé","Ma-lar-mé"),("Moréas","Mo-ré-as"),("Villiers de l'Isle-Adam","Vi-lié de li-la-dan"),
  ("Véra","Vé-ra"),("d'Athol","Da-tol"),("Huysmans","U-is-mans"),("Maeterlinck","Mè-tèr-linck"),("Laforgue","La-forgue")],
 faq=[("Faut-il comprendre tout Le Bateau ivre ?","Non : comprendre le mouvement (libération, visions, épuisement) et savoir commenter les cinq premières strophes."),
  ("Mallarmé est-il au programme ?","Pas en A.1 ; Brise marine peut entrer dans l'anthologie.")]),

7: dict(
 essentiel=[
  "1896, Théâtre de l'Œuvre de Lugné-Poe : Salomé de Wilde (11 février, Wilde en prison) et Ubu Roi de Jarry (10 décembre, scandale du mot Merdre).",
  "Salomé est écrite en français (1891) et interdite à Londres (1892) ; Ubu naît d'une farce de lycéens à Rennes.",
  "Gide, Les Nourritures terrestres (1897) : une prose poétique qui enseigne la ferveur à Nathanaël.",
  "René Vivien (Pauline Tarn, 1877-1909) : poétesse anglaise de langue française, disciple de Sappho, paire 1 de la liste A.1 avec Lamartine.",
  "Scandale et consécration : en 1830, 1857, 1896, les œuvres sifflées ou interdites deviennent des classiques.",
  "Bainville (1901-1904) montre ce que deviennent les poètes de 1889 : tirages de cinquante exemplaires, puis la Bourse, la presse, l'affaire Dreyfus.",
  "Méthode : conclure en répondant à la problématique et ouvrir sur une œuvre précise.",
 ],
 glossaire=[("Théâtre de l'Œuvre","Théâtre d'avant-garde fondé par Lugné-Poe en 1893."),
  ("Farce","Pièce comique grossière et excessive."),
  ("Drame symboliste","Théâtre poétique du mystère et de la suggestion (Maeterlinck, Wilde)."),
  ("Ferveur","Chez Gide, intensité du désir et du regard."),
  ("Consécration","Reconnaissance durable d'une œuvre (par les pairs, l'école, les institutions).")],
 noms=[("Lugné-Poe","Lu-gné-Pô"),("Jarry","Ja-ri"),("Ubu","U-bu"),("Wilde","Ouaïlde"),("Iokanaan","Io-ka-na-an"),("Gide","Jide (g doux)"),
  ("Nathanaël","Na-ta-na-èl"),("René Vivien","Re-né Vi-vi-in"),("Gémier","Jé-mié"),("Le Cardonnel","Le Car-do-nel")],
 faq=[("Doit-on choisir Salomé ou Ubu ?","Oui, la paire 5 de la liste A.1 : une pièce à lire en entier."),
  ("Peut-on dire merdre en classe ?","Oui, c'est le texte. On analyse l'effet de la lettre ajoutée.")]),

8: dict(
 essentiel=[
  "Marinetti publie le Manifeste du futurisme à la une du Figaro le 20 février 1909 : vitesse, machine, guerre ; le futurisme italien naît à Paris, en français.",
  "1913, année extraordinaire : Alcools, Prose du Transsibérien, Du côté de chez Swann, Le Grand Meaulnes. Août 1914 : la guerre ; Alain-Fournier meurt en septembre.",
  "Paire 6 : Le Grand Meaulnes (François Seurel raconte Meaulnes) ou Les Caves du Vatican (l'acte gratuit de Lafcadio).",
  "Années folles : un chrononyme (Myriam Juan) ; deuil, reconstruction, refus du vote des femmes en 1922 (Jean-Yves Le Naour).",
  "René Maran, Batouala : premier Goncourt d'un écrivain noir (1921), préface anticoloniale.",
  "Bilan : le pouvoir de consacrer passe des académies au public, aux tribunaux, aux groupes, aux prix et à l'école.",
  "Bilan IA : classer les erreurs de l'IA repérées au semestre (dates, attributions, citations, scansion, traduction).",
 ],
 glossaire=[("Futurisme","Avant-garde fondée par Marinetti (1909) : vitesse, machine, rupture avec le passé."),
  ("Chrononyme","Nom d'une période (Années folles, Belle Époque)."),
  ("Sotie","Récit satirique et farcesque (Les Caves du Vatican)."),
  ("Acte gratuit","Acte sans motif, pour prouver sa liberté (Lafcadio)."),
  ("Avant-garde","Groupe qui se proclame en rupture et en avance sur son temps.")],
 noms=[("Marinetti","comme en italien"),("Cendrars","San-drar"),("Alain-Fournier","A-lin-Four-nié"),("Meaulnes","Môn"),("Lafcadio","Laf-ca-di-o"),
  ("Fleurissoire","Fleu-ri-soir"),("Sonia Delaunay","So-ni-a De-lo-nè"),("Batouala","Ba-tou-a-la"),("Pitoëff","Pi-to-èf"),("Le Naour","Le Na-our")],
 faq=[("Le futurisme est-il fasciste ?","Marinetti se rallie au fascisme, mais le manifeste de 1909 le précède ; il glorifie déjà la guerre et le mépris de la femme : le dire."),
  ("Que faire après le cours ?","Compléter l'anthologie A.2, la faire valider au moins 30 jours avant l'examen, relire les six œuvres A.1 choisies.")]),
}
